ARTS: arts.h File Reference
arts.h File Reference
The global header file for ARTS.
#include <cstddef>
#include <cstdlib>
#include "matpack.h"
#include "mystring.h"
#include "debug.h"
#include "config_global.h"
#include <cassert>
Functions
void define_wsv_group_names ()
Define the array of workspace variable group names.
Index get_wsv_id (const String &name)
Get index of WSV.
Index get_wsv_id (const char *name)
Get index of WSV.
bool is_valid_keyword_group (const Index name)
void define_species_data ()
void define_lineshape_data ()
void define_lineshape_norm_data ()
void arts_exit (int status=EXIT_FAILURE)
This is the exit function of ARTS.
void arts_exit_with_error_message (const String &m, ArtsOut &os)
Print error message and exit.
Detailed Description
The global header file for ARTS.
This file is included directly or indirectly by each and every ARTS source file. It must therefor not contain stuff that should not always be present.
Note that you do not have to include this file explicitly in many cases, since it is included directly or indirectly by most ARTS header files.
Author
Stefan Buehler
Date
16.05.1999
Definition in file arts.h.
Function Documentation
arts_exit()
void arts_exit (int status)
This is the exit function of ARTS.
Whenever arts has to be terminated at some point, call this function.
You can call without any parameters, since the exit status then defaults to EXIT_FAILURE.
Parameters
status Exit code. EXIT_FAILURE if omitted.
Definition at line 42 of file arts.cc.
References add_basedir(), cleanup_output_file(), out_basename, and report_file.
Referenced by arts_exit_with_error_message(), Exit(), get_parameters(), interp_poly(), main(), operator<<(), AgRecord::operator=(), MdRecord::operator=(), option_describe(), option_input(), option_methods(), option_workspacevariables(), polite_goodby(), set_reporting_level(), and VectorInsertGridPoints().
arts_exit_with_error_message()
void arts_exit_with_error_message (const String & m, ArtsOut & out)
Print error message and exit.
This function is intended for use in catch blocks.
Parameters
m Error message.
m ArtsOut stream to use.
Author
Stefan Buehler
Date
2008-05-09
Definition at line 64 of file arts.cc.
References arts_exit().
Referenced by Arts(), Arts2(), and main().
define_lineshape_data()
void define_lineshape_data ()
Definition at line 1928 of file lineshapes.cc.
References faddeeva_algorithm_916(), hui_etal_1978_lineshape(), lineshape_CO2_drayson(), lineshape_CO2_lorentz(), global_data::lineshape_data, lineshape_doppler(), lineshape_lorentz(), lineshape_no_shape(), lineshape_voigt_drayson(), lineshape_voigt_kuntz3(), lineshape_voigt_kuntz4(), and lineshape_voigt_kuntz6().
Referenced by main().
define_lineshape_norm_data()
void define_lineshape_norm_data ()
Definition at line 2033 of file lineshapes.cc.
References global_data::lineshape_norm_data, lineshape_norm_no_norm(), lineshape_norm_quadratic(), and lineshape_norm_VVH().
Referenced by main().
define_species_data()
void define_species_data ()
Definition at line 158 of file species_data.cc.
References define_basic_species_data(), and define_partition_species_data().
Referenced by main().
define_wsv_group_names()
void define_wsv_group_names ()
Define the array of workspace variable group names.
This defines the global variable wsv_group_names. It is used in two different programs:
In arts.
In make_wsv_group_h.
Author
Stefan Buehler
Date
2000-08-04
Definition at line 84 of file groups.cc.
References define_valid_keyword_groups(), define_wsv_group_map(), and global_data::wsv_group_names.
Referenced by main().
get_wsv_id() [1/2]
Index get_wsv_id (const char * name)
Get index of WSV.
Returns the index the Workspace of the given WSV.
Convenience function which can be called from within the debugger because it takes a plain char pointer instead of a String object as input.
Parameters
[in] name WSV name
Returns
Index in Workspace
Author
Oliver Lemke
Definition at line 5020 of file workspace.cc.
References get_wsv_id().
get_wsv_id() [2/2]
Index get_wsv_id (const String & name)
Get index of WSV.
Returns the index the Workspace of the given WSV.
Parameters
[in] name WSV name
Returns
Index in Workspace
Author
Oliver Lemke
Definition at line 4998 of file workspace.cc.
References Workspace::WsvMap.
Referenced by AgRecord::AgRecord(), Arts2(), Agenda::execute(), get_wsv_id(), main(), and MdRecord::MdRecord().
is_valid_keyword_group()
bool is_valid_keyword_group (const Index name)
Definition at line 157 of file groups.cc.
References Array< base >::nelem(), and valid_keyword_groups.