ARTS: IsotopologueRecord Class Reference
IsotopologueRecord Class Reference
Contains the lookup data for one isotopologue.
#include <absorption.h>
Public Types
enum { PF_FROMCOEFF, PF_FROMTEMP, PF_NOTHING }
Public Member Functions
IsotopologueRecord ()
Default constructor.
IsotopologueRecord (const IsotopologueRecord &x)
Copy constructor.
IsotopologueRecord (const String &name, const Numeric &abundance, const Numeric &mass, const Index &mytrantag, const Index &hitrantag, const MakeArray< Index > &jpltags)
Constructor that sets the values.
const String & Name () const
Isotopologue name.
const Numeric & Abundance () const
Normal abundance (= isotopologue ratio).
const Numeric & Mass () const
Mass of the isotopologue.
const Index & MytranTag () const
MYTRAN2 tag numbers for all isotopologues.
const Index & HitranTag () const
HITRAN-96 tag numbers for all isotopologues.
const ArrayOfIndex & JplTags () const
JPL tag numbers for all isotopologues.
bool isContinuum () const
Check if isotopologue is actually a continuum.
void SetPartitionFctCoeff (const ArrayOfNumeric &qcoeff, const Index &qcoefftype)
Numeric CalculatePartitionFctRatio (Numeric reference_temperature, Numeric actual_temperature) const
Calculate partition function ratio.
Private Member Functions
Numeric CalculatePartitionFctAtTempFromCoeff (Numeric temperature) const
Numeric CalculatePartitionFctAtTempFromData (Numeric temperature) const
Private Attributes
String mname
Numeric mabundance
Numeric mmass
Index mmytrantag
Index mhitrantag
ArrayOfIndex mjpltags
Vector mqcoeff
Index mqcoefftype
Vector mqcoeffgrid
Index mqcoeffinterporder
Detailed Description
Contains the lookup data for one isotopologue.
Author
Stefan Buehler
Definition at line 191 of file absorption.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
PF_FROMCOEFF
PF_FROMTEMP
PF_NOTHING
Definition at line 338 of file absorption.h.
Constructor & Destructor Documentation
IsotopologueRecord() [1/3]
IsotopologueRecord::IsotopologueRecord () inline
Default constructor.
Needed by make_array.
Definition at line 195 of file absorption.h.
IsotopologueRecord() [2/3]
IsotopologueRecord::IsotopologueRecord (const IsotopologueRecord & x) inline
Copy constructor.
We need this, since operator= does not work correctly for Arrays. (Target Array has to be resized first.)
Definition at line 209 of file absorption.h.
IsotopologueRecord() [3/3]
IsotopologueRecord::IsotopologueRecord (const String & name, const Numeric & abundance, const Numeric & mass, const Index & mytrantag, const Index & hitrantag, const MakeArray< Index > & jpltags) inline
Constructor that sets the values.
Definition at line 223 of file absorption.h.
References mhitrantag, mjpltags, mmytrantag, and Array< base >::nelem().
Member Function Documentation
Abundance()
const Numeric& IsotopologueRecord::Abundance () const inline
Normal abundance (= isotopologue ratio).
(Absolute number.)
Definition at line 257 of file absorption.h.
References mabundance.
Referenced by xml_write_to_stream().
CalculatePartitionFctAtTempFromCoeff()
Numeric IsotopologueRecord::CalculatePartitionFctAtTempFromCoeff (Numeric temperature) const private
Definition at line 56 of file absorption.cc.
References VectorView::begin(), VectorView::end(), and mqcoeff.
Referenced by CalculatePartitionFctRatio().
CalculatePartitionFctAtTempFromData()
Numeric IsotopologueRecord::CalculatePartitionFctAtTempFromData (Numeric temperature) const private
Definition at line 79 of file absorption.cc.
References gridpos_poly(), interp(), interpweights(), mqcoeff, mqcoeffgrid, and mqcoeffinterporder.
Referenced by CalculatePartitionFctRatio().
CalculatePartitionFctRatio()
Numeric IsotopologueRecord::CalculatePartitionFctRatio (Numeric reference_temperature, Numeric actual_temperature) const inline
Calculate partition function ratio.
This computes the partition function ratio Q(Tref)/Q(T).
Unfortunately, we have to recalculate also Q(Tref) for each spectral line, because the reference temperatures can be different!
Parameters
reference_temperature The reference temperature.
actual_temperature The actual temperature.
Returns
The ratio.
Definition at line 295 of file absorption.h.
References CalculatePartitionFctAtTempFromCoeff(), CalculatePartitionFctAtTempFromData(), mname, mqcoefftype, PF_FROMCOEFF, and PF_FROMTEMP.
Referenced by xsec_species().
HitranTag()
const Index& IsotopologueRecord::HitranTag () const inline
HITRAN-96 tag numbers for all isotopologues.
-1 means not included.
Definition at line 264 of file absorption.h.
References mhitrantag.
Referenced by xml_write_to_stream().
isContinuum()
bool IsotopologueRecord::isContinuum () const inline
Check if isotopologue is actually a continuum.
Returns
True if this is a continuum.
Definition at line 274 of file absorption.h.
References mname.
JplTags()
const ArrayOfIndex& IsotopologueRecord::JplTags () const inline
JPL tag numbers for all isotopologues.
Empty array means not included. There can be more than one JPL tag for an isotopologue species, because in JPL different vibrational states have different tags.
Definition at line 268 of file absorption.h.
References mjpltags.
Referenced by xml_write_to_stream().
Mass()
const Numeric& IsotopologueRecord::Mass () const inline
Mass of the isotopologue.
(In unified atomic mass units u) If I understand this correctly this is the same as g/mol.
Definition at line 260 of file absorption.h.
References mmass.
Referenced by xml_write_to_stream(), and xsec_species().
MytranTag()
const Index& IsotopologueRecord::MytranTag () const inline
MYTRAN2 tag numbers for all isotopologues.
-1 means not included.
Definition at line 262 of file absorption.h.
References mmytrantag.
Referenced by xml_write_to_stream().
Name()
const String& IsotopologueRecord::Name () const inline
Isotopologue name.
Definition at line 255 of file absorption.h.
References mname.
Referenced by xml_write_to_stream().
SetPartitionFctCoeff()
void IsotopologueRecord::SetPartitionFctCoeff (const ArrayOfNumeric & qcoeff, const Index & qcoefftype) inline
Definition at line 276 of file absorption.h.
References mqcoeff, and mqcoefftype.
Member Data Documentation
mabundance
Numeric IsotopologueRecord::mabundance private
Definition at line 352 of file absorption.h.
Referenced by Abundance().
mhitrantag
Index IsotopologueRecord::mhitrantag private
Definition at line 355 of file absorption.h.
Referenced by HitranTag(), and IsotopologueRecord().
mjpltags
ArrayOfIndex IsotopologueRecord::mjpltags private
Definition at line 356 of file absorption.h.
Referenced by IsotopologueRecord(), and JplTags().
mmass
Numeric IsotopologueRecord::mmass private
Definition at line 353 of file absorption.h.
Referenced by Mass().
mmytrantag
Index IsotopologueRecord::mmytrantag private
Definition at line 354 of file absorption.h.
Referenced by IsotopologueRecord(), and MytranTag().
mname
String IsotopologueRecord::mname private
Definition at line 351 of file absorption.h.
Referenced by CalculatePartitionFctRatio(), isContinuum(), and Name().
mqcoeff
Vector IsotopologueRecord::mqcoeff private
Definition at line 357 of file absorption.h.
Referenced by CalculatePartitionFctAtTempFromCoeff(), CalculatePartitionFctAtTempFromData(), and SetPartitionFctCoeff().
mqcoeffgrid
Vector IsotopologueRecord::mqcoeffgrid private
Definition at line 359 of file absorption.h.
Referenced by CalculatePartitionFctAtTempFromData().
mqcoeffinterporder
Index IsotopologueRecord::mqcoeffinterporder private
Definition at line 360 of file absorption.h.
Referenced by CalculatePartitionFctAtTempFromData().
mqcoefftype
Index IsotopologueRecord::mqcoefftype private
Definition at line 358 of file absorption.h.
Referenced by CalculatePartitionFctRatio(), and SetPartitionFctCoeff().
The documentation for this class was generated from the following files:
absorption.h
absorption.cc