ARTS: Tensor4View Class Reference
Tensor4View Class Reference
The Tensor4View class.
#include <matpackIV.h>
Public Member Functions
ConstTensor4View operator() (const Range &b, const Range &p, const Range &r, const Range &c) const
Const index operator for subrange.
ConstTensor3View operator() (const Range &b, const Range &p, const Range &r, Index c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (const Range &b, const Range &p, Index r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (const Range &b, Index p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (Index b, const Range &p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstMatrixView operator() (const Range &b, const Range &p, Index r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (const Range &b, Index p, const Range &r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (const Range &b, Index p, Index r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index b, const Range &p, Index r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index b, const Range &p, const Range &r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index b, Index p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstVectorView operator() (const Range &b, Index p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index b, const Range &p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index b, Index p, const Range &r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index b, Index p, Index r, const Range &c) const
Const index operator returning an object of type ConstVectorView.
Numeric operator() (Index b, Index p, Index r, Index c) const
Plain const index operator.
Numeric get (Index b, Index p, Index r, Index c) const
Get element implementation without assertions.
Tensor4View operator() (const Range &b, const Range &p, const Range &r, const Range &c)
Index operator for subrange.
Tensor3View operator() (const Range &b, const Range &p, const Range &r, Index c)
Index operator returning an object of type Tensor3View.
Tensor3View operator() (const Range &b, const Range &p, Index r, const Range &c)
Index operator returning an object of type Tensor3View.
Tensor3View operator() (const Range &b, Index p, const Range &r, const Range &c)
Index operator returning an object of type Tensor3View.
Tensor3View operator() (Index b, const Range &p, const Range &r, const Range &c)
Index operator returning an object of type Tensor3View.
MatrixView operator() (const Range &b, const Range &p, Index r, Index c)
Index operator returning an object of type MatrixView.
MatrixView operator() (const Range &b, Index p, const Range &r, Index c)
Index operator returning an object of type MatrixView.
MatrixView operator() (const Range &b, Index p, Index r, const Range &c)
Index operator returning an object of type MatrixView.
MatrixView operator() (Index b, const Range &p, Index r, const Range &c)
Index operator returning an object of type MatrixView.
MatrixView operator() (Index b, const Range &p, const Range &r, Index c)
Index operator returning an object of type MatrixView.
MatrixView operator() (Index b, Index p, const Range &r, const Range &c)
Index operator returning an object of type MatrixView.
VectorView operator() (const Range &b, Index p, Index r, Index c)
Index operator returning an object of type VectorView.
VectorView operator() (Index b, const Range &p, Index r, Index c)
Index operator returning an object of type VectorView.
VectorView operator() (Index b, Index p, const Range &r, Index c)
Index operator returning an object of type VectorView.
VectorView operator() (Index b, Index p, Index r, const Range &c)
Index operator returning an object of type VectorView.
Numeric & operator() (Index b, Index p, Index r, Index c)
Plain non-const index operator.
Numeric & get (Index b, Index p, Index r, Index c)
Get element implementation without assertions.
const Numeric * get_c_array () const
Conversion to plain C-array.
Numeric * get_c_array ()
Conversion to plain C-array.
ConstIterator4D begin () const
Return const iterator to first book.
ConstIterator4D end () const
Return const iterator behind last book.
Iterator4D begin ()
Return iterator to first book.
Iterator4D end ()
Return iterator behind last book.
Tensor4View & operator= (const ConstTensor4View &v)
Assignment operator.
Tensor4View & operator= (const Tensor4View &v)
Assignment from Tensor4View to Tensor4View.
Tensor4View & operator= (const Tensor4 &v)
Assignment from a Tensor4.
Tensor4View & operator= (Numeric x)
Assigning a scalar to a Tensor4View will set all elements to this value.
Tensor4View & operator*= (Numeric x)
Multiplication by scalar.
Tensor4View & operator/= (Numeric x)
Division by scalar.
Tensor4View & operator+= (Numeric x)
Addition of scalar.
Tensor4View & operator-= (Numeric x)
Subtraction of scalar.
Tensor4View & operator*= (const ConstTensor4View &x)
Element-vise multiplication by another Tensor4.
Tensor4View & operator/= (const ConstTensor4View &x)
Element-vise division by another Tensor4.
Tensor4View & operator+= (const ConstTensor4View &x)
Element-vise addition of another Tensor4.
Tensor4View & operator-= (const ConstTensor4View &x)
Element-vise subtraction of another Tensor4.
virtual ~Tensor4View ()
Destructor.
Tensor4View (const Tensor3View &a)
Special constructor to make a Tensor4 view of a Tensor3.
Public Member Functions inherited from ConstTensor4View
Index nbooks () const
Returns the number of books.
Index npages () const
Returns the number of pages.
Index nrows () const
Returns the number of rows.
Index ncols () const
Returns the number of columns.
ConstTensor4View operator() (const Range &b, const Range &p, const Range &r, const Range &c) const
Const index operator for subrange.
ConstTensor3View operator() (const Range &b, const Range &p, const Range &r, Index c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (const Range &b, const Range &p, Index r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (const Range &b, Index p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (Index b, const Range &p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstMatrixView operator() (const Range &b, const Range &p, Index r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (const Range &b, Index p, const Range &r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (const Range &b, Index p, Index r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index b, const Range &p, Index r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index b, const Range &p, const Range &r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index b, Index p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstVectorView operator() (const Range &b, Index p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index b, const Range &p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index b, Index p, const Range &r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index b, Index p, Index r, const Range &c) const
Const index operator returning an object of type ConstVectorView.
Numeric operator() (Index b, Index p, Index r, Index c) const
Plain const index operator.
Numeric get (Index b, Index p, Index r, Index c) const
Get element implementation without assertions.
ConstIterator4D begin () const
Return const iterator to first book.
ConstIterator4D end () const
Return const iterator behind last book.
virtual ~ConstTensor4View ()
Destructor.
ConstTensor4View (const ConstTensor3View &a)
Special constructor to make a Tensor4 view of a Tensor3.
Protected Member Functions
Tensor4View ()
Default constructor.
Tensor4View (Numeric *data, const Range &b, const Range &p, const Range &r, const Range &c)
Explicit constructor.
Tensor4View (Numeric *data, const Range &pb, const Range &pp, const Range &pr, const Range &pc, const Range &nb, const Range &np, const Range &nr, const Range &nc)
Recursive constructor.
Protected Member Functions inherited from ConstTensor4View
ConstTensor4View ()
Default constructor.
ConstTensor4View (Numeric *data, const Range &b, const Range &p, const Range &r, const Range &c)
Explicit constructor.
ConstTensor4View (Numeric *data, const Range &pb, const Range &pp, const Range &pr, const Range &pc, const Range &nb, const Range &np, const Range &nr, const Range &nc)
Recursive constructor.
Friends
class Iterator5D
class Tensor5View
class Tensor6View
class Tensor7View
Additional Inherited Members
Protected Attributes inherited from ConstTensor4View
Range mbr
The book range of mdata that is actually used.
Range mpr
The page range of mdata that is actually used.
Range mrr
The row range of mdata that is actually used.
Range mcr
The column range of mdata that is actually used.
Numeric * mdata
Pointer to the plain C array that holds the data.
Detailed Description
The Tensor4View class.
This contains the main implementation of a Tensor4. It defines the concepts of Tensor4View. Plus additionally the recursive subrange operator, which makes it possible to create a Tensor4View from a subrange of a Tensor4View.
The class Tensor4 is just a special case of a Tensor4View which also allocates storage.
Definition at line 243 of file matpackIV.h.
Constructor & Destructor Documentation
~Tensor4View()
virtual Tensor4View::~Tensor4View () inline virtual
Destructor.
Definition at line 350 of file matpackIV.h.
Tensor4View() [1/4]
Tensor4View::Tensor4View (const Tensor3View & a)
Special constructor to make a Tensor4 view of a Tensor3.
Definition at line 1197 of file matpackIV.cc.
Tensor4View() [2/4]
Tensor4View::Tensor4View () protected
Default constructor.
This is necessary, so that we can have a default constructor for the derived class Tensor4.
Definition at line 1212 of file matpackIV.cc.
Referenced by operator()().
Tensor4View() [3/4]
Tensor4View::Tensor4View (Numeric * data, const Range & br, const Range & pr, const Range & rr, const Range & cr) protected
Explicit constructor.
This one is used by Tensor4 to initialize its own Tensor4View part. The row range rr must have a stride to account for the length of one row.
Definition at line 1221 of file matpackIV.cc.
Tensor4View() [4/4]
Tensor4View::Tensor4View (Numeric * data, const Range & pb, const Range & pp, const Range & pr, const Range & pc, const Range & nb, const Range & np, const Range & nr, const Range & nc) protected
Recursive constructor.
This is used to construct SubMatrices from SubMatrices. That means that the new ranges have to be interpreted relative to the original ranges.
The new ranges may contain -1 for the extent which acts as a joker. However, the used Range constructor converts this to an explicit range, consistent with the original Range.
Parameters
*data The actual data.
pb Previous range.
pp Previous range.
pr Previous range.
pc Previous range.
nb New Range.
np New Range.
nr New Range.
nc New Range.
Definition at line 1249 of file matpackIV.cc.
Member Function Documentation
begin() [1/2]
Iterator4D Tensor4View::begin ()
Return iterator to first book.
Definition at line 1009 of file matpackIV.cc.
References ConstTensor4View::mbr, ConstTensor4View::mcr, ConstTensor4View::mdata, ConstTensor4View::mpr, ConstTensor4View::mrr, Range::mstart, and Range::mstride.
begin() [2/2]
ConstIterator4D Tensor4View::begin () const
Return const iterator to first book.
Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 997 of file matpackIV.cc.
References ConstTensor4View::begin().
Referenced by copy(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), Tensor4::operator=(), Tensor4::Tensor4(), and transform().
end() [1/2]
Iterator4D Tensor4View::end ()
Return iterator behind last book.
Definition at line 1017 of file matpackIV.cc.
References ConstTensor4View::mbr, ConstTensor4View::mcr, ConstTensor4View::mdata, Range::mextent, ConstTensor4View::mpr, ConstTensor4View::mrr, Range::mstart, and Range::mstride.
end() [2/2]
ConstIterator4D Tensor4View::end () const
Return const iterator behind last book.
Definition at line 1003 of file matpackIV.cc.
References ConstTensor4View::end().
Referenced by copy(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), Tensor4::operator=(), and Tensor4::Tensor4().
get() [1/2]
Numeric& Tensor4View::get (Index b, Index p, Index r, Index c) inline
Get element implementation without assertions.
Definition at line 312 of file matpackIV.h.
References ConstTensor4View::mbr, ConstTensor4View::mcr, ConstTensor4View::mdata, ConstTensor4View::mpr, ConstTensor4View::mrr, Range::mstart, and Range::mstride.
get() [2/2]
Numeric Tensor4View::get (Index b, Index p, Index r, Index c) const inline
Get element implementation without assertions.
Definition at line 272 of file matpackIV.h.
References ConstTensor4View::get().
Referenced by interpweights(), and operator()().
get_c_array() [1/2]
Numeric * Tensor4View::get_c_array ()
Conversion to plain C-array.
This function returns a pointer to the raw data. It fails if the Tensor4View is not pointing to the beginning of a Tensor4 or the stride is not 1 because the caller expects to get a C array with continuous data.
Definition at line 385 of file matpackIV.cc.
References ConstTensor4View::mbr, ConstTensor4View::mcr, ConstTensor4View::mdata, Range::mextent, ConstTensor4View::mpr, ConstTensor4View::mrr, Range::mstart, and Range::mstride.
get_c_array() [2/2]
const Numeric * Tensor4View::get_c_array () const
Conversion to plain C-array.
This function returns a pointer to the raw data. It fails if the Tensor4View is not pointing to the beginning of a Tensor4 or the stride is not 1 because the caller expects to get a C array with continuous data.
Definition at line 402 of file matpackIV.cc.
References ConstTensor4View::mbr, ConstTensor4View::mcr, ConstTensor4View::mdata, Range::mextent, ConstTensor4View::mpr, ConstTensor4View::mrr, Range::mstart, and Range::mstride.
Referenced by nca_get_data_Tensor4(), nca_put_var_Tensor4(), nca_read_from_file(), nca_write_to_file(), Reduce(), and WriteMolTau().
operator()() [1/32]
Tensor4View Tensor4View::operator() (const Range & b, const Range & p, const Range & r, const Range & c)
Index operator for subrange.
We have to also account for the case, that *this is already a subrange of a Tensor4. This allows correct recursive behavior.
Definition at line 705 of file matpackIV.cc.
References ConstTensor4View::mbr, ConstTensor4View::mcr, ConstTensor4View::mdata, ConstTensor4View::mpr, ConstTensor4View::mrr, and Tensor4View().
operator()() [2/32]
ConstTensor4View Tensor4View::operator() (const Range & b, const Range & p, const Range & r, const Range & c) const
Const index operator for subrange.
We have to also account for the case, that *this is already a subrange of a Tensor4. This allows correct recursive behavior. Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 526 of file matpackIV.cc.
References ConstTensor4View::operator()().
operator()() [3/32]
Tensor3View Tensor4View::operator() (const Range & b, const Range & p, const Range & r, Index c)
Index operator returning an object of type Tensor3View.
(Reducing the dimension by one.)
Definition at line 717 of file matpackIV.cc.
References ConstTensor4View::mbr, ConstTensor4View::mcr, ConstTensor4View::mdata, Range::mextent, ConstTensor4View::mpr, ConstTensor4View::mrr, Range::mstart, and Range::mstride.
operator()() [4/32]
ConstTensor3View Tensor4View::operator() (const Range & b, const Range & p, const Range & r, Index c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by one.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 538 of file matpackIV.cc.
References ConstTensor4View::operator()().
operator()() [5/32]
Tensor3View Tensor4View::operator() (const Range & b, const Range & p, Index r, const Range & c)
Index operator returning an object of type Tensor3View.
(Reducing the dimension by one.)
Definition at line 734 of file matpackIV.cc.
References ConstTensor4View::mbr, ConstTensor4View::mcr, ConstTensor4View::mdata, Range::mextent, ConstTensor4View::mpr, ConstTensor4View::mrr, Range::mstart, and Range::mstride.
operator()() [6/32]
ConstTensor3View Tensor4View::operator() (const Range & b, const Range & p, Index r, const Range & c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by one.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 550 of file matpackIV.cc.
References ConstTensor4View::operator()().
operator()() [7/32]
MatrixView Tensor4View::operator() (const Range & b, const Range & p, Index r, Index c)
Index operator returning an object of type MatrixView.
(Reducing the dimension by two.)
Definition at line 785 of file matpackIV.cc.
References ConstTensor4View::mbr, ConstTensor4View::mcr, ConstTensor4View::mdata, Range::mextent, ConstTensor4View::mpr, ConstTensor4View::mrr, Range::mstart, and Range::mstride.
operator()() [8/32]
ConstMatrixView Tensor4View::operator() (const Range & b, const Range & p, Index r, Index c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by two.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 586 of file matpackIV.cc.
References ConstTensor4View::operator()().
operator()() [9/32]
Tensor3View Tensor4View::operator() (const Range & b, Index p, const Range & r, const Range & c)
Index operator returning an object of type Tensor3View.
(Reducing the dimension by one.)
Definition at line 751 of file matpackIV.cc.
References ConstTensor4View::mbr, ConstTensor4View::mcr, ConstTensor4View::mdata, Range::mextent, ConstTensor4View::mpr, ConstTensor4View::mrr, Range::mstart, and Range::mstride.
operator()() [10/32]
ConstTensor3View Tensor4View::operator() (const Range & b, Index p, const Range & r, const Range & c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by one.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 562 of file matpackIV.cc.
References ConstTensor4View::operator()().
operator()() [11/32]
MatrixView Tensor4View::operator() (const Range & b, Index p, const Range & r, Index c)
Index operator returning an object of type MatrixView.
(Reducing the dimension by two.)
Definition at line 805 of file matpackIV.cc.
References ConstTensor4View::mbr, ConstTensor4View::mcr, ConstTensor4View::mdata, Range::mextent, ConstTensor4View::mpr, ConstTensor4View::mrr, Range::mstart, and Range::mstride.
operator()() [12/32]
ConstMatrixView Tensor4View::operator() (const Range & b, Index p, const Range & r, Index c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by two.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 598 of file matpackIV.cc.
References ConstTensor4View::operator()().
operator()() [13/32]
MatrixView Tensor4View::operator() (const Range & b, Index p, Index r, const Range & c)
Index operator returning an object of type MatrixView.
(Reducing the dimension by two.)
Definition at line 825 of file matpackIV.cc.
References ConstTensor4View::mbr, ConstTensor4View::mcr, ConstTensor4View::mdata, Range::mextent, ConstTensor4View::mpr, ConstTensor4View::mrr, Range::mstart, and Range::mstride.
operator()() [14/32]
ConstMatrixView Tensor4View::operator() (const Range & b, Index p, Index r, const Range & c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by two.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 610 of file matpackIV.cc.
References ConstTensor4View::operator()().
operator()() [15/32]
VectorView Tensor4View::operator() (const Range & b, Index p, Index r, Index c)
Index operator returning an object of type VectorView.
(Reducing the dimension by three.)
Definition at line 905 of file matpackIV.cc.
References ConstTensor4View::mbr, ConstTensor4View::mcr, ConstTensor4View::mdata, Range::mextent, ConstTensor4View::mpr, ConstTensor4View::mrr, Range::mstart, and Range::mstride.
operator()() [16/32]
ConstVectorView Tensor4View::operator() (const Range & b, Index p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
(Reducing the dimension by three.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 658 of file matpackIV.cc.
References ConstTensor4View::operator()().
operator()() [17/32]
Tensor3View Tensor4View::operator() (Index b, const Range & p, const Range & r, const Range & c)
Index operator returning an object of type Tensor3View.
(Reducing the dimension by one.)
Definition at line 768 of file matpackIV.cc.
References ConstTensor4View::mbr, ConstTensor4View::mcr, ConstTensor4View::mdata, Range::mextent, ConstTensor4View::mpr, ConstTensor4View::mrr, Range::mstart, and Range::mstride.
operator()() [18/32]
ConstTensor3View Tensor4View::operator() (Index b, const Range & p, const Range & r, const Range & c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by one.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 574 of file matpackIV.cc.
References ConstTensor4View::operator()().
operator()() [19/32]
MatrixView Tensor4View::operator() (Index b, const Range & p, const Range & r, Index c)
Index operator returning an object of type MatrixView.
(Reducing the dimension by two.)
Definition at line 865 of file matpackIV.cc.
References ConstTensor4View::mbr, ConstTensor4View::mcr, ConstTensor4View::mdata, Range::mextent, ConstTensor4View::mpr, ConstTensor4View::mrr, Range::mstart, and Range::mstride.
operator()() [20/32]
ConstMatrixView Tensor4View::operator() (Index b, const Range & p, const Range & r, Index c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by two.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 634 of file matpackIV.cc.
References ConstTensor4View::operator()().
operator()() [21/32]
MatrixView Tensor4View::operator() (Index b, const Range & p, Index r, const Range & c)
Index operator returning an object of type MatrixView.
(Reducing the dimension by two.)
Definition at line 845 of file matpackIV.cc.
References ConstTensor4View::mbr, ConstTensor4View::mcr, ConstTensor4View::mdata, Range::mextent, ConstTensor4View::mpr, ConstTensor4View::mrr, Range::mstart, and Range::mstride.
operator()() [22/32]
ConstMatrixView Tensor4View::operator() (Index b, const Range & p, Index r, const Range & c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by two.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 622 of file matpackIV.cc.
References ConstTensor4View::operator()().
operator()() [23/32]
VectorView Tensor4View::operator() (Index b, const Range & p, Index r, Index c)
Index operator returning an object of type VectorView.
(Reducing the dimension by three.)
Definition at line 928 of file matpackIV.cc.
References ConstTensor4View::mbr, ConstTensor4View::mcr, ConstTensor4View::mdata, Range::mextent, ConstTensor4View::mpr, ConstTensor4View::mrr, Range::mstart, and Range::mstride.
operator()() [24/32]
ConstVectorView Tensor4View::operator() (Index b, const Range & p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
(Reducing the dimension by three.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 670 of file matpackIV.cc.
References ConstTensor4View::operator()().
operator()() [25/32]
MatrixView Tensor4View::operator() (Index b, Index p, const Range & r, const Range & c)
Index operator returning an object of type MatrixView.
(Reducing the dimension by two.)
Definition at line 885 of file matpackIV.cc.
References ConstTensor4View::mbr, ConstTensor4View::mcr, ConstTensor4View::mdata, Range::mextent, ConstTensor4View::mpr, ConstTensor4View::mrr, Range::mstart, and Range::mstride.
operator()() [26/32]
ConstMatrixView Tensor4View::operator() (Index b, Index p, const Range & r, const Range & c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by two.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 646 of file matpackIV.cc.
References ConstTensor4View::operator()().
operator()() [27/32]
VectorView Tensor4View::operator() (Index b, Index p, const Range & r, Index c)
Index operator returning an object of type VectorView.
(Reducing the dimension by three.)
Definition at line 951 of file matpackIV.cc.
References ConstTensor4View::mbr, ConstTensor4View::mcr, ConstTensor4View::mdata, Range::mextent, ConstTensor4View::mpr, ConstTensor4View::mrr, Range::mstart, and Range::mstride.
operator()() [28/32]
ConstVectorView Tensor4View::operator() (Index b, Index p, const Range & r, Index c) const
Const index operator returning an object of type ConstVectorView.
(Reducing the dimension by three.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 682 of file matpackIV.cc.
References ConstTensor4View::operator()().
operator()() [29/32]
VectorView Tensor4View::operator() (Index b, Index p, Index r, const Range & c)
Index operator returning an object of type VectorView.
Reducing the dimension by three.)
Definition at line 974 of file matpackIV.cc.
References ConstTensor4View::mbr, ConstTensor4View::mcr, ConstTensor4View::mdata, Range::mextent, ConstTensor4View::mpr, ConstTensor4View::mrr, Range::mstart, and Range::mstride.
operator()() [30/32]
ConstVectorView Tensor4View::operator() (Index b, Index p, Index r, const Range & c) const
Const index operator returning an object of type ConstVectorView.
(Reducing the dimension by three.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 694 of file matpackIV.cc.
References ConstTensor4View::operator()().
operator()() [31/32]
Numeric& Tensor4View::operator() (Index b, Index p, Index r, Index c) inline
Plain non-const index operator.
Definition at line 297 of file matpackIV.h.
References get(), ConstTensor4View::mbr, ConstTensor4View::mcr, Range::mextent, ConstTensor4View::mpr, and ConstTensor4View::mrr.
operator()() [32/32]
Numeric Tensor4View::operator() (Index b, Index p, Index r, Index c) const inline
Plain const index operator.
Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 268 of file matpackIV.h.
References ConstTensor4View::operator()().
operator*=() [1/2]
Tensor4View & Tensor4View::operator*= (const ConstTensor4View & x)
Element-vise multiplication by another Tensor4.
Definition at line 1129 of file matpackIV.cc.
References ConstTensor4View::begin(), begin(), eb, end(), ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), and ConstTensor4View::nrows().
operator*=() [2/2]
Tensor4View & Tensor4View::operator*= (Numeric x)
Multiplication by scalar.
Definition at line 1085 of file matpackIV.cc.
References begin(), eb, and end().
operator+=() [1/2]
Tensor4View & Tensor4View::operator+= (const ConstTensor4View & x)
Element-vise addition of another Tensor4.
Definition at line 1163 of file matpackIV.cc.
References ConstTensor4View::begin(), begin(), eb, end(), ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), and ConstTensor4View::nrows().
operator+=() [2/2]
Tensor4View & Tensor4View::operator+= (Numeric x)
Addition of scalar.
Definition at line 1107 of file matpackIV.cc.
References begin(), eb, and end().
operator-=() [1/2]
Tensor4View & Tensor4View::operator-= (const ConstTensor4View & x)
Element-vise subtraction of another Tensor4.
Definition at line 1180 of file matpackIV.cc.
References ConstTensor4View::begin(), begin(), eb, end(), ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), and ConstTensor4View::nrows().
operator-=() [2/2]
Tensor4View & Tensor4View::operator-= (Numeric x)
Subtraction of scalar.
Definition at line 1118 of file matpackIV.cc.
References begin(), eb, and end().
operator/=() [1/2]
Tensor4View & Tensor4View::operator/= (const ConstTensor4View & x)
Element-vise division by another Tensor4.
Definition at line 1146 of file matpackIV.cc.
References ConstTensor4View::begin(), begin(), eb, end(), ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), and ConstTensor4View::nrows().
operator/=() [2/2]
Tensor4View & Tensor4View::operator/= (Numeric x)
Division by scalar.
Definition at line 1096 of file matpackIV.cc.
References begin(), eb, and end().
operator=() [1/4]
Tensor4View & Tensor4View::operator= (const ConstTensor4View & m)
Assignment operator.
This copies the data from another Tensor4View to this Tensor4View. Dimensions must agree! Resizing would destroy the selection that we might have done in this Tensor4View by setting its range.
Definition at line 1029 of file matpackIV.cc.
References ConstTensor4View::begin(), begin(), copy(), ConstTensor4View::end(), ConstTensor4View::mbr, ConstTensor4View::mcr, Range::mextent, ConstTensor4View::mpr, and ConstTensor4View::mrr.
operator=() [2/4]
Tensor4View & Tensor4View::operator= (const Tensor4 & m)
Assignment from a Tensor4.
This must exist to overide the automatically generated assignment operators, which don't copy the contents!
Definition at line 1061 of file matpackIV.cc.
References begin(), copy(), end(), ConstTensor4View::mbr, ConstTensor4View::mcr, Range::mextent, ConstTensor4View::mpr, and ConstTensor4View::mrr.
operator=() [3/4]
Tensor4View & Tensor4View::operator= (const Tensor4View & m)
Assignment from Tensor4View to Tensor4View.
This is a tricky one. The problem is that since Tensor4View is derived from ConstTensor4View, a default = operator is generated by the compiler, which does not do what we want. So we need this one to override the default.
Definition at line 1046 of file matpackIV.cc.
References begin(), copy(), end(), ConstTensor4View::mbr, ConstTensor4View::mcr, Range::mextent, ConstTensor4View::mpr, and ConstTensor4View::mrr.
operator=() [4/4]
Tensor4View & Tensor4View::operator= (Numeric x)
Assigning a scalar to a Tensor4View will set all elements to this value.
Definition at line 1075 of file matpackIV.cc.
References begin(), copy(), and end().
Friends And Related Function Documentation
Iterator5D
friend class Iterator5D friend
Definition at line 356 of file matpackIV.h.
Tensor5View
friend class Tensor5View friend
Definition at line 357 of file matpackIV.h.
Tensor6View
friend class Tensor6View friend
Definition at line 358 of file matpackIV.h.
Tensor7View
friend class Tensor7View friend
Definition at line 359 of file matpackIV.h.
The documentation for this class was generated from the following files:
matpackIV.h
matpackIV.cc