ARTS: Tensor6View Class Reference
Tensor6View Class Reference
The Tensor6View class.
#include <matpackVI.h>
Public Member Functions
ConstTensor6View operator() (const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor3View operator() (const Range &v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstTensor3View operator() (const Range &v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (Index v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (Index v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (Index v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstMatrixView operator() (Index v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstMatrixView operator() (Index v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstMatrixView operator() (Index v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (const Range &v, Index s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstMatrixView operator() (Index v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (const Range &v, Index s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (const Range &v, Index s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &v, Index s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &v, const Range &s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (Index v, Index s, Index b, Index p, Index r, const Range &c) const
ConstVectorView operator() (Index v, Index s, Index b, Index p, const Range &r, Index c) const
ConstVectorView operator() (Index v, Index s, Index b, const Range &p, Index r, Index c) const
ConstVectorView operator() (Index v, Index s, const Range &b, Index p, Index r, Index c) const
ConstVectorView operator() (Index v, const Range &s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (const Range &v, Index s, Index b, Index p, Index r, Index c) const
Numeric operator() (Index v, Index s, Index b, Index p, Index r, Index c) const
Numeric get (Index v, Index s, Index b, Index p, Index r, Index c) const
Get element implementation without assertions.
Tensor6View operator() (const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c)
Tensor5View operator() (const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c)
Tensor5View operator() (const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c)
Tensor5View operator() (const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor4View operator() (const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c)
Tensor4View operator() (const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c)
Tensor4View operator() (const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c)
Tensor4View operator() (const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c)
Tensor4View operator() (Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c)
Tensor4View operator() (const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c)
Tensor4View operator() (const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c)
Tensor4View operator() (const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c)
Tensor4View operator() (Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c)
Tensor4View operator() (const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c)
Tensor4View operator() (const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c)
Tensor4View operator() (Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c)
Tensor4View operator() (const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c)
Tensor4View operator() (Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c)
Tensor4View operator() (Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor3View operator() (const Range &v, const Range &s, const Range &b, Index p, Index r, Index c)
Tensor3View operator() (const Range &v, const Range &s, Index b, const Range &p, Index r, Index c)
Tensor3View operator() (const Range &v, Index s, const Range &b, const Range &p, Index r, Index c)
Tensor3View operator() (Index v, const Range &s, const Range &b, const Range &p, Index r, Index c)
Tensor3View operator() (const Range &v, const Range &s, Index b, Index p, const Range &r, Index c)
Tensor3View operator() (const Range &v, Index s, const Range &b, Index p, const Range &r, Index c)
Tensor3View operator() (Index v, const Range &s, const Range &b, Index p, const Range &r, Index c)
Tensor3View operator() (const Range &v, Index s, Index b, const Range &p, const Range &r, Index c)
Tensor3View operator() (Index v, const Range &s, Index b, const Range &p, const Range &r, Index c)
Tensor3View operator() (Index v, Index s, const Range &b, const Range &p, const Range &r, Index c)
Tensor3View operator() (const Range &v, const Range &s, Index b, Index p, Index r, const Range &c)
Tensor3View operator() (const Range &v, Index s, const Range &b, Index p, Index r, const Range &c)
Tensor3View operator() (Index v, const Range &s, const Range &b, Index p, Index r, const Range &c)
Tensor3View operator() (const Range &v, Index s, Index b, const Range &p, Index r, const Range &c)
Tensor3View operator() (Index v, const Range &s, Index b, const Range &p, Index r, const Range &c)
Tensor3View operator() (Index v, Index s, const Range &b, const Range &p, Index r, const Range &c)
Tensor3View operator() (const Range &v, Index s, Index b, Index p, const Range &r, const Range &c)
Tensor3View operator() (Index v, const Range &s, Index b, Index p, const Range &r, const Range &c)
Tensor3View operator() (Index v, Index s, const Range &b, Index p, const Range &r, const Range &c)
Tensor3View operator() (Index v, Index s, Index b, const Range &p, const Range &r, const Range &c)
MatrixView operator() (Index v, Index s, Index b, Index p, const Range &r, const Range &c)
MatrixView operator() (Index v, Index s, Index b, const Range &p, Index r, const Range &c)
MatrixView operator() (Index v, Index s, const Range &b, Index p, Index r, const Range &c)
MatrixView operator() (Index v, const Range &s, Index b, Index p, Index r, const Range &c)
MatrixView operator() (const Range &v, Index s, Index b, Index p, Index r, const Range &c)
MatrixView operator() (Index v, Index s, Index b, const Range &p, const Range &r, Index c)
MatrixView operator() (Index v, Index s, const Range &b, Index p, const Range &r, Index c)
MatrixView operator() (Index v, const Range &s, Index b, Index p, const Range &r, Index c)
MatrixView operator() (const Range &v, Index s, Index b, Index p, const Range &r, Index c)
MatrixView operator() (Index v, Index s, const Range &b, const Range &p, Index r, Index c)
MatrixView operator() (Index v, const Range &s, Index b, const Range &p, Index r, Index c)
MatrixView operator() (const Range &v, Index s, Index b, const Range &p, Index r, Index c)
MatrixView operator() (Index v, const Range &s, const Range &b, Index p, Index r, Index c)
MatrixView operator() (const Range &v, Index s, const Range &b, Index p, Index r, Index c)
MatrixView operator() (const Range &v, const Range &s, Index b, Index p, Index r, Index c)
VectorView operator() (Index v, Index s, Index b, Index p, Index r, const Range &c)
VectorView operator() (Index v, Index s, Index b, Index p, const Range &r, Index c)
VectorView operator() (Index v, Index s, Index b, const Range &p, Index r, Index c)
VectorView operator() (Index v, Index s, const Range &b, Index p, Index r, Index c)
VectorView operator() (Index v, const Range &s, Index b, Index p, Index r, Index c)
VectorView operator() (const Range &v, Index s, Index b, Index p, Index r, Index c)
Numeric & operator() (Index v, Index s, Index b, Index p, Index r, Index c)
Numeric & get (Index v, Index s, Index b, Index p, Index r, Index c)
Get element implementation without assertions.
const Numeric * get_c_array () const
Conversion to plain C-array.
Numeric * get_c_array ()
Conversion to plain C-array.
ConstIterator6D begin () const
Return const iterator to sub-tensor.
ConstIterator6D end () const
Return const iterator behind last sub-tensor.
Iterator6D begin ()
Return iterator to first sub-tensor.
Iterator6D end ()
Return iterator behind last sub-tensor.
Tensor6View & operator= (const ConstTensor6View &v)
Assignment operator.
Tensor6View & operator= (const Tensor6View &v)
Assignment from Tensor6View to Tensor6View.
Tensor6View & operator= (const Tensor6 &v)
Assignment from a Tensor6.
Tensor6View & operator= (Numeric x)
Assigning a scalar to a Tensor6View will set all elements to this value.
Tensor6View & operator*= (Numeric x)
Multiplication by scalar.
Tensor6View & operator/= (Numeric x)
Division by scalar.
Tensor6View & operator+= (Numeric x)
Addition of scalar.
Tensor6View & operator-= (Numeric x)
Subtraction of scalar.
Tensor6View & operator*= (const ConstTensor6View &x)
Element-vise multiplication by another Tensor6.
Tensor6View & operator/= (const ConstTensor6View &x)
Element-vise division by another Tensor6.
Tensor6View & operator+= (const ConstTensor6View &x)
Element-vise addition of another Tensor6.
Tensor6View & operator-= (const ConstTensor6View &x)
Element-vise subtraction of another Tensor6.
virtual ~Tensor6View ()
Tensor6View (const Tensor5View &a)
Special constructor to make a Tensor6 view of a Tensor5.
Public Member Functions inherited from ConstTensor6View
Index nvitrines () const
Returns the number of vitrines.
Index nshelves () const
Returns the number of shelves.
Index nbooks () const
Returns the number of books.
Index npages () const
Returns the number of pages.
Index nrows () const
Returns the number of rows.
Index ncols () const
Returns the number of columns.
ConstTensor6View operator() (const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor3View operator() (const Range &v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstTensor3View operator() (const Range &v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (Index v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (Index v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (Index v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstMatrixView operator() (Index v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstMatrixView operator() (Index v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstMatrixView operator() (Index v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (const Range &v, Index s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstMatrixView operator() (Index v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (const Range &v, Index s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (const Range &v, Index s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &v, Index s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &v, const Range &s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (Index v, Index s, Index b, Index p, Index r, const Range &c) const
ConstVectorView operator() (Index v, Index s, Index b, Index p, const Range &r, Index c) const
ConstVectorView operator() (Index v, Index s, Index b, const Range &p, Index r, Index c) const
ConstVectorView operator() (Index v, Index s, const Range &b, Index p, Index r, Index c) const
ConstVectorView operator() (Index v, const Range &s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (const Range &v, Index s, Index b, Index p, Index r, Index c) const
Numeric operator() (Index v, Index s, Index b, Index p, Index r, Index c) const
Numeric get (Index v, Index s, Index b, Index p, Index r, Index c) const
Get element implementation without assertions.
ConstIterator6D begin () const
Return const iterator to first sub-tensor.
ConstIterator6D end () const
Return const iterator behind last sub-tensor.
virtual ~ConstTensor6View ()
ConstTensor6View (const ConstTensor5View &a)
Special constructor to make a Tensor6 view of a Tensor5.
Protected Member Functions
Tensor6View ()
Default constructor.
Tensor6View (Numeric *data, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Explicit constructor.
Tensor6View (Numeric *data, const Range &pv, const Range &ps, const Range &pb, const Range &pp, const Range &pr, const Range &pc, const Range &nv, const Range &ns, const Range &nb, const Range &np, const Range &nr, const Range &nc)
Recursive constructor.
Protected Member Functions inherited from ConstTensor6View
ConstTensor6View ()
Default constructor.
ConstTensor6View (Numeric *data, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Explicit constructor.
ConstTensor6View (Numeric *data, const Range &pv, const Range &ps, const Range &pb, const Range &pp, const Range &pr, const Range &pc, const Range &nv, const Range &ns, const Range &nb, const Range &np, const Range &nr, const Range &nc)
Recursive constructor.
Friends
class Iterator7D
class Tensor7View
Additional Inherited Members
Protected Attributes inherited from ConstTensor6View
Range mvr
The vitrine range of mdata that is actually used.
Range msr
The shelf range of mdata that is actually used.
Range mbr
The book range of mdata that is actually used.
Range mpr
The page range of mdata that is actually used.
Range mrr
The row range of mdata that is actually used.
Range mcr
The column range of mdata that is actually used.
Numeric * mdata
Pointer to the plain C array that holds the data.
Detailed Description
The Tensor6View class.
This contains the main implementation of a Tensor6. It defines the concepts of Tensor6View. Plus additionally the recursive subrange operator, which makes it possible to create a Tensor6View from a subrange of a Tensor6View.
The class Tensor6 is just a special case of a Tensor6View which also allocates storage.
Definition at line 449 of file matpackVI.h.
Constructor & Destructor Documentation
~Tensor6View()
virtual Tensor6View::~Tensor6View () inline virtual
Definition at line 920 of file matpackVI.h.
Tensor6View() [1/4]
Tensor6View::Tensor6View (const Tensor5View & a)
Special constructor to make a Tensor6 view of a Tensor5.
Definition at line 2645 of file matpackVI.cc.
Tensor6View() [2/4]
Tensor6View::Tensor6View () protected
Default constructor.
This is necessary, so that we can have a default constructor for the derived class Tensor6.
Definition at line 2664 of file matpackVI.cc.
Tensor6View() [3/4]
Tensor6View::Tensor6View (Numeric * data, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c) protected
Explicit constructor.
This one is used by Tensor6 to initialize its own Tensor6View part. The row range rr must have a stride to account for the length of one row.
Definition at line 2673 of file matpackVI.cc.
Tensor6View() [4/4]
Tensor6View::Tensor6View (Numeric * data, const Range & pv, const Range & ps, const Range & pb, const Range & pp, const Range & pr, const Range & pc, const Range & nv, const Range & ns, const Range & nb, const Range & np, const Range & nr, const Range & nc) protected
Recursive constructor.
This is used to construct SubMatrices from SubMatrices. That means that the new ranges have to be interpreted relative to the original ranges.
The new ranges may contain -1 for the extent which acts as a joker. However, the used Range constructor converts this to an explicit range, consistent with the original Range.
Parameters
*data The actual data.
pv Previous range.
ps Previous range.
pb Previous range.
pp Previous range.
pr Previous range.
pc Previous range.
nv New Range.
ns New Range.
nb New Range.
np New Range.
nr New Range.
nc New Range.
Definition at line 2707 of file matpackVI.cc.
Member Function Documentation
begin() [1/2]
Iterator6D Tensor6View::begin ()
Return iterator to first sub-tensor.
Definition at line 2435 of file matpackVI.cc.
References ConstTensor6View::mbr, ConstTensor6View::mcr, ConstTensor6View::mdata, ConstTensor6View::mpr, ConstTensor6View::mrr, ConstTensor6View::msr, Range::mstart, Range::mstride, and ConstTensor6View::mvr.
begin() [2/2]
ConstIterator6D Tensor6View::begin () const
Return const iterator to sub-tensor.
Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 2423 of file matpackVI.cc.
References ConstTensor6View::begin().
Referenced by copy(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), Tensor6::operator=(), Tensor6::Tensor6(), and transform().
end() [1/2]
Iterator6D Tensor6View::end ()
Return iterator behind last sub-tensor.
Definition at line 2447 of file matpackVI.cc.
References ConstTensor6View::mbr, ConstTensor6View::mcr, ConstTensor6View::mdata, Range::mextent, ConstTensor6View::mpr, ConstTensor6View::mrr, ConstTensor6View::msr, Range::mstart, Range::mstride, and ConstTensor6View::mvr.
end() [2/2]
ConstIterator6D Tensor6View::end () const
Return const iterator behind last sub-tensor.
Definition at line 2429 of file matpackVI.cc.
References ConstTensor6View::end().
Referenced by copy(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), Tensor6::operator=(), and Tensor6::Tensor6().
get() [1/2]
Numeric& Tensor6View::get (Index v, Index s, Index b, Index p, Index r, Index c) inline
Get element implementation without assertions.
Definition at line 883 of file matpackVI.h.
References ConstTensor6View::mdata, and OFFSET.
get() [2/2]
Numeric Tensor6View::get (Index v, Index s, Index b, Index p, Index r, Index c) const inline
Get element implementation without assertions.
Definition at line 662 of file matpackVI.h.
References ConstTensor6View::get().
Referenced by interpweights(), and operator()().
get_c_array() [1/2]
Numeric * Tensor6View::get_c_array ()
Conversion to plain C-array.
This function returns a pointer to the raw data. It fails if the Tensor5View is not pointing to the beginning of a Tensor5 or the stride is not 1 because the caller expects to get a C array with continuous data.
Definition at line 2387 of file matpackVI.cc.
References ConstTensor6View::mbr, ConstTensor6View::mcr, ConstTensor6View::mdata, Range::mextent, ConstTensor6View::mpr, ConstTensor6View::mrr, ConstTensor6View::msr, Range::mstart, Range::mstride, and ConstTensor6View::mvr.
get_c_array() [2/2]
const Numeric * Tensor6View::get_c_array () const
Conversion to plain C-array.
This function returns a pointer to the raw data. It fails if the Tensor5View is not pointing to the beginning of a Tensor5 or the stride is not 1 because the caller expects to get a C array with continuous data.
Definition at line 2407 of file matpackVI.cc.
References ConstTensor6View::mbr, ConstTensor6View::mcr, ConstTensor6View::mdata, Range::mextent, ConstTensor6View::mpr, ConstTensor6View::mrr, ConstTensor6View::msr, Range::mstart, Range::mstride, and ConstTensor6View::mvr.
Referenced by Reduce().
operator()() [1/128]
Tensor6View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 1555 of file matpackVI.cc.
operator()() [2/128]
ConstTensor6View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 1036 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [3/128]
Tensor5View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 1567 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [4/128]
ConstTensor5View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 1046 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [5/128]
Tensor5View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 1578 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [6/128]
ConstTensor5View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 1054 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [7/128]
Tensor4View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, const Range & p, Index r, Index c)
Definition at line 1635 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [8/128]
ConstTensor4View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 1096 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [9/128]
Tensor5View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 1589 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [10/128]
ConstTensor5View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 1062 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [11/128]
Tensor4View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, Index p, const Range & r, Index c)
Definition at line 1647 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [12/128]
ConstTensor4View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 1104 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [13/128]
Tensor4View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, Index p, Index r, const Range & c)
Definition at line 1695 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [14/128]
ConstTensor4View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 1136 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [15/128]
Tensor3View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, Index p, Index r, Index c)
Definition at line 1817 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [16/128]
ConstTensor3View Tensor6View::operator() (const Range & v, const Range & s, const Range & b, Index p, Index r, Index c) const
Definition at line 1218 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [17/128]
Tensor5View Tensor6View::operator() (const Range & v, const Range & s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 1600 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [18/128]
ConstTensor5View Tensor6View::operator() (const Range & v, const Range & s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 1070 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [19/128]
Tensor4View Tensor6View::operator() (const Range & v, const Range & s, Index b, const Range & p, const Range & r, Index c)
Definition at line 1659 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [20/128]
ConstTensor4View Tensor6View::operator() (const Range & v, const Range & s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 1112 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [21/128]
Tensor4View Tensor6View::operator() (const Range & v, const Range & s, Index b, const Range & p, Index r, const Range & c)
Definition at line 1707 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [22/128]
ConstTensor4View Tensor6View::operator() (const Range & v, const Range & s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 1144 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [23/128]
Tensor3View Tensor6View::operator() (const Range & v, const Range & s, Index b, const Range & p, Index r, Index c)
Definition at line 1830 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [24/128]
ConstTensor3View Tensor6View::operator() (const Range & v, const Range & s, Index b, const Range & p, Index r, Index c) const
Definition at line 1226 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [25/128]
Tensor4View Tensor6View::operator() (const Range & v, const Range & s, Index b, Index p, const Range & r, const Range & c)
Definition at line 1743 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [26/128]
ConstTensor4View Tensor6View::operator() (const Range & v, const Range & s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 1168 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [27/128]
Tensor3View Tensor6View::operator() (const Range & v, const Range & s, Index b, Index p, const Range & r, Index c)
Definition at line 1869 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [28/128]
ConstTensor3View Tensor6View::operator() (const Range & v, const Range & s, Index b, Index p, const Range & r, Index c) const
Definition at line 1250 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [29/128]
Tensor3View Tensor6View::operator() (const Range & v, const Range & s, Index b, Index p, Index r, const Range & c)
Definition at line 1947 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [30/128]
ConstTensor3View Tensor6View::operator() (const Range & v, const Range & s, Index b, Index p, Index r, const Range & c) const
Definition at line 1298 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [31/128]
MatrixView Tensor6View::operator() (const Range & v, const Range & s, Index b, Index p, Index r, Index c)
Definition at line 2275 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [32/128]
ConstMatrixView Tensor6View::operator() (const Range & v, const Range & s, Index b, Index p, Index r, Index c) const
Definition at line 1492 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [33/128]
Tensor5View Tensor6View::operator() (const Range & v, Index s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 1611 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [34/128]
ConstTensor5View Tensor6View::operator() (const Range & v, Index s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 1078 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [35/128]
Tensor4View Tensor6View::operator() (const Range & v, Index s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 1671 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [36/128]
ConstTensor4View Tensor6View::operator() (const Range & v, Index s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 1120 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [37/128]
Tensor4View Tensor6View::operator() (const Range & v, Index s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 1719 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [38/128]
ConstTensor4View Tensor6View::operator() (const Range & v, Index s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 1152 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [39/128]
Tensor3View Tensor6View::operator() (const Range & v, Index s, const Range & b, const Range & p, Index r, Index c)
Definition at line 1843 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [40/128]
ConstTensor3View Tensor6View::operator() (const Range & v, Index s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 1234 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [41/128]
Tensor4View Tensor6View::operator() (const Range & v, Index s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 1755 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [42/128]
ConstTensor4View Tensor6View::operator() (const Range & v, Index s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 1176 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [43/128]
Tensor3View Tensor6View::operator() (const Range & v, Index s, const Range & b, Index p, const Range & r, Index c)
Definition at line 1882 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [44/128]
ConstTensor3View Tensor6View::operator() (const Range & v, Index s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 1258 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [45/128]
Tensor3View Tensor6View::operator() (const Range & v, Index s, const Range & b, Index p, Index r, const Range & c)
Definition at line 1960 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [46/128]
ConstTensor3View Tensor6View::operator() (const Range & v, Index s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 1306 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [47/128]
MatrixView Tensor6View::operator() (const Range & v, Index s, const Range & b, Index p, Index r, Index c)
Definition at line 2261 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [48/128]
ConstMatrixView Tensor6View::operator() (const Range & v, Index s, const Range & b, Index p, Index r, Index c) const
Definition at line 1484 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [49/128]
Tensor4View Tensor6View::operator() (const Range & v, Index s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 1779 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [50/128]
ConstTensor4View Tensor6View::operator() (const Range & v, Index s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 1192 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [51/128]
Tensor3View Tensor6View::operator() (const Range & v, Index s, Index b, const Range & p, const Range & r, Index c)
Definition at line 1908 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [52/128]
ConstTensor3View Tensor6View::operator() (const Range & v, Index s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 1274 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [53/128]
Tensor3View Tensor6View::operator() (const Range & v, Index s, Index b, const Range & p, Index r, const Range & c)
Definition at line 1986 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [54/128]
ConstTensor3View Tensor6View::operator() (const Range & v, Index s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 1322 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [55/128]
MatrixView Tensor6View::operator() (const Range & v, Index s, Index b, const Range & p, Index r, Index c)
Definition at line 2233 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [56/128]
ConstMatrixView Tensor6View::operator() (const Range & v, Index s, Index b, const Range & p, Index r, Index c) const
Definition at line 1468 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [57/128]
Tensor3View Tensor6View::operator() (const Range & v, Index s, Index b, Index p, const Range & r, const Range & c)
Definition at line 2025 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [58/128]
ConstTensor3View Tensor6View::operator() (const Range & v, Index s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 1346 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [59/128]
MatrixView Tensor6View::operator() (const Range & v, Index s, Index b, Index p, const Range & r, Index c)
Definition at line 2191 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [60/128]
ConstMatrixView Tensor6View::operator() (const Range & v, Index s, Index b, Index p, const Range & r, Index c) const
Definition at line 1444 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [61/128]
MatrixView Tensor6View::operator() (const Range & v, Index s, Index b, Index p, Index r, const Range & c)
Definition at line 2135 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [62/128]
ConstMatrixView Tensor6View::operator() (const Range & v, Index s, Index b, Index p, Index r, const Range & c) const
Definition at line 1412 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [63/128]
VectorView Tensor6View::operator() (const Range & v, Index s, Index b, Index p, Index r, Index c)
Definition at line 2366 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [64/128]
ConstVectorView Tensor6View::operator() (const Range & v, Index s, Index b, Index p, Index r, Index c) const
Definition at line 1542 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [65/128]
Tensor5View Tensor6View::operator() (Index v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 1622 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [66/128]
ConstTensor5View Tensor6View::operator() (Index v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 1086 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [67/128]
Tensor4View Tensor6View::operator() (Index v, const Range & s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 1683 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [68/128]
ConstTensor4View Tensor6View::operator() (Index v, const Range & s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 1128 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [69/128]
Tensor4View Tensor6View::operator() (Index v, const Range & s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 1731 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [70/128]
ConstTensor4View Tensor6View::operator() (Index v, const Range & s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 1160 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [71/128]
Tensor3View Tensor6View::operator() (Index v, const Range & s, const Range & b, const Range & p, Index r, Index c)
Definition at line 1856 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [72/128]
ConstTensor3View Tensor6View::operator() (Index v, const Range & s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 1242 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [73/128]
Tensor4View Tensor6View::operator() (Index v, const Range & s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 1767 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [74/128]
ConstTensor4View Tensor6View::operator() (Index v, const Range & s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 1184 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [75/128]
Tensor3View Tensor6View::operator() (Index v, const Range & s, const Range & b, Index p, const Range & r, Index c)
Definition at line 1895 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [76/128]
ConstTensor3View Tensor6View::operator() (Index v, const Range & s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 1266 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [77/128]
Tensor3View Tensor6View::operator() (Index v, const Range & s, const Range & b, Index p, Index r, const Range & c)
Definition at line 1973 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [78/128]
ConstTensor3View Tensor6View::operator() (Index v, const Range & s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 1314 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [79/128]
MatrixView Tensor6View::operator() (Index v, const Range & s, const Range & b, Index p, Index r, Index c)
Definition at line 2247 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [80/128]
ConstMatrixView Tensor6View::operator() (Index v, const Range & s, const Range & b, Index p, Index r, Index c) const
Definition at line 1476 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [81/128]
Tensor4View Tensor6View::operator() (Index v, const Range & s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 1791 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [82/128]
ConstTensor4View Tensor6View::operator() (Index v, const Range & s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 1200 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [83/128]
Tensor3View Tensor6View::operator() (Index v, const Range & s, Index b, const Range & p, const Range & r, Index c)
Definition at line 1921 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [84/128]
ConstTensor3View Tensor6View::operator() (Index v, const Range & s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 1282 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [85/128]
Tensor3View Tensor6View::operator() (Index v, const Range & s, Index b, const Range & p, Index r, const Range & c)
Definition at line 1999 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [86/128]
ConstTensor3View Tensor6View::operator() (Index v, const Range & s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 1330 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [87/128]
MatrixView Tensor6View::operator() (Index v, const Range & s, Index b, const Range & p, Index r, Index c)
Definition at line 2219 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [88/128]
ConstMatrixView Tensor6View::operator() (Index v, const Range & s, Index b, const Range & p, Index r, Index c) const
Definition at line 1460 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [89/128]
Tensor3View Tensor6View::operator() (Index v, const Range & s, Index b, Index p, const Range & r, const Range & c)
Definition at line 2038 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [90/128]
ConstTensor3View Tensor6View::operator() (Index v, const Range & s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 1354 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [91/128]
MatrixView Tensor6View::operator() (Index v, const Range & s, Index b, Index p, const Range & r, Index c)
Definition at line 2177 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [92/128]
ConstMatrixView Tensor6View::operator() (Index v, const Range & s, Index b, Index p, const Range & r, Index c) const
Definition at line 1436 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [93/128]
MatrixView Tensor6View::operator() (Index v, const Range & s, Index b, Index p, Index r, const Range & c)
Definition at line 2121 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [94/128]
ConstMatrixView Tensor6View::operator() (Index v, const Range & s, Index b, Index p, Index r, const Range & c) const
Definition at line 1404 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [95/128]
VectorView Tensor6View::operator() (Index v, const Range & s, Index b, Index p, Index r, Index c)
Definition at line 2351 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [96/128]
ConstVectorView Tensor6View::operator() (Index v, const Range & s, Index b, Index p, Index r, Index c) const
Definition at line 1534 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [97/128]
Tensor4View Tensor6View::operator() (Index v, Index s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 1803 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [98/128]
ConstTensor4View Tensor6View::operator() (Index v, Index s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 1208 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [99/128]
Tensor3View Tensor6View::operator() (Index v, Index s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 1934 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [100/128]
ConstTensor3View Tensor6View::operator() (Index v, Index s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 1290 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [101/128]
Tensor3View Tensor6View::operator() (Index v, Index s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 2012 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [102/128]
ConstTensor3View Tensor6View::operator() (Index v, Index s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 1338 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [103/128]
MatrixView Tensor6View::operator() (Index v, Index s, const Range & b, const Range & p, Index r, Index c)
Definition at line 2205 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [104/128]
ConstMatrixView Tensor6View::operator() (Index v, Index s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 1452 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [105/128]
Tensor3View Tensor6View::operator() (Index v, Index s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 2051 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [106/128]
ConstTensor3View Tensor6View::operator() (Index v, Index s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 1362 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [107/128]
MatrixView Tensor6View::operator() (Index v, Index s, const Range & b, Index p, const Range & r, Index c)
Definition at line 2163 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [108/128]
ConstMatrixView Tensor6View::operator() (Index v, Index s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 1428 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [109/128]
MatrixView Tensor6View::operator() (Index v, Index s, const Range & b, Index p, Index r, const Range & c)
Definition at line 2107 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [110/128]
ConstMatrixView Tensor6View::operator() (Index v, Index s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 1396 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [111/128]
VectorView Tensor6View::operator() (Index v, Index s, const Range & b, Index p, Index r, Index c)
Definition at line 2336 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [112/128]
ConstVectorView Tensor6View::operator() (Index v, Index s, const Range & b, Index p, Index r, Index c) const
Definition at line 1526 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [113/128]
Tensor3View Tensor6View::operator() (Index v, Index s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 2064 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [114/128]
ConstTensor3View Tensor6View::operator() (Index v, Index s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 1370 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [115/128]
MatrixView Tensor6View::operator() (Index v, Index s, Index b, const Range & p, const Range & r, Index c)
Definition at line 2149 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [116/128]
ConstMatrixView Tensor6View::operator() (Index v, Index s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 1420 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [117/128]
MatrixView Tensor6View::operator() (Index v, Index s, Index b, const Range & p, Index r, const Range & c)
Definition at line 2093 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [118/128]
ConstMatrixView Tensor6View::operator() (Index v, Index s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 1388 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [119/128]
VectorView Tensor6View::operator() (Index v, Index s, Index b, const Range & p, Index r, Index c)
Definition at line 2321 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [120/128]
ConstVectorView Tensor6View::operator() (Index v, Index s, Index b, const Range & p, Index r, Index c) const
Definition at line 1518 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [121/128]
MatrixView Tensor6View::operator() (Index v, Index s, Index b, Index p, const Range & r, const Range & c)
Definition at line 2079 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [122/128]
ConstMatrixView Tensor6View::operator() (Index v, Index s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 1380 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [123/128]
VectorView Tensor6View::operator() (Index v, Index s, Index b, Index p, const Range & r, Index c)
Definition at line 2306 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [124/128]
ConstVectorView Tensor6View::operator() (Index v, Index s, Index b, Index p, const Range & r, Index c) const
Definition at line 1510 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [125/128]
VectorView Tensor6View::operator() (Index v, Index s, Index b, Index p, Index r, const Range & c)
Definition at line 2291 of file matpackVI.cc.
References CHECK, and OFFSET.
operator()() [126/128]
ConstVectorView Tensor6View::operator() (Index v, Index s, Index b, Index p, Index r, const Range & c) const
Definition at line 1502 of file matpackVI.cc.
References ConstTensor6View::operator()().
operator()() [127/128]
Numeric& Tensor6View::operator() (Index v, Index s, Index b, Index p, Index r, Index c) inline
Definition at line 871 of file matpackVI.h.
References CHECK, and get().
operator()() [128/128]
Numeric Tensor6View::operator() (Index v, Index s, Index b, Index p, Index r, Index c) const inline
Definition at line 657 of file matpackVI.h.
References ConstTensor6View::operator()().
operator*=() [1/2]
Tensor6View & Tensor6View::operator*= (const ConstTensor6View & x)
Element-vise multiplication by another Tensor6.
Definition at line 2569 of file matpackVI.cc.
References ConstTensor6View::begin(), begin(), end(), ConstTensor6View::nbooks(), ConstTensor6View::ncols(), ConstTensor6View::npages(), ConstTensor6View::nrows(), ConstTensor6View::nshelves(), and ConstTensor6View::nvitrines().
operator*=() [2/2]
Tensor6View & Tensor6View::operator*= (Numeric x)
Multiplication by scalar.
Definition at line 2525 of file matpackVI.cc.
References begin(), and end().
operator+=() [1/2]
Tensor6View & Tensor6View::operator+= (const ConstTensor6View & x)
Element-vise addition of another Tensor6.
Definition at line 2607 of file matpackVI.cc.
References ConstTensor6View::begin(), begin(), end(), ConstTensor6View::nbooks(), ConstTensor6View::ncols(), ConstTensor6View::npages(), ConstTensor6View::nrows(), ConstTensor6View::nshelves(), and ConstTensor6View::nvitrines().
operator+=() [2/2]
Tensor6View & Tensor6View::operator+= (Numeric x)
Addition of scalar.
Definition at line 2547 of file matpackVI.cc.
References begin(), and end().
operator-=() [1/2]
Tensor6View & Tensor6View::operator-= (const ConstTensor6View & x)
Element-vise subtraction of another Tensor6.
Definition at line 2626 of file matpackVI.cc.
References ConstTensor6View::begin(), begin(), end(), ConstTensor6View::nbooks(), ConstTensor6View::ncols(), ConstTensor6View::npages(), ConstTensor6View::nrows(), ConstTensor6View::nshelves(), and ConstTensor6View::nvitrines().
operator-=() [2/2]
Tensor6View & Tensor6View::operator-= (Numeric x)
Subtraction of scalar.
Definition at line 2558 of file matpackVI.cc.
References begin(), and end().
operator/=() [1/2]
Tensor6View & Tensor6View::operator/= (const ConstTensor6View & x)
Element-vise division by another Tensor6.
Definition at line 2588 of file matpackVI.cc.
References ConstTensor6View::begin(), begin(), end(), ConstTensor6View::nbooks(), ConstTensor6View::ncols(), ConstTensor6View::npages(), ConstTensor6View::nrows(), ConstTensor6View::nshelves(), and ConstTensor6View::nvitrines().
operator/=() [2/2]
Tensor6View & Tensor6View::operator/= (Numeric x)
Division by scalar.
Definition at line 2536 of file matpackVI.cc.
References begin(), and end().
operator=() [1/4]
Tensor6View & Tensor6View::operator= (const ConstTensor6View & m)
Assignment operator.
This copies the data from another Tensor6View to this Tensor6View. Dimensions must agree! Resizing would destroy the selection that we might have done in this Tensor6View by setting its range.
Definition at line 2463 of file matpackVI.cc.
References ConstTensor6View::begin(), begin(), copy(), ConstTensor6View::end(), ConstTensor6View::mbr, ConstTensor6View::mcr, Range::mextent, ConstTensor6View::mpr, ConstTensor6View::mrr, ConstTensor6View::msr, and ConstTensor6View::mvr.
operator=() [2/4]
Tensor6View & Tensor6View::operator= (const Tensor6 & m)
Assignment from a Tensor6.
This must exist to overide the automatically generated assignment operators, which don't copy the contents!
Definition at line 2499 of file matpackVI.cc.
References begin(), copy(), end(), ConstTensor6View::mbr, ConstTensor6View::mcr, Range::mextent, ConstTensor6View::mpr, ConstTensor6View::mrr, ConstTensor6View::msr, and ConstTensor6View::mvr.
operator=() [3/4]
Tensor6View & Tensor6View::operator= (const Tensor6View & m)
Assignment from Tensor6View to Tensor6View.
This is a tricky one. The problem is that since Tensor6View is derived from ConstTensor6View, a default = operator is generated by the compiler, which does not do what we want. So we need this one to override the default.
Definition at line 2482 of file matpackVI.cc.
References begin(), copy(), end(), ConstTensor6View::mbr, ConstTensor6View::mcr, Range::mextent, ConstTensor6View::mpr, ConstTensor6View::mrr, ConstTensor6View::msr, and ConstTensor6View::mvr.
operator=() [4/4]
Tensor6View & Tensor6View::operator= (Numeric x)
Assigning a scalar to a Tensor6View will set all elements to this value.
Definition at line 2515 of file matpackVI.cc.
References begin(), copy(), and end().
Friends And Related Function Documentation
Iterator7D
friend class Iterator7D friend
Definition at line 923 of file matpackVI.h.
Tensor7View
friend class Tensor7View friend
Definition at line 924 of file matpackVI.h.
The documentation for this class was generated from the following files:
matpackVI.h
matpackVI.cc