ARTS: LineshapeSpec Class Reference
LineshapeSpec Class Reference
Lineshape related specification like which lineshape to use, the normalizationfactor, and the cutoff.
#include <absorption.h>
Public Member Functions
LineshapeSpec ()
Default constructor.
LineshapeSpec (const Index &ind_ls, const Index &ind_lsn, const Numeric &cutoff)
Initializing constructor.
const Index & Ind_ls () const
Return the index of this lineshape.
void SetInd_ls (Index ind_ls)
Set it.
const Index & Ind_lsn () const
Return the index of the normalization factor.
void SetInd_lsn (Index ind_lsn)
Set it.
const Numeric & Cutoff () const
Return the cutoff frequency (in Hz).
void SetCutoff (Numeric cutoff)
Set it.
Private Attributes
Index mind_ls
Index mind_lsn
Numeric mcutoff
Detailed Description
Lineshape related specification like which lineshape to use, the normalizationfactor, and the cutoff.
\author Axel von Engeln
\date   2001-01-05
Definition at line 141 of file absorption.h.
Constructor & Destructor Documentation
LineshapeSpec() [1/2]
LineshapeSpec::LineshapeSpec () inline
Default constructor.
Definition at line 145 of file absorption.h.
LineshapeSpec() [2/2]
LineshapeSpec::LineshapeSpec (const Index & ind_ls, const Index & ind_lsn, const Numeric & cutoff) inline
Initializing constructor.
Definition at line 151 of file absorption.h.
Member Function Documentation
Cutoff()
const Numeric& LineshapeSpec::Cutoff () const inline
Return the cutoff frequency (in Hz).
This is the distance from the line center outside of which the lineshape is defined to be zero. Negative means no cutoff.
Definition at line 172 of file absorption.h.
References mcutoff.
Referenced by abs_xsec_per_speciesAddLines(), and operator<<().
Ind_ls()
const Index& LineshapeSpec::Ind_ls () const inline
Return the index of this lineshape.
Definition at line 160 of file absorption.h.
References mind_ls.
Referenced by abs_xsec_per_speciesAddLines(), and operator<<().
Ind_lsn()
const Index& LineshapeSpec::Ind_lsn () const inline
Return the index of the normalization factor.
Definition at line 165 of file absorption.h.
References mind_lsn.
Referenced by abs_xsec_per_speciesAddLines(), and operator<<().
SetCutoff()
void LineshapeSpec::SetCutoff (Numeric cutoff) inline
Set it.
Definition at line 174 of file absorption.h.
References mcutoff.
SetInd_ls()
void LineshapeSpec::SetInd_ls (Index ind_ls) inline
Set it.
Definition at line 162 of file absorption.h.
References mind_ls.
SetInd_lsn()
void LineshapeSpec::SetInd_lsn (Index ind_lsn) inline
Set it.
Definition at line 167 of file absorption.h.
References mind_lsn.
Member Data Documentation
mcutoff
Numeric LineshapeSpec::mcutoff private
Definition at line 178 of file absorption.h.
Referenced by Cutoff(), and SetCutoff().
mind_ls
Index LineshapeSpec::mind_ls private
Definition at line 176 of file absorption.h.
Referenced by Ind_ls(), and SetInd_ls().
mind_lsn
Index LineshapeSpec::mind_lsn private
Definition at line 177 of file absorption.h.
Referenced by Ind_lsn(), and SetInd_lsn().
The documentation for this class was generated from the following file:
absorption.h