ARTS: LineMixingRecord Class Reference
LineMixingRecord Class Reference
#include <linemixingrecord.h>
Public Member Functions
LineMixingRecord ()
LineMixingRecord (Index species, Index iso)
Index Species () const
Index Isotopologue () const
QuantumNumberRecord & Quantum ()
const QuantumNumberRecord & Quantum () const
Vector & Data ()
const Vector & Data () const
Private Attributes
Index mspecies
Species index.
Index misotopologue
Isotopologue index.
QuantumNumberRecord mquantum
Quantum Numbers.
Vector mdata
Line mixing data.
Detailed Description
Definition at line 33 of file linemixingrecord.h.
Constructor & Destructor Documentation
LineMixingRecord() [1/2]
LineMixingRecord::LineMixingRecord () inline
Definition at line 36 of file linemixingrecord.h.
LineMixingRecord() [2/2]
LineMixingRecord::LineMixingRecord (Index species, Index iso) inline
Definition at line 37 of file linemixingrecord.h.
Member Function Documentation
Data() [1/2]
Vector& LineMixingRecord::Data () inline
Definition at line 45 of file linemixingrecord.h.
References mdata.
Referenced by ArrayOfLineMixingRecordReadAscii(), operator<<(), xml_read_from_stream(), and xml_write_to_stream().
Data() [2/2]
const Vector& LineMixingRecord::Data () const inline
Definition at line 46 of file linemixingrecord.h.
References mdata.
Isotopologue()
Index LineMixingRecord::Isotopologue () const inline
Definition at line 40 of file linemixingrecord.h.
References misotopologue.
Referenced by line_mixing_dataMatch(), operator<<(), and xml_write_to_stream().
Quantum() [1/2]
QuantumNumberRecord& LineMixingRecord::Quantum () inline
Definition at line 42 of file linemixingrecord.h.
References mquantum.
Referenced by ArrayOfLineMixingRecordReadAscii(), line_mixing_dataMatch(), operator<<(), xml_read_from_stream(), and xml_write_to_stream().
Quantum() [2/2]
const QuantumNumberRecord& LineMixingRecord::Quantum () const inline
Definition at line 43 of file linemixingrecord.h.
References mquantum.
Species()
Index LineMixingRecord::Species () const inline
Definition at line 39 of file linemixingrecord.h.
References mspecies.
Referenced by line_mixing_dataMatch(), operator<<(), and xml_write_to_stream().
Member Data Documentation
mdata
Vector LineMixingRecord::mdata private
Line mixing data.
Definition at line 56 of file linemixingrecord.h.
Referenced by Data().
misotopologue
Index LineMixingRecord::misotopologue private
Isotopologue index.
Definition at line 52 of file linemixingrecord.h.
Referenced by Isotopologue().
mquantum
QuantumNumberRecord LineMixingRecord::mquantum private
Quantum Numbers.
Definition at line 54 of file linemixingrecord.h.
Referenced by Quantum().
mspecies
Index LineMixingRecord::mspecies private
Species index.
Definition at line 50 of file linemixingrecord.h.
Referenced by Species().
The documentation for this class was generated from the following file:
linemixingrecord.h