ARTS: QuantumNumbers Class Reference
QuantumNumbers Class Reference
Container class for Quantum Numbers.
#include <quantum.h>
Public Types
typedef std::map< Index, Rational > QuantumContainer
Public Member Functions
const Rational operator[] (const Index qn) const
Return copy of quantum number.
void Set (Index qn, Rational r)
Set quantum number.
const QuantumContainer & GetNumbers () const
bool Compare (const QuantumNumbers &qn) const
Compare Quantum Numbers.
Private Attributes
QuantumContainer mqnumbers
Detailed Description
Container class for Quantum Numbers.
Definition at line 57 of file quantum.h.
Member Typedef Documentation
QuantumContainer
typedef std::map<Index, Rational> QuantumNumbers::QuantumContainer
Definition at line 60 of file quantum.h.
Member Function Documentation
Compare()
bool QuantumNumbers::Compare (const QuantumNumbers & qn) const
Compare Quantum Numbers.
Ignores any undefined numbers in the comparison
Parameters
[in] qn Quantum Numbers to compare to
Returns
True for match
Definition at line 31 of file quantum.cc.
References GetNumbers(), and mqnumbers.
Referenced by main().
GetNumbers()
const QuantumContainer& QuantumNumbers::GetNumbers () const inline
Definition at line 75 of file quantum.h.
References mqnumbers.
Referenced by Compare(), and xml_write_to_stream().
operator[]()
const Rational QuantumNumbers::operator[] (const Index qn) const inline
Return copy of quantum number.
Definition at line 63 of file quantum.h.
References mqnumbers, and RATIONAL_UNDEFINED.
Set()
void QuantumNumbers::Set (Index qn, Rational r) inline
Set quantum number.
Definition at line 73 of file quantum.h.
References mqnumbers, and QN_FINAL_ENTRY.
Referenced by main(), QuantumNumberRecord::SetLower(), and QuantumNumberRecord::SetUpper().
Member Data Documentation
mqnumbers
QuantumContainer QuantumNumbers::mqnumbers private
Definition at line 88 of file quantum.h.
Referenced by Compare(), GetNumbers(), operator[](), and Set().
The documentation for this class was generated from the following files:
quantum.h
quantum.cc