ARTS: QuantumNumberRecord Class Reference
QuantumNumberRecord Class Reference
Record containing upper and lower quantum numbers.
#include <quantum.h>
Public Member Functions
void SetLower (const Index i, const Rational r)
Set lower quantum number.
void SetUpper (const Index i, const Rational r)
Set upper quantum number.
Rational Lower (Index i) const
Get lower quantum number.
Rational Upper (Index i) const
Get upper quantum number.
QuantumNumbers & Lower ()
Get lower quantum numbers.
const QuantumNumbers & Lower () const
Get lower quantum numbers.
QuantumNumbers & Upper ()
Get upper quantum numbers.
const QuantumNumbers & Upper () const
Get upper quantum numbers.
Private Attributes
QuantumNumbers mqn_upper
Upper state quantum numbers.
QuantumNumbers mqn_lower
Lower state quantum numbers.
Detailed Description
Record containing upper and lower quantum numbers.
Definition at line 93 of file quantum.h.
Member Function Documentation
Lower() [1/3]
QuantumNumbers& QuantumNumberRecord::Lower () inline
Get lower quantum numbers.
Definition at line 109 of file quantum.h.
References mqn_lower.
Lower() [2/3]
const QuantumNumbers& QuantumNumberRecord::Lower () const inline
Get lower quantum numbers.
Definition at line 112 of file quantum.h.
References mqn_lower.
Lower() [3/3]
Rational QuantumNumberRecord::Lower (Index i) const inline
Get lower quantum number.
Definition at line 103 of file quantum.h.
References mqn_lower.
Referenced by find_matching_lines(), operator<<(), propmat_clearskyAddZeeman(), LineRecord::ReadFromHitran2004Stream(), xml_read_from_stream(), and xml_write_to_stream().
SetLower()
void QuantumNumberRecord::SetLower (const Index i, const Rational r) inline
Set lower quantum number.
Definition at line 97 of file quantum.h.
References mqn_lower, and QuantumNumbers::Set().
Referenced by ArrayOfLineMixingRecordReadAscii(), main(), LineRecord::ReadFromArtscat4Stream(), and LineRecord::ReadFromHitran2004Stream().
SetUpper()
void QuantumNumberRecord::SetUpper (const Index i, const Rational r) inline
Set upper quantum number.
Definition at line 100 of file quantum.h.
References mqn_upper, and QuantumNumbers::Set().
Referenced by ArrayOfLineMixingRecordReadAscii(), main(), LineRecord::ReadFromArtscat4Stream(), and LineRecord::ReadFromHitran2004Stream().
Upper() [1/3]
QuantumNumbers& QuantumNumberRecord::Upper () inline
Get upper quantum numbers.
Definition at line 115 of file quantum.h.
References mqn_upper.
Upper() [2/3]
const QuantumNumbers& QuantumNumberRecord::Upper () const inline
Get upper quantum numbers.
Definition at line 118 of file quantum.h.
References mqn_upper.
Upper() [3/3]
Rational QuantumNumberRecord::Upper (Index i) const inline
Get upper quantum number.
Definition at line 106 of file quantum.h.
References mqn_upper.
Referenced by find_matching_lines(), operator<<(), propmat_clearskyAddZeeman(), LineRecord::ReadFromHitran2004Stream(), xml_read_from_stream(), and xml_write_to_stream().
Member Data Documentation
mqn_lower
QuantumNumbers QuantumNumberRecord::mqn_lower private
Lower state quantum numbers.
Definition at line 124 of file quantum.h.
Referenced by Lower(), and SetLower().
mqn_upper
QuantumNumbers QuantumNumberRecord::mqn_upper private
Upper state quantum numbers.
Definition at line 122 of file quantum.h.
Referenced by SetUpper(), and Upper().
The documentation for this class was generated from the following file:
quantum.h