ARTS: RetrievalQuantity Class Reference
RetrievalQuantity Class Reference
Contains the data for one retrieval quantity.
#include <jacobian.h>
Public Member Functions
RetrievalQuantity ()
Default constructor.
RetrievalQuantity (const String &maintag, const String &subtag, const String &mode, const Index &analytical, const Numeric &perturbation, const ArrayOfVector &grids)
Constructor that sets the values.
const String & MainTag () const
Main tag.
void MainTag (const String &mt)
const String & Subtag () const
Subtag.
void Subtag (const String &st)
const String & Mode () const
Calculation mode.
void Mode (const String &m)
const Index & Analytical () const
Boolean to make analytical calculations (if possible).
void Analytical (const Index &m)
const Numeric & Perturbation () const
Size of perturbation used for perturbation calculations.
void Perturbation (const Numeric &p)
const ArrayOfVector & Grids () const
Grids.
void Grids (const ArrayOfVector &g)
Private Attributes
String mmaintag
String msubtag
String mmode
Index manalytical
Numeric mperturbation
ArrayOfVector mgrids
Detailed Description
Contains the data for one retrieval quantity.
Author
Mattias Ekstrom
Definition at line 45 of file jacobian.h.
Constructor & Destructor Documentation
RetrievalQuantity() [1/2]
RetrievalQuantity::RetrievalQuantity () inline
Default constructor.
Needed by make_array.
Definition at line 49 of file jacobian.h.
RetrievalQuantity() [2/2]
RetrievalQuantity::RetrievalQuantity (const String & maintag, const String & subtag, const String & mode, const Index & analytical, const Numeric & perturbation, const ArrayOfVector & grids) inline
Constructor that sets the values.
Definition at line 59 of file jacobian.h.
Member Function Documentation
Analytical() [1/2]
const Index& RetrievalQuantity::Analytical () const inline
Boolean to make analytical calculations (if possible).
Definition at line 85 of file jacobian.h.
References manalytical.
Referenced by jacobianAddAbsSpecies(), jacobianAddFreqShift(), jacobianAddFreqStretch(), jacobianAddPointingZa(), jacobianAddPolyfit(), jacobianAddSinefit(), jacobianAddTemperature(), jacobianAddWind(), jacobianCalcAbsSpeciesPerturbations(), jacobianCalcTemperaturePerturbations(), operator<<(), and xml_write_to_stream().
Analytical() [2/2]
void RetrievalQuantity::Analytical (const Index & m) inline
Definition at line 86 of file jacobian.h.
References manalytical.
Grids() [1/2]
const ArrayOfVector& RetrievalQuantity::Grids () const inline
Grids.
Definition grids for the jacobian, eg. p, lat and lon.
Definition at line 91 of file jacobian.h.
References mgrids.
Referenced by diy_from_path_to_rgrids(), jacobianAddAbsSpecies(), jacobianAddFreqShift(), jacobianAddFreqStretch(), jacobianAddPointingZa(), jacobianAddPolyfit(), jacobianAddSinefit(), jacobianAddTemperature(), jacobianAddWind(), jacobianCalcAbsSpeciesPerturbations(), jacobianCalcFreqShift(), jacobianCalcFreqStretch(), jacobianCalcPointingZaInterp(), jacobianCalcPointingZaRecalc(), jacobianCalcTemperaturePerturbations(), and xml_write_to_stream().
Grids() [2/2]
void RetrievalQuantity::Grids (const ArrayOfVector & g) inline
Definition at line 92 of file jacobian.h.
References mgrids.
MainTag() [1/2]
const String& RetrievalQuantity::MainTag () const inline
Main tag.
Definition at line 76 of file jacobian.h.
References mmaintag.
Referenced by jacobianAddAbsSpecies(), jacobianAddFreqShift(), jacobianAddFreqStretch(), jacobianAddPointingZa(), jacobianAddPolyfit(), jacobianAddSinefit(), jacobianAddTemperature(), jacobianAddWind(), operator<<(), and xml_write_to_stream().
MainTag() [2/2]
void RetrievalQuantity::MainTag (const String & mt) inline
Definition at line 77 of file jacobian.h.
References mmaintag.
Mode() [1/2]
const String& RetrievalQuantity::Mode () const inline
Calculation mode.
Eg. "abs", "rel", "vmr" and "nd".
Definition at line 82 of file jacobian.h.
References mmode.
Referenced by jacobianAddAbsSpecies(), jacobianAddFreqShift(), jacobianAddFreqStretch(), jacobianAddPointingZa(), jacobianAddPolyfit(), jacobianAddSinefit(), jacobianAddTemperature(), jacobianCalcAbsSpeciesPerturbations(), operator<<(), and xml_write_to_stream().
Mode() [2/2]
void RetrievalQuantity::Mode (const String & m) inline
Definition at line 83 of file jacobian.h.
References mmode.
Perturbation() [1/2]
const Numeric& RetrievalQuantity::Perturbation () const inline
Size of perturbation used for perturbation calculations.
Definition at line 88 of file jacobian.h.
References mperturbation.
Referenced by jacobianAddAbsSpecies(), jacobianAddFreqShift(), jacobianAddFreqStretch(), jacobianAddPointingZa(), jacobianAddPolyfit(), jacobianAddSinefit(), jacobianAddTemperature(), jacobianCalcAbsSpeciesPerturbations(), jacobianCalcFreqShift(), jacobianCalcFreqStretch(), jacobianCalcPointingZaInterp(), jacobianCalcPointingZaRecalc(), jacobianCalcTemperaturePerturbations(), and xml_write_to_stream().
Perturbation() [2/2]
void RetrievalQuantity::Perturbation (const Numeric & p) inline
Definition at line 89 of file jacobian.h.
References mperturbation.
Subtag() [1/2]
const String& RetrievalQuantity::Subtag () const inline
Subtag.
Eg. for gas species: O3, ClO.
Definition at line 79 of file jacobian.h.
References msubtag.
Referenced by jacobianAddAbsSpecies(), jacobianAddFreqShift(), jacobianAddFreqStretch(), jacobianAddPointingZa(), jacobianAddPolyfit(), jacobianAddSinefit(), jacobianAddTemperature(), jacobianAddWind(), jacobianCalcTemperaturePerturbations(), operator<<(), and xml_write_to_stream().
Subtag() [2/2]
void RetrievalQuantity::Subtag (const String & st) inline
Definition at line 80 of file jacobian.h.
References msubtag.
Member Data Documentation
manalytical
Index RetrievalQuantity::manalytical private
Definition at line 99 of file jacobian.h.
Referenced by Analytical().
mgrids
ArrayOfVector RetrievalQuantity::mgrids private
Definition at line 101 of file jacobian.h.
Referenced by Grids().
mmaintag
String RetrievalQuantity::mmaintag private
Definition at line 96 of file jacobian.h.
Referenced by MainTag().
mmode
String RetrievalQuantity::mmode private
Definition at line 98 of file jacobian.h.
Referenced by Mode().
mperturbation
Numeric RetrievalQuantity::mperturbation private
Definition at line 100 of file jacobian.h.
Referenced by Perturbation().
msubtag
String RetrievalQuantity::msubtag private
Definition at line 97 of file jacobian.h.
Referenced by Subtag().
The documentation for this class was generated from the following file:
jacobian.h