ARTS: SpeciesAuxData Class Reference
SpeciesAuxData Class Reference
Auxiliary data for isotopologues.
#include <absorption.h>
Public Member Functions
SpeciesAuxData ()
Default constructor.
void initParams (Index nparams)
Resize according to builtin isotopologues in species data.
Numeric getParam (Index species, Index isotopologue, Index col) const
Get single parameter value.
void setParam (Index species, Index isotopologue, Index col, Numeric v)
Set parameter.
const ArrayOfMatrix & getParams () const
Return a constant reference to the parameters.
bool ReadFromStream (String &artsid, istream &is, Index nparams, const Verbosity &verbosity)
Read parameters from input stream.
Private Attributes
ArrayOfMatrix mparams
Detailed Description
Auxiliary data for isotopologues.
Definition at line 439 of file absorption.h.
Constructor & Destructor Documentation
SpeciesAuxData()
SpeciesAuxData::SpeciesAuxData () inline
Default constructor.
Definition at line 443 of file absorption.h.
Member Function Documentation
getParam()
Numeric SpeciesAuxData::getParam (Index species, Index isotopologue, Index col) const inline
Get single parameter value.
Definition at line 449 of file absorption.h.
References mparams.
Referenced by checkIsotopologueRatios(), propmat_clearskyAddZeeman(), and xsec_species().
getParams()
const ArrayOfMatrix& SpeciesAuxData::getParams () const inline
Return a constant reference to the parameters.
Definition at line 461 of file absorption.h.
References mparams.
Referenced by checkIsotopologueRatios(), operator<<(), and xml_write_to_stream().
initParams()
void SpeciesAuxData::initParams (Index nparams)
Resize according to builtin isotopologues in species data.
Definition at line 90 of file absorption.cc.
References mparams, and global_data::species_data.
Referenced by fillSpeciesAuxDataWithIsotopologueRatiosFromSpeciesData(), and xml_read_from_stream().
ReadFromStream()
bool SpeciesAuxData::ReadFromStream (String & artsid, istream & is, Index nparams, const Verbosity & verbosity)
Read parameters from input stream.
Definition at line 104 of file absorption.cc.
References CREATE_OUT3, extract(), SpeciesRecord::Isotopologue(), mparams, SpeciesRecord::Name(), my_basic_string< charT >::nelem(), global_data::species_data, and SpecIsoMap::Speciesindex().
Referenced by xml_read_from_stream().
setParam()
void SpeciesAuxData::setParam (Index species, Index isotopologue, Index col, Numeric v) inline
Set parameter.
Definition at line 455 of file absorption.h.
References mparams.
Referenced by fillSpeciesAuxDataWithIsotopologueRatiosFromSpeciesData().
Member Data Documentation
mparams
ArrayOfMatrix SpeciesAuxData::mparams private
Definition at line 468 of file absorption.h.
Referenced by getParam(), getParams(), initParams(), ReadFromStream(), and setParam().
The documentation for this class was generated from the following files:
absorption.h
absorption.cc