ARTS: Tensor7View Class Reference
Tensor7View Class Reference
The Tensor7View class.
#include <matpackVII.h>
Public Member Functions
ConstTensor7View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor6View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor6View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor6View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor6View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, const Range &v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &l, Index v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &l, const Range &v, Index s, Index b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &l, const Range &v, Index s, Index b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, Index r, Index c) const
ConstMatrixView operator() (Index l, Index v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstMatrixView operator() (Index l, Index v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstMatrixView operator() (Index l, Index v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index l, Index v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index l, const Range &v, Index s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (const Range &l, Index v, Index s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index l, Index v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstMatrixView operator() (Index l, Index v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index l, Index v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index l, const Range &v, Index s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (const Range &l, Index v, Index s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index l, Index v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index l, Index v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index l, const Range &v, Index s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (const Range &l, Index v, Index s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index l, Index v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (Index l, const Range &v, Index s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &l, Index v, Index s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (Index l, const Range &v, const Range &s, Index b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &l, Index v, const Range &s, Index b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &l, const Range &v, Index s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (Index l, Index v, Index s, Index b, Index p, Index r, const Range &c) const
ConstVectorView operator() (Index l, Index v, Index s, Index b, Index p, const Range &r, Index c) const
ConstVectorView operator() (Index l, Index v, Index s, Index b, const Range &p, Index r, Index c) const
ConstVectorView operator() (Index l, Index v, Index s, const Range &b, Index p, Index r, Index c) const
ConstVectorView operator() (Index l, Index v, const Range &s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (Index l, const Range &v, Index s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (const Range &l, Index v, Index s, Index b, Index p, Index r, Index c) const
Numeric operator() (Index l, Index v, Index s, Index b, Index p, Index r, Index c) const
Numeric get (Index l, Index v, Index s, Index b, Index p, Index r, Index c) const
Get element implementation without assertions.
Tensor7View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c)
Tensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c)
Tensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c)
Tensor6View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c)
Tensor6View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor6View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor6View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c)
Tensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c)
Tensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c)
Tensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c)
Tensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c)
Tensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c)
Tensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c)
Tensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c)
Tensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c)
Tensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c)
Tensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c)
Tensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c)
Tensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c)
Tensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c)
Tensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c)
Tensor5View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor5View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor4View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, Index r, Index c)
Tensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, Index r, Index c)
Tensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, Index r, Index c)
Tensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, Index r, Index c)
Tensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c)
Tensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, const Range &r, Index c)
Tensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, const Range &r, Index c)
Tensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, const Range &r, Index c)
Tensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c)
Tensor4View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, const Range &r, Index c)
Tensor4View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, const Range &r, Index c)
Tensor4View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c)
Tensor4View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, const Range &r, Index c)
Tensor4View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c)
Tensor4View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c)
Tensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, Index r, const Range &c)
Tensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, Index r, const Range &c)
Tensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, Index r, const Range &c)
Tensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c)
Tensor4View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, Index r, const Range &c)
Tensor4View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, Index r, const Range &c)
Tensor4View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c)
Tensor4View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, Index r, const Range &c)
Tensor4View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c)
Tensor4View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c)
Tensor4View operator() (const Range &l, const Range &v, Index s, Index b, Index p, const Range &r, const Range &c)
Tensor4View operator() (const Range &l, Index v, const Range &s, Index b, Index p, const Range &r, const Range &c)
Tensor4View operator() (Index l, const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c)
Tensor4View operator() (const Range &l, Index v, Index s, const Range &b, Index p, const Range &r, const Range &c)
Tensor4View operator() (Index l, const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c)
Tensor4View operator() (Index l, Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c)
Tensor4View operator() (const Range &l, Index v, Index s, Index b, const Range &p, const Range &r, const Range &c)
Tensor4View operator() (Index l, const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c)
Tensor4View operator() (Index l, Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c)
Tensor4View operator() (Index l, Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c)
Tensor3View operator() (Index l, Index v, Index s, Index b, const Range &p, const Range &r, const Range &c)
Tensor3View operator() (Index l, Index v, Index s, const Range &b, Index p, const Range &r, const Range &c)
Tensor3View operator() (Index l, Index v, const Range &s, Index b, Index p, const Range &r, const Range &c)
Tensor3View operator() (Index l, const Range &v, Index s, Index b, Index p, const Range &r, const Range &c)
Tensor3View operator() (const Range &l, Index v, Index s, Index b, Index p, const Range &r, const Range &c)
Tensor3View operator() (Index l, Index v, Index s, const Range &b, const Range &p, Index r, const Range &c)
Tensor3View operator() (Index l, Index v, const Range &s, Index b, const Range &p, Index r, const Range &c)
Tensor3View operator() (Index l, const Range &v, Index s, Index b, const Range &p, Index r, const Range &c)
Tensor3View operator() (const Range &l, Index v, Index s, Index b, const Range &p, Index r, const Range &c)
Tensor3View operator() (Index l, Index v, const Range &s, const Range &b, Index p, Index r, const Range &c)
Tensor3View operator() (Index l, const Range &v, Index s, const Range &b, Index p, Index r, const Range &c)
Tensor3View operator() (const Range &l, Index v, Index s, const Range &b, Index p, Index r, const Range &c)
Tensor3View operator() (Index l, const Range &v, const Range &s, Index b, Index p, Index r, const Range &c)
Tensor3View operator() (const Range &l, Index v, const Range &s, Index b, Index p, Index r, const Range &c)
Tensor3View operator() (const Range &l, const Range &v, Index s, Index b, Index p, Index r, const Range &c)
Tensor3View operator() (Index l, Index v, Index s, const Range &b, const Range &p, const Range &r, Index c)
Tensor3View operator() (Index l, Index v, const Range &s, Index b, const Range &p, const Range &r, Index c)
Tensor3View operator() (Index l, const Range &v, Index s, Index b, const Range &p, const Range &r, Index c)
Tensor3View operator() (const Range &l, Index v, Index s, Index b, const Range &p, const Range &r, Index c)
Tensor3View operator() (Index l, Index v, const Range &s, const Range &b, Index p, const Range &r, Index c)
Tensor3View operator() (Index l, const Range &v, Index s, const Range &b, Index p, const Range &r, Index c)
Tensor3View operator() (const Range &l, Index v, Index s, const Range &b, Index p, const Range &r, Index c)
Tensor3View operator() (Index l, const Range &v, const Range &s, Index b, Index p, const Range &r, Index c)
Tensor3View operator() (const Range &l, Index v, const Range &s, Index b, Index p, const Range &r, Index c)
Tensor3View operator() (const Range &l, const Range &v, Index s, Index b, Index p, const Range &r, Index c)
Tensor3View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, Index r, Index c)
Tensor3View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, Index r, Index c)
Tensor3View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, Index r, Index c)
Tensor3View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, Index r, Index c)
Tensor3View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, Index r, Index c)
Tensor3View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, Index r, Index c)
Tensor3View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, Index r, Index c)
Tensor3View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, Index r, Index c)
Tensor3View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, Index r, Index c)
Tensor3View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, Index r, Index c)
MatrixView operator() (Index l, Index v, Index s, Index b, Index p, const Range &r, const Range &c)
MatrixView operator() (Index l, Index v, Index s, Index b, const Range &p, Index r, const Range &c)
MatrixView operator() (Index l, Index v, Index s, const Range &b, Index p, Index r, const Range &c)
MatrixView operator() (Index l, Index v, const Range &s, Index b, Index p, Index r, const Range &c)
MatrixView operator() (Index l, const Range &v, Index s, Index b, Index p, Index r, const Range &c)
MatrixView operator() (const Range &l, Index v, Index s, Index b, Index p, Index r, const Range &c)
MatrixView operator() (Index l, Index v, Index s, Index b, const Range &p, const Range &r, Index c)
MatrixView operator() (Index l, Index v, Index s, const Range &b, Index p, const Range &r, Index c)
MatrixView operator() (Index l, Index v, const Range &s, Index b, Index p, const Range &r, Index c)
MatrixView operator() (Index l, const Range &v, Index s, Index b, Index p, const Range &r, Index c)
MatrixView operator() (const Range &l, Index v, Index s, Index b, Index p, const Range &r, Index c)
MatrixView operator() (Index l, Index v, Index s, const Range &b, const Range &p, Index r, Index c)
MatrixView operator() (Index l, Index v, const Range &s, Index b, const Range &p, Index r, Index c)
MatrixView operator() (Index l, const Range &v, Index s, Index b, const Range &p, Index r, Index c)
MatrixView operator() (const Range &l, Index v, Index s, Index b, const Range &p, Index r, Index c)
MatrixView operator() (Index l, Index v, const Range &s, const Range &b, Index p, Index r, Index c)
MatrixView operator() (Index l, const Range &v, Index s, const Range &b, Index p, Index r, Index c)
MatrixView operator() (const Range &l, Index v, Index s, const Range &b, Index p, Index r, Index c)
MatrixView operator() (Index l, const Range &v, const Range &s, Index b, Index p, Index r, Index c)
MatrixView operator() (const Range &l, Index v, const Range &s, Index b, Index p, Index r, Index c)
MatrixView operator() (const Range &l, const Range &v, Index s, Index b, Index p, Index r, Index c)
VectorView operator() (Index l, Index v, Index s, Index b, Index p, Index r, const Range &c)
VectorView operator() (Index l, Index v, Index s, Index b, Index p, const Range &r, Index c)
VectorView operator() (Index l, Index v, Index s, Index b, const Range &p, Index r, Index c)
VectorView operator() (Index l, Index v, Index s, const Range &b, Index p, Index r, Index c)
VectorView operator() (Index l, Index v, const Range &s, Index b, Index p, Index r, Index c)
VectorView operator() (Index l, const Range &v, Index s, Index b, Index p, Index r, Index c)
VectorView operator() (const Range &l, Index v, Index s, Index b, Index p, Index r, Index c)
Numeric & operator() (Index l, Index v, Index s, Index b, Index p, Index r, Index c)
Numeric & get (Index l, Index v, Index s, Index b, Index p, Index r, Index c)
Get element implementation without assertions.
const Numeric * get_c_array () const
Conversion to plain C-array.
Numeric * get_c_array ()
Conversion to plain C-array.
ConstIterator7D begin () const
Return iterator to sub-tensor.
ConstIterator7D end () const
Return const iterator behind last sub-tensor.
Iterator7D begin ()
Return iterator to first sub-tensor.
Iterator7D end ()
Return iterator behind last sub-tensor.
Tensor7View & operator= (const ConstTensor7View &v)
Assignment operator.
Tensor7View & operator= (const Tensor7View &v)
Assignment from Tensor7View to Tensor7View.
Tensor7View & operator= (const Tensor7 &v)
Assignment from a Tensor7.
Tensor7View & operator= (Numeric x)
Assigning a scalar to a Tensor7View will set all elements to this value.
Tensor7View & operator*= (Numeric x)
Multiplication by scalar.
Tensor7View & operator/= (Numeric x)
Division by scalar.
Tensor7View & operator+= (Numeric x)
Addition of scalar.
Tensor7View & operator-= (Numeric x)
Subtraction of scalar.
Tensor7View & operator*= (const ConstTensor7View &x)
Element-vise multiplication by another Tensor7.
Tensor7View & operator/= (const ConstTensor7View &x)
Element-vise division by another Tensor7.
Tensor7View & operator+= (const ConstTensor7View &x)
Element-vise addition of another Tensor7.
Tensor7View & operator-= (const ConstTensor7View &x)
Element-vise subtraction of another Tensor7.
virtual ~Tensor7View ()
Destructor.
Tensor7View (const Tensor6View &a)
Special constructor to make a Tensor7 view of a Tensor6.
Public Member Functions inherited from ConstTensor7View
Index nlibraries () const
Returns the number of libraries.
Index nvitrines () const
Returns the number of vitrines.
Index nshelves () const
Returns the number of shelves.
Index nbooks () const
Returns the number of books.
Index npages () const
Returns the number of pages.
Index nrows () const
Returns the number of rows.
Index ncols () const
Returns the number of columns.
ConstTensor7View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor6View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor6View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor6View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor6View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor6View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor5View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &l, const Range &v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor4View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor4View operator() (const Range &l, const Range &v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, Index v, const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor4View operator() (const Range &l, Index v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, const Range &v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, Index v, const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor4View operator() (Index l, Index v, Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, Index s, Index b, const Range &p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, Index s, const Range &b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, Index s, const Range &b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, const Range &v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &l, Index v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (const Range &l, const Range &v, Index s, Index b, Index p, Index r, const Range &c) const
ConstTensor3View operator() (Index l, Index v, Index s, const Range &b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (const Range &l, const Range &v, Index s, Index b, Index p, const Range &r, Index c) const
ConstTensor3View operator() (Index l, Index v, const Range &s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, const Range &v, Index s, Index b, const Range &p, Index r, Index c) const
ConstTensor3View operator() (Index l, const Range &v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, Index v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, const Range &v, Index s, const Range &b, Index p, Index r, Index c) const
ConstTensor3View operator() (const Range &l, const Range &v, const Range &s, Index b, Index p, Index r, Index c) const
ConstMatrixView operator() (Index l, Index v, Index s, Index b, Index p, const Range &r, const Range &c) const
ConstMatrixView operator() (Index l, Index v, Index s, Index b, const Range &p, Index r, const Range &c) const
ConstMatrixView operator() (Index l, Index v, Index s, const Range &b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index l, Index v, const Range &s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index l, const Range &v, Index s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (const Range &l, Index v, Index s, Index b, Index p, Index r, const Range &c) const
ConstMatrixView operator() (Index l, Index v, Index s, Index b, const Range &p, const Range &r, Index c) const
ConstMatrixView operator() (Index l, Index v, Index s, const Range &b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index l, Index v, const Range &s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index l, const Range &v, Index s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (const Range &l, Index v, Index s, Index b, Index p, const Range &r, Index c) const
ConstMatrixView operator() (Index l, Index v, Index s, const Range &b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index l, Index v, const Range &s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index l, const Range &v, Index s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (const Range &l, Index v, Index s, Index b, const Range &p, Index r, Index c) const
ConstMatrixView operator() (Index l, Index v, const Range &s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (Index l, const Range &v, Index s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &l, Index v, Index s, const Range &b, Index p, Index r, Index c) const
ConstMatrixView operator() (Index l, const Range &v, const Range &s, Index b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &l, Index v, const Range &s, Index b, Index p, Index r, Index c) const
ConstMatrixView operator() (const Range &l, const Range &v, Index s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (Index l, Index v, Index s, Index b, Index p, Index r, const Range &c) const
ConstVectorView operator() (Index l, Index v, Index s, Index b, Index p, const Range &r, Index c) const
ConstVectorView operator() (Index l, Index v, Index s, Index b, const Range &p, Index r, Index c) const
ConstVectorView operator() (Index l, Index v, Index s, const Range &b, Index p, Index r, Index c) const
ConstVectorView operator() (Index l, Index v, const Range &s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (Index l, const Range &v, Index s, Index b, Index p, Index r, Index c) const
ConstVectorView operator() (const Range &l, Index v, Index s, Index b, Index p, Index r, Index c) const
Numeric operator() (Index l, Index v, Index s, Index b, Index p, Index r, Index c) const
Numeric get (Index l, Index v, Index s, Index b, Index p, Index r, Index c) const
Get element implementation without assertions.
ConstIterator7D begin () const
Return const iterator to first sub-tensor.
ConstIterator7D end () const
Return const iterator behind last sub-tensor.
virtual ~ConstTensor7View ()
Destructor.
ConstTensor7View (const ConstTensor6View &a)
Special constructor to make a Tensor7 view of a Tensor6.
Protected Member Functions
Tensor7View ()
Default constructor.
Tensor7View (Numeric *data, const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Explicit constructor.
Tensor7View (Numeric *data, const Range &pl, const Range &pv, const Range &ps, const Range &pb, const Range &pp, const Range &pr, const Range &pc, const Range &nl, const Range &nv, const Range &ns, const Range &nb, const Range &np, const Range &nr, const Range &nc)
Recursive constructor.
Protected Member Functions inherited from ConstTensor7View
ConstTensor7View ()
Default constructor.
ConstTensor7View (Numeric *data, const Range &l, const Range &v, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Explicit constructor.
ConstTensor7View (Numeric *data, const Range &pl, const Range &pv, const Range &ps, const Range &pb, const Range &pp, const Range &pr, const Range &pc, const Range &nl, const Range &nv, const Range &ns, const Range &nb, const Range &np, const Range &nr, const Range &nc)
Recursive constructor.
Additional Inherited Members
Protected Attributes inherited from ConstTensor7View
Range mlr
The library range of mdata that is actually used.
Range mvr
The vitrine range of mdata that is actually used.
Range msr
The shelf range of mdata that is actually used.
Range mbr
The book range of mdata that is actually used.
Range mpr
The page range of mdata that is actually used.
Range mrr
The row range of mdata that is actually used.
Range mcr
The column range of mdata that is actually used.
Numeric * mdata
Pointer to the plain C array that holds the data.
Detailed Description
The Tensor7View class.
This contains the main implementation of a Tensor7. It defines the concepts of Tensor7View. Plus additionally the recursive subrange operator, which makes it possible to create a Tensor7View from a subrange of a Tensor7View.
The class Tensor7 is just a special case of a Tensor7View which also allocates storage.
Definition at line 780 of file matpackVII.h.
Constructor & Destructor Documentation
~Tensor7View()
virtual Tensor7View::~Tensor7View () inline virtual
Destructor.
Definition at line 1900 of file matpackVII.h.
Tensor7View() [1/4]
Tensor7View::Tensor7View (const Tensor6View & a)
Special constructor to make a Tensor7 view of a Tensor6.
Definition at line 5133 of file matpackVII.cc.
Tensor7View() [2/4]
Tensor7View::Tensor7View () protected
Default constructor.
This is necessary, so that we can have a default constructor for the derived class Tensor7.
Definition at line 5154 of file matpackVII.cc.
Tensor7View() [3/4]
Tensor7View::Tensor7View (Numeric * data, const Range & l, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c) protected
Explicit constructor.
This one is used by Tensor7 to initialize its own Tensor7View part.
Definition at line 5162 of file matpackVII.cc.
Tensor7View() [4/4]
Tensor7View::Tensor7View (Numeric * data, const Range & pl, const Range & pv, const Range & ps, const Range & pb, const Range & pp, const Range & pr, const Range & pc, const Range & nl, const Range & nv, const Range & ns, const Range & nb, const Range & np, const Range & nr, const Range & nc) protected
Recursive constructor.
This is used to construct SubMatrices from SubMatrices. That means that the new ranges have to be interpreted relative to the original ranges.
The new ranges may contain -1 for the extent which acts as a joker. However, the used Range constructor converts this to an explicit range, consistent with the original Range.
Parameters
*data The actual data.
pl Previous range.
pv Previous range.
ps Previous range.
pb Previous range.
pp Previous range.
pr Previous range.
pc Previous range.
nl New Range.
nv New Range.
ns New Range.
nb New Range.
np New Range.
nr New Range.
nc New Range.
Definition at line 5199 of file matpackVII.cc.
Member Function Documentation
begin() [1/2]
Iterator7D Tensor7View::begin ()
Return iterator to first sub-tensor.
Definition at line 4914 of file matpackVII.cc.
References ConstTensor7View::mbr, ConstTensor7View::mcr, ConstTensor7View::mdata, ConstTensor7View::mlr, ConstTensor7View::mpr, ConstTensor7View::mrr, ConstTensor7View::msr, Range::mstart, Range::mstride, and ConstTensor7View::mvr.
begin() [2/2]
ConstIterator7D Tensor7View::begin () const
Return iterator to sub-tensor.
Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 4902 of file matpackVII.cc.
References ConstTensor7View::begin().
Referenced by operator*=(), operator+=(), operator-=(), operator/=(), operator=(), Tensor7::operator=(), Tensor7::Tensor7(), and transform().
end() [1/2]
Iterator7D Tensor7View::end ()
Return iterator behind last sub-tensor.
Definition at line 4927 of file matpackVII.cc.
References ConstTensor7View::mbr, ConstTensor7View::mcr, ConstTensor7View::mdata, Range::mextent, ConstTensor7View::mlr, ConstTensor7View::mpr, ConstTensor7View::mrr, ConstTensor7View::msr, Range::mstart, Range::mstride, and ConstTensor7View::mvr.
end() [2/2]
ConstIterator7D Tensor7View::end () const
Return const iterator behind last sub-tensor.
Definition at line 4908 of file matpackVII.cc.
References ConstTensor7View::end().
Referenced by operator*=(), operator+=(), operator-=(), operator/=(), operator=(), Tensor7::operator=(), and Tensor7::Tensor7().
get() [1/2]
Numeric& Tensor7View::get (Index l, Index v, Index s, Index b, Index p, Index r, Index c) inline
Get element implementation without assertions.
Definition at line 1861 of file matpackVII.h.
References ConstTensor7View::mdata, and OFFSET.
get() [2/2]
Numeric Tensor7View::get (Index l, Index v, Index s, Index b, Index p, Index r, Index c) const inline
Get element implementation without assertions.
Definition at line 1315 of file matpackVII.h.
References ConstTensor7View::get().
Referenced by interpweights(), and operator()().
get_c_array() [1/2]
Numeric * Tensor7View::get_c_array ()
Conversion to plain C-array.
This function returns a pointer to the raw data. It fails if the Tensor5View is not pointing to the beginning of a Tensor5 or the stride is not 1 because the caller expects to get a C array with continuous data.
Definition at line 4864 of file matpackVII.cc.
References ConstTensor7View::mbr, ConstTensor7View::mcr, ConstTensor7View::mdata, Range::mextent, ConstTensor7View::mlr, ConstTensor7View::mpr, ConstTensor7View::mrr, ConstTensor7View::msr, Range::mstart, Range::mstride, and ConstTensor7View::mvr.
get_c_array() [2/2]
const Numeric * Tensor7View::get_c_array () const
Conversion to plain C-array.
This function returns a pointer to the raw data. It fails if the Tensor5View is not pointing to the beginning of a Tensor5 or the stride is not 1 because the caller expects to get a C array with continuous data.
Definition at line 4885 of file matpackVII.cc.
References ConstTensor7View::mbr, ConstTensor7View::mcr, ConstTensor7View::mdata, Range::mextent, ConstTensor7View::mlr, ConstTensor7View::mpr, ConstTensor7View::mrr, ConstTensor7View::msr, Range::mstart, Range::mstride, and ConstTensor7View::mvr.
Referenced by Reduce().
operator()() [1/256]
Tensor7View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 3081 of file matpackVII.cc.
operator()() [2/256]
ConstTensor7View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 1999 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [3/256]
Tensor6View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 3103 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [4/256]
ConstTensor6View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 2016 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [5/256]
Tensor6View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 3127 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [6/256]
ConstTensor6View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 2033 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [7/256]
Tensor5View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, const Range & p, Index r, Index c)
Definition at line 3247 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [8/256]
ConstTensor5View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 2118 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [9/256]
Tensor6View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 3151 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [10/256]
ConstTensor6View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 2050 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [11/256]
Tensor5View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, Index p, const Range & r, Index c)
Definition at line 3273 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [12/256]
ConstTensor5View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 2135 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [13/256]
Tensor5View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, Index p, Index r, const Range & c)
Definition at line 3377 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [14/256]
ConstTensor5View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 2203 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [15/256]
Tensor4View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, Index p, Index r, Index c)
Definition at line 3637 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [16/256]
ConstTensor4View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, const Range & b, Index p, Index r, Index c) const
Definition at line 2373 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [17/256]
Tensor6View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 3175 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [18/256]
ConstTensor6View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 2067 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [19/256]
Tensor5View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, const Range & p, const Range & r, Index c)
Definition at line 3299 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [20/256]
ConstTensor5View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 2152 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [21/256]
Tensor5View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, const Range & p, Index r, const Range & c)
Definition at line 3403 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [22/256]
ConstTensor5View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 2220 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [23/256]
Tensor4View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, const Range & p, Index r, Index c)
Definition at line 3665 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [24/256]
ConstTensor4View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, const Range & p, Index r, Index c) const
Definition at line 2390 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [25/256]
Tensor5View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, Index p, const Range & r, const Range & c)
Definition at line 3481 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [26/256]
ConstTensor5View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 2271 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [27/256]
Tensor4View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, Index p, const Range & r, Index c)
Definition at line 3749 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [28/256]
ConstTensor4View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, Index p, const Range & r, Index c) const
Definition at line 2441 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [29/256]
Tensor4View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, Index p, Index r, const Range & c)
Definition at line 3917 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [30/256]
ConstTensor4View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, Index p, Index r, const Range & c) const
Definition at line 2543 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [31/256]
Tensor3View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, Index p, Index r, Index c)
Definition at line 4617 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [32/256]
ConstTensor3View Tensor7View::operator() (const Range & l, const Range & v, const Range & s, Index b, Index p, Index r, Index c) const
Definition at line 2951 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [33/256]
Tensor6View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 3199 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [34/256]
ConstTensor6View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 2084 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [35/256]
Tensor5View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 3325 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [36/256]
ConstTensor5View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 2169 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [37/256]
Tensor5View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 3429 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [38/256]
ConstTensor5View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 2237 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [39/256]
Tensor4View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, const Range & p, Index r, Index c)
Definition at line 3693 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [40/256]
ConstTensor4View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 2407 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [41/256]
Tensor5View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 3507 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [42/256]
ConstTensor5View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 2288 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [43/256]
Tensor4View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, Index p, const Range & r, Index c)
Definition at line 3777 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [44/256]
ConstTensor4View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 2458 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [45/256]
Tensor4View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, Index p, Index r, const Range & c)
Definition at line 3945 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [46/256]
ConstTensor4View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 2560 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [47/256]
Tensor3View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, Index p, Index r, Index c)
Definition at line 4587 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [48/256]
ConstTensor3View Tensor7View::operator() (const Range & l, const Range & v, Index s, const Range & b, Index p, Index r, Index c) const
Definition at line 2934 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [49/256]
Tensor5View Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 3559 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [50/256]
ConstTensor5View Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 2322 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [51/256]
Tensor4View Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, const Range & p, const Range & r, Index c)
Definition at line 3833 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [52/256]
ConstTensor4View Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 2492 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [53/256]
Tensor4View Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, const Range & p, Index r, const Range & c)
Definition at line 4001 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [54/256]
ConstTensor4View Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 2594 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [55/256]
Tensor3View Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, const Range & p, Index r, Index c)
Definition at line 4527 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [56/256]
ConstTensor3View Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, const Range & p, Index r, Index c) const
Definition at line 2900 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [57/256]
Tensor4View Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, Index p, const Range & r, const Range & c)
Definition at line 4085 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [58/256]
ConstTensor4View Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 2645 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [59/256]
Tensor3View Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, Index p, const Range & r, Index c)
Definition at line 4437 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [60/256]
ConstTensor3View Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, Index p, const Range & r, Index c) const
Definition at line 2849 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [61/256]
Tensor3View Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, Index p, Index r, const Range & c)
Definition at line 4317 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [62/256]
ConstTensor3View Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, Index p, Index r, const Range & c) const
Definition at line 2781 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [63/256]
MatrixView Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, Index p, Index r, Index c)
Definition at line 4807 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [64/256]
ConstMatrixView Tensor7View::operator() (const Range & l, const Range & v, Index s, Index b, Index p, Index r, Index c) const
Definition at line 3053 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [65/256]
Tensor6View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 3223 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [66/256]
ConstTensor6View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 2101 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [67/256]
Tensor5View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 3351 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [68/256]
ConstTensor5View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 2186 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [69/256]
Tensor5View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 3455 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [70/256]
ConstTensor5View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 2254 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [71/256]
Tensor4View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, const Range & p, Index r, Index c)
Definition at line 3721 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [72/256]
ConstTensor4View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 2424 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [73/256]
Tensor5View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 3533 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [74/256]
ConstTensor5View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 2305 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [75/256]
Tensor4View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, Index p, const Range & r, Index c)
Definition at line 3805 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [76/256]
ConstTensor4View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 2475 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [77/256]
Tensor4View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, Index p, Index r, const Range & c)
Definition at line 3973 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [78/256]
ConstTensor4View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 2577 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [79/256]
Tensor3View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, Index p, Index r, Index c)
Definition at line 4557 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [80/256]
ConstTensor3View Tensor7View::operator() (const Range & l, Index v, const Range & s, const Range & b, Index p, Index r, Index c) const
Definition at line 2917 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [81/256]
Tensor5View Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 3585 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [82/256]
ConstTensor5View Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 2339 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [83/256]
Tensor4View Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, const Range & p, const Range & r, Index c)
Definition at line 3861 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [84/256]
ConstTensor4View Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 2509 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [85/256]
Tensor4View Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, const Range & p, Index r, const Range & c)
Definition at line 4029 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [86/256]
ConstTensor4View Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 2611 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [87/256]
Tensor3View Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, const Range & p, Index r, Index c)
Definition at line 4497 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [88/256]
ConstTensor3View Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, const Range & p, Index r, Index c) const
Definition at line 2883 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [89/256]
Tensor4View Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, Index p, const Range & r, const Range & c)
Definition at line 4113 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [90/256]
ConstTensor4View Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 2662 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [91/256]
Tensor3View Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, Index p, const Range & r, Index c)
Definition at line 4407 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [92/256]
ConstTensor3View Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, Index p, const Range & r, Index c) const
Definition at line 2832 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [93/256]
Tensor3View Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, Index p, Index r, const Range & c)
Definition at line 4287 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [94/256]
ConstTensor3View Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, Index p, Index r, const Range & c) const
Definition at line 2764 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [95/256]
MatrixView Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, Index p, Index r, Index c)
Definition at line 4775 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [96/256]
ConstMatrixView Tensor7View::operator() (const Range & l, Index v, const Range & s, Index b, Index p, Index r, Index c) const
Definition at line 3036 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [97/256]
Tensor5View Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 3611 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [98/256]
ConstTensor5View Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 2356 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [99/256]
Tensor4View Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 3889 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [100/256]
ConstTensor4View Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 2526 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [101/256]
Tensor4View Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 4057 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [102/256]
ConstTensor4View Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 2628 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [103/256]
Tensor3View Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, const Range & p, Index r, Index c)
Definition at line 4467 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [104/256]
ConstTensor3View Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 2866 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [105/256]
Tensor4View Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 4141 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [106/256]
ConstTensor4View Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 2679 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [107/256]
Tensor3View Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, Index p, const Range & r, Index c)
Definition at line 4377 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [108/256]
ConstTensor3View Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 2815 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [109/256]
Tensor3View Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, Index p, Index r, const Range & c)
Definition at line 4257 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [110/256]
ConstTensor3View Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 2747 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [111/256]
MatrixView Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, Index p, Index r, Index c)
Definition at line 4743 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [112/256]
ConstMatrixView Tensor7View::operator() (const Range & l, Index v, Index s, const Range & b, Index p, Index r, Index c) const
Definition at line 3019 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [113/256]
Tensor4View Tensor7View::operator() (const Range & l, Index v, Index s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 4169 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [114/256]
ConstTensor4View Tensor7View::operator() (const Range & l, Index v, Index s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 2696 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [115/256]
Tensor3View Tensor7View::operator() (const Range & l, Index v, Index s, Index b, const Range & p, const Range & r, Index c)
Definition at line 4347 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [116/256]
ConstTensor3View Tensor7View::operator() (const Range & l, Index v, Index s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 2798 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [117/256]
Tensor3View Tensor7View::operator() (const Range & l, Index v, Index s, Index b, const Range & p, Index r, const Range & c)
Definition at line 4227 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [118/256]
ConstTensor3View Tensor7View::operator() (const Range & l, Index v, Index s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 2730 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [119/256]
MatrixView Tensor7View::operator() (const Range & l, Index v, Index s, Index b, const Range & p, Index r, Index c)
Definition at line 4711 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [120/256]
ConstMatrixView Tensor7View::operator() (const Range & l, Index v, Index s, Index b, const Range & p, Index r, Index c) const
Definition at line 3002 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [121/256]
Tensor3View Tensor7View::operator() (const Range & l, Index v, Index s, Index b, Index p, const Range & r, const Range & c)
Definition at line 4197 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [122/256]
ConstTensor3View Tensor7View::operator() (const Range & l, Index v, Index s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 2713 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [123/256]
MatrixView Tensor7View::operator() (const Range & l, Index v, Index s, Index b, Index p, const Range & r, Index c)
Definition at line 4679 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [124/256]
ConstMatrixView Tensor7View::operator() (const Range & l, Index v, Index s, Index b, Index p, const Range & r, Index c) const
Definition at line 2985 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [125/256]
MatrixView Tensor7View::operator() (const Range & l, Index v, Index s, Index b, Index p, Index r, const Range & c)
Definition at line 4647 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [126/256]
ConstMatrixView Tensor7View::operator() (const Range & l, Index v, Index s, Index b, Index p, Index r, const Range & c) const
Definition at line 2968 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [127/256]
VectorView Tensor7View::operator() (const Range & l, Index v, Index s, Index b, Index p, Index r, Index c)
Definition at line 4839 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [128/256]
ConstVectorView Tensor7View::operator() (const Range & l, Index v, Index s, Index b, Index p, Index r, Index c) const
Definition at line 3070 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [129/256]
Tensor6View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 3091 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [130/256]
ConstTensor6View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 2007 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [131/256]
Tensor5View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 3114 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [132/256]
ConstTensor5View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 2024 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [133/256]
Tensor5View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 3138 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [134/256]
ConstTensor5View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 2041 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [135/256]
Tensor4View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, const Range & p, Index r, Index c)
Definition at line 3259 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [136/256]
ConstTensor4View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 2126 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [137/256]
Tensor5View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 3162 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [138/256]
ConstTensor5View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 2058 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [139/256]
Tensor4View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, Index p, const Range & r, Index c)
Definition at line 3285 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [140/256]
ConstTensor4View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 2143 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [141/256]
Tensor4View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, Index p, Index r, const Range & c)
Definition at line 3389 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [142/256]
ConstTensor4View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 2211 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [143/256]
Tensor3View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, Index p, Index r, Index c)
Definition at line 3650 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [144/256]
ConstTensor3View Tensor7View::operator() (Index l, const Range & v, const Range & s, const Range & b, Index p, Index r, Index c) const
Definition at line 2381 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [145/256]
Tensor5View Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 3186 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [146/256]
ConstTensor5View Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 2075 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [147/256]
Tensor4View Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, const Range & p, const Range & r, Index c)
Definition at line 3311 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [148/256]
ConstTensor4View Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 2160 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [149/256]
Tensor4View Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, const Range & p, Index r, const Range & c)
Definition at line 3415 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [150/256]
ConstTensor4View Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 2228 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [151/256]
Tensor3View Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, const Range & p, Index r, Index c)
Definition at line 3678 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [152/256]
ConstTensor3View Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, const Range & p, Index r, Index c) const
Definition at line 2398 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [153/256]
Tensor4View Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, Index p, const Range & r, const Range & c)
Definition at line 3493 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [154/256]
ConstTensor4View Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 2279 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [155/256]
Tensor3View Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, Index p, const Range & r, Index c)
Definition at line 3762 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [156/256]
ConstTensor3View Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, Index p, const Range & r, Index c) const
Definition at line 2449 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [157/256]
Tensor3View Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, Index p, Index r, const Range & c)
Definition at line 3930 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [158/256]
ConstTensor3View Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, Index p, Index r, const Range & c) const
Definition at line 2551 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [159/256]
MatrixView Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, Index p, Index r, Index c)
Definition at line 4631 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [160/256]
ConstMatrixView Tensor7View::operator() (Index l, const Range & v, const Range & s, Index b, Index p, Index r, Index c) const
Definition at line 2959 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [161/256]
Tensor5View Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 3210 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [162/256]
ConstTensor5View Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 2092 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [163/256]
Tensor4View Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 3337 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [164/256]
ConstTensor4View Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 2177 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [165/256]
Tensor4View Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 3441 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [166/256]
ConstTensor4View Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 2245 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [167/256]
Tensor3View Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, const Range & p, Index r, Index c)
Definition at line 3706 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [168/256]
ConstTensor3View Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 2415 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [169/256]
Tensor4View Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 3519 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [170/256]
ConstTensor4View Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 2296 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [171/256]
Tensor3View Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, Index p, const Range & r, Index c)
Definition at line 3790 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [172/256]
ConstTensor3View Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 2466 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [173/256]
Tensor3View Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, Index p, Index r, const Range & c)
Definition at line 3958 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [174/256]
ConstTensor3View Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 2568 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [175/256]
MatrixView Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, Index p, Index r, Index c)
Definition at line 4601 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [176/256]
ConstMatrixView Tensor7View::operator() (Index l, const Range & v, Index s, const Range & b, Index p, Index r, Index c) const
Definition at line 2942 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [177/256]
Tensor4View Tensor7View::operator() (Index l, const Range & v, Index s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 3571 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [178/256]
ConstTensor4View Tensor7View::operator() (Index l, const Range & v, Index s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 2330 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [179/256]
Tensor3View Tensor7View::operator() (Index l, const Range & v, Index s, Index b, const Range & p, const Range & r, Index c)
Definition at line 3846 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [180/256]
ConstTensor3View Tensor7View::operator() (Index l, const Range & v, Index s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 2500 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [181/256]
Tensor3View Tensor7View::operator() (Index l, const Range & v, Index s, Index b, const Range & p, Index r, const Range & c)
Definition at line 4014 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [182/256]
ConstTensor3View Tensor7View::operator() (Index l, const Range & v, Index s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 2602 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [183/256]
MatrixView Tensor7View::operator() (Index l, const Range & v, Index s, Index b, const Range & p, Index r, Index c)
Definition at line 4541 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [184/256]
ConstMatrixView Tensor7View::operator() (Index l, const Range & v, Index s, Index b, const Range & p, Index r, Index c) const
Definition at line 2908 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [185/256]
Tensor3View Tensor7View::operator() (Index l, const Range & v, Index s, Index b, Index p, const Range & r, const Range & c)
Definition at line 4098 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [186/256]
ConstTensor3View Tensor7View::operator() (Index l, const Range & v, Index s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 2653 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [187/256]
MatrixView Tensor7View::operator() (Index l, const Range & v, Index s, Index b, Index p, const Range & r, Index c)
Definition at line 4451 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [188/256]
ConstMatrixView Tensor7View::operator() (Index l, const Range & v, Index s, Index b, Index p, const Range & r, Index c) const
Definition at line 2857 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [189/256]
MatrixView Tensor7View::operator() (Index l, const Range & v, Index s, Index b, Index p, Index r, const Range & c)
Definition at line 4331 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [190/256]
ConstMatrixView Tensor7View::operator() (Index l, const Range & v, Index s, Index b, Index p, Index r, const Range & c) const
Definition at line 2789 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [191/256]
VectorView Tensor7View::operator() (Index l, const Range & v, Index s, Index b, Index p, Index r, Index c)
Definition at line 4822 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [192/256]
ConstVectorView Tensor7View::operator() (Index l, const Range & v, Index s, Index b, Index p, Index r, Index c) const
Definition at line 3061 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [193/256]
Tensor5View Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 3234 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [194/256]
ConstTensor5View Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 2109 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [195/256]
Tensor4View Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 3363 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [196/256]
ConstTensor4View Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 2194 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [197/256]
Tensor4View Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 3467 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [198/256]
ConstTensor4View Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 2262 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [199/256]
Tensor3View Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, const Range & p, Index r, Index c)
Definition at line 3734 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [200/256]
ConstTensor3View Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 2432 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [201/256]
Tensor4View Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 3545 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [202/256]
ConstTensor4View Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 2313 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [203/256]
Tensor3View Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, Index p, const Range & r, Index c)
Definition at line 3818 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [204/256]
ConstTensor3View Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 2483 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [205/256]
Tensor3View Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, Index p, Index r, const Range & c)
Definition at line 3986 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [206/256]
ConstTensor3View Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 2585 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [207/256]
MatrixView Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, Index p, Index r, Index c)
Definition at line 4571 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [208/256]
ConstMatrixView Tensor7View::operator() (Index l, Index v, const Range & s, const Range & b, Index p, Index r, Index c) const
Definition at line 2925 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [209/256]
Tensor4View Tensor7View::operator() (Index l, Index v, const Range & s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 3597 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [210/256]
ConstTensor4View Tensor7View::operator() (Index l, Index v, const Range & s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 2347 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [211/256]
Tensor3View Tensor7View::operator() (Index l, Index v, const Range & s, Index b, const Range & p, const Range & r, Index c)
Definition at line 3874 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [212/256]
ConstTensor3View Tensor7View::operator() (Index l, Index v, const Range & s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 2517 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [213/256]
Tensor3View Tensor7View::operator() (Index l, Index v, const Range & s, Index b, const Range & p, Index r, const Range & c)
Definition at line 4042 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [214/256]
ConstTensor3View Tensor7View::operator() (Index l, Index v, const Range & s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 2619 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [215/256]
MatrixView Tensor7View::operator() (Index l, Index v, const Range & s, Index b, const Range & p, Index r, Index c)
Definition at line 4511 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [216/256]
ConstMatrixView Tensor7View::operator() (Index l, Index v, const Range & s, Index b, const Range & p, Index r, Index c) const
Definition at line 2891 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [217/256]
Tensor3View Tensor7View::operator() (Index l, Index v, const Range & s, Index b, Index p, const Range & r, const Range & c)
Definition at line 4126 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [218/256]
ConstTensor3View Tensor7View::operator() (Index l, Index v, const Range & s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 2670 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [219/256]
MatrixView Tensor7View::operator() (Index l, Index v, const Range & s, Index b, Index p, const Range & r, Index c)
Definition at line 4421 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [220/256]
ConstMatrixView Tensor7View::operator() (Index l, Index v, const Range & s, Index b, Index p, const Range & r, Index c) const
Definition at line 2840 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [221/256]
MatrixView Tensor7View::operator() (Index l, Index v, const Range & s, Index b, Index p, Index r, const Range & c)
Definition at line 4301 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [222/256]
ConstMatrixView Tensor7View::operator() (Index l, Index v, const Range & s, Index b, Index p, Index r, const Range & c) const
Definition at line 2772 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [223/256]
VectorView Tensor7View::operator() (Index l, Index v, const Range & s, Index b, Index p, Index r, Index c)
Definition at line 4790 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [224/256]
ConstVectorView Tensor7View::operator() (Index l, Index v, const Range & s, Index b, Index p, Index r, Index c) const
Definition at line 3044 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [225/256]
Tensor4View Tensor7View::operator() (Index l, Index v, Index s, const Range & b, const Range & p, const Range & r, const Range & c)
Definition at line 3623 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [226/256]
ConstTensor4View Tensor7View::operator() (Index l, Index v, Index s, const Range & b, const Range & p, const Range & r, const Range & c) const
Definition at line 2364 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [227/256]
Tensor3View Tensor7View::operator() (Index l, Index v, Index s, const Range & b, const Range & p, const Range & r, Index c)
Definition at line 3902 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [228/256]
ConstTensor3View Tensor7View::operator() (Index l, Index v, Index s, const Range & b, const Range & p, const Range & r, Index c) const
Definition at line 2534 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [229/256]
Tensor3View Tensor7View::operator() (Index l, Index v, Index s, const Range & b, const Range & p, Index r, const Range & c)
Definition at line 4070 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [230/256]
ConstTensor3View Tensor7View::operator() (Index l, Index v, Index s, const Range & b, const Range & p, Index r, const Range & c) const
Definition at line 2636 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [231/256]
MatrixView Tensor7View::operator() (Index l, Index v, Index s, const Range & b, const Range & p, Index r, Index c)
Definition at line 4481 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [232/256]
ConstMatrixView Tensor7View::operator() (Index l, Index v, Index s, const Range & b, const Range & p, Index r, Index c) const
Definition at line 2874 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [233/256]
Tensor3View Tensor7View::operator() (Index l, Index v, Index s, const Range & b, Index p, const Range & r, const Range & c)
Definition at line 4154 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [234/256]
ConstTensor3View Tensor7View::operator() (Index l, Index v, Index s, const Range & b, Index p, const Range & r, const Range & c) const
Definition at line 2687 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [235/256]
MatrixView Tensor7View::operator() (Index l, Index v, Index s, const Range & b, Index p, const Range & r, Index c)
Definition at line 4391 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [236/256]
ConstMatrixView Tensor7View::operator() (Index l, Index v, Index s, const Range & b, Index p, const Range & r, Index c) const
Definition at line 2823 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [237/256]
MatrixView Tensor7View::operator() (Index l, Index v, Index s, const Range & b, Index p, Index r, const Range & c)
Definition at line 4271 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [238/256]
ConstMatrixView Tensor7View::operator() (Index l, Index v, Index s, const Range & b, Index p, Index r, const Range & c) const
Definition at line 2755 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [239/256]
VectorView Tensor7View::operator() (Index l, Index v, Index s, const Range & b, Index p, Index r, Index c)
Definition at line 4758 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [240/256]
ConstVectorView Tensor7View::operator() (Index l, Index v, Index s, const Range & b, Index p, Index r, Index c) const
Definition at line 3027 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [241/256]
Tensor3View Tensor7View::operator() (Index l, Index v, Index s, Index b, const Range & p, const Range & r, const Range & c)
Definition at line 4182 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [242/256]
ConstTensor3View Tensor7View::operator() (Index l, Index v, Index s, Index b, const Range & p, const Range & r, const Range & c) const
Definition at line 2704 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [243/256]
MatrixView Tensor7View::operator() (Index l, Index v, Index s, Index b, const Range & p, const Range & r, Index c)
Definition at line 4361 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [244/256]
ConstMatrixView Tensor7View::operator() (Index l, Index v, Index s, Index b, const Range & p, const Range & r, Index c) const
Definition at line 2806 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [245/256]
MatrixView Tensor7View::operator() (Index l, Index v, Index s, Index b, const Range & p, Index r, const Range & c)
Definition at line 4241 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [246/256]
ConstMatrixView Tensor7View::operator() (Index l, Index v, Index s, Index b, const Range & p, Index r, const Range & c) const
Definition at line 2738 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [247/256]
VectorView Tensor7View::operator() (Index l, Index v, Index s, Index b, const Range & p, Index r, Index c)
Definition at line 4726 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [248/256]
ConstVectorView Tensor7View::operator() (Index l, Index v, Index s, Index b, const Range & p, Index r, Index c) const
Definition at line 3010 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [249/256]
MatrixView Tensor7View::operator() (Index l, Index v, Index s, Index b, Index p, const Range & r, const Range & c)
Definition at line 4211 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [250/256]
ConstMatrixView Tensor7View::operator() (Index l, Index v, Index s, Index b, Index p, const Range & r, const Range & c) const
Definition at line 2721 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [251/256]
VectorView Tensor7View::operator() (Index l, Index v, Index s, Index b, Index p, const Range & r, Index c)
Definition at line 4694 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [252/256]
ConstVectorView Tensor7View::operator() (Index l, Index v, Index s, Index b, Index p, const Range & r, Index c) const
Definition at line 2993 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [253/256]
VectorView Tensor7View::operator() (Index l, Index v, Index s, Index b, Index p, Index r, const Range & c)
Definition at line 4662 of file matpackVII.cc.
References CHECK, and OFFSET.
operator()() [254/256]
ConstVectorView Tensor7View::operator() (Index l, Index v, Index s, Index b, Index p, Index r, const Range & c) const
Definition at line 2976 of file matpackVII.cc.
References ConstTensor7View::operator()().
operator()() [255/256]
Numeric& Tensor7View::operator() (Index l, Index v, Index s, Index b, Index p, Index r, Index c) inline
Definition at line 1847 of file matpackVII.h.
References CHECK, and get().
operator()() [256/256]
Numeric Tensor7View::operator() (Index l, Index v, Index s, Index b, Index p, Index r, Index c) const inline
Definition at line 1309 of file matpackVII.h.
References ConstTensor7View::operator()().
operator*=() [1/2]
Tensor7View & Tensor7View::operator*= (const ConstTensor7View & x)
Element-vise multiplication by another Tensor7.
Definition at line 5053 of file matpackVII.cc.
References ConstTensor7View::begin(), begin(), end(), ConstTensor7View::nbooks(), ConstTensor7View::ncols(), ConstTensor7View::nlibraries(), ConstTensor7View::npages(), ConstTensor7View::nrows(), ConstTensor7View::nshelves(), and ConstTensor7View::nvitrines().
operator*=() [2/2]
Tensor7View & Tensor7View::operator*= (Numeric x)
Multiplication by scalar.
Definition at line 5009 of file matpackVII.cc.
References begin(), and end().
operator+=() [1/2]
Tensor7View & Tensor7View::operator+= (const ConstTensor7View & x)
Element-vise addition of another Tensor7.
Definition at line 5093 of file matpackVII.cc.
References ConstTensor7View::begin(), begin(), end(), ConstTensor7View::nbooks(), ConstTensor7View::ncols(), ConstTensor7View::nlibraries(), ConstTensor7View::npages(), ConstTensor7View::nrows(), ConstTensor7View::nshelves(), and ConstTensor7View::nvitrines().
operator+=() [2/2]
Tensor7View & Tensor7View::operator+= (Numeric x)
Addition of scalar.
Definition at line 5031 of file matpackVII.cc.
References begin(), and end().
operator-=() [1/2]
Tensor7View & Tensor7View::operator-= (const ConstTensor7View & x)
Element-vise subtraction of another Tensor7.
Definition at line 5113 of file matpackVII.cc.
References ConstTensor7View::begin(), begin(), end(), ConstTensor7View::nbooks(), ConstTensor7View::ncols(), ConstTensor7View::nlibraries(), ConstTensor7View::npages(), ConstTensor7View::nrows(), ConstTensor7View::nshelves(), and ConstTensor7View::nvitrines().
operator-=() [2/2]
Tensor7View & Tensor7View::operator-= (Numeric x)
Subtraction of scalar.
Definition at line 5042 of file matpackVII.cc.
References begin(), and end().
operator/=() [1/2]
Tensor7View & Tensor7View::operator/= (const ConstTensor7View & x)
Element-vise division by another Tensor7.
Definition at line 5073 of file matpackVII.cc.
References ConstTensor7View::begin(), begin(), end(), ConstTensor7View::nbooks(), ConstTensor7View::ncols(), ConstTensor7View::nlibraries(), ConstTensor7View::npages(), ConstTensor7View::nrows(), ConstTensor7View::nshelves(), and ConstTensor7View::nvitrines().
operator/=() [2/2]
Tensor7View & Tensor7View::operator/= (Numeric x)
Division by scalar.
Definition at line 5020 of file matpackVII.cc.
References begin(), and end().
operator=() [1/4]
Tensor7View & Tensor7View::operator= (const ConstTensor7View & m)
Assignment operator.
This copies the data from another Tensor7View to this Tensor7View. Dimensions must agree! Resizing would destroy the selection that we might have done in this Tensor7View by setting its range.
Definition at line 4944 of file matpackVII.cc.
References ConstTensor7View::begin(), begin(), copy(), ConstTensor7View::end(), ConstTensor7View::mbr, ConstTensor7View::mcr, Range::mextent, ConstTensor7View::mlr, ConstTensor7View::mpr, ConstTensor7View::mrr, ConstTensor7View::msr, and ConstTensor7View::mvr.
operator=() [2/4]
Tensor7View & Tensor7View::operator= (const Tensor7 & m)
Assignment from a Tensor7.
This must exist to overide the automatically generated assignment operators, which don't copy the contents!
Definition at line 4982 of file matpackVII.cc.
References begin(), copy(), end(), ConstTensor7View::mbr, ConstTensor7View::mcr, Range::mextent, ConstTensor7View::mlr, ConstTensor7View::mpr, ConstTensor7View::mrr, ConstTensor7View::msr, and ConstTensor7View::mvr.
operator=() [3/4]
Tensor7View & Tensor7View::operator= (const Tensor7View & m)
Assignment from Tensor7View to Tensor7View.
This is a tricky one. The problem is that since Tensor7View is derived from ConstTensor7View, a default = operator is generated by the compiler, which does not do what we want. So we need this one to override the default.
Definition at line 4964 of file matpackVII.cc.
References begin(), copy(), end(), ConstTensor7View::mbr, ConstTensor7View::mcr, Range::mextent, ConstTensor7View::mlr, ConstTensor7View::mpr, ConstTensor7View::mrr, ConstTensor7View::msr, and ConstTensor7View::mvr.
operator=() [4/4]
Tensor7View & Tensor7View::operator= (Numeric x)
Assigning a scalar to a Tensor7View will set all elements to this value.
Definition at line 4999 of file matpackVII.cc.
References begin(), copy(), and end().
The documentation for this class was generated from the following files:
matpackVII.h
matpackVII.cc