ARTS: GriddedField6 Class Reference
GriddedField6 Class Reference
#include <gridded_fields.h>
Public Member Functions
GriddedField6 ()
Construct an empty GriddedField6.
GriddedField6 (const String &s)
Construct an empty GriddedField6 with the given name.
virtual bool checksize () const
Consistency check.
virtual void checksize_strict () const
Strict consistency check.
void resize (const GriddedField6 &gf)
Make this GriddedField6 the same size as the given one.
void resize (Index v, Index s, Index b, Index p, Index r, Index c)
Resize the data tensor.
Public Member Functions inherited from GriddedField
Index get_dim () const
Get the dimension of this gridded field.
void copy_grids (const GriddedField &gf)
Copy grids.
const String & get_grid_name (Index i) const
Get grid name.
Index get_grid_size (Index i) const
Get the size of a grid.
GridType get_grid_type (Index i) const
Get grid type.
ConstVectorView get_numeric_grid (Index i) const
Get a numeric grid.
VectorView get_numeric_grid (Index i)
Get a numeric grid.
const ArrayOfString & get_string_grid (Index i) const
Get a string grid.
ArrayOfString & get_string_grid (Index i)
Get a string grid.
const String & get_name () const
Get the name of this gridded field.
void set_grid (Index i, const Vector &g)
Set a numeric grid.
void set_grid (Index i, const ArrayOfString &g)
Set a string grid.
void set_grid_name (Index i, const String &s)
Set grid name.
void set_name (const String &s)
Set name of this gridded field.
virtual ~GriddedField ()
GriddedField virtual destructor.
Public Attributes
Tensor6 data
Friends
std::ostream & operator<< (std::ostream &os, const GriddedField6 &gf)
Additional Inherited Members
Protected Member Functions inherited from GriddedField
GriddedField ()
Construct an empty GriddedField.
GriddedField (const Index d, const String &s)
Construct a GriddedField.
Detailed Description
Definition at line 505 of file gridded_fields.h.
Constructor & Destructor Documentation
GriddedField6() [1/2]
GriddedField6::GriddedField6 () inline
Construct an empty GriddedField6.
Definition at line 508 of file gridded_fields.h.
GriddedField6() [2/2]
GriddedField6::GriddedField6 (const String & s) inline
Construct an empty GriddedField6 with the given name.
Parameters
[in] s Name.
Definition at line 511 of file gridded_fields.h.
Member Function Documentation
checksize()
virtual bool GriddedField6::checksize () const inline virtual
Consistency check.
Check if the sizes of the grids match the data dimension.
This function must be overwritten by the derived classes.
Returns
True if sizes match.
Implements GriddedField.
Definition at line 513 of file gridded_fields.h.
References data, GriddedField::get_grid_size(), ConstTensor6View::nbooks(), ConstTensor6View::ncols(), ConstTensor6View::npages(), ConstTensor6View::nrows(), ConstTensor6View::nshelves(), and ConstTensor6View::nvitrines().
Referenced by checksize_strict().
checksize_strict()
virtual void GriddedField6::checksize_strict () const inline virtual
Strict consistency check.
Same as GriddedField::checksize but throws runtime_error in case of error.
Implements GriddedField.
Definition at line 529 of file gridded_fields.h.
References CHECK_ERROR_BOILERPLATE, checksize(), data, GriddedField::get_grid_name(), GriddedField::get_grid_size(), GriddedField::get_name(), ConstTensor6View::nbooks(), ConstTensor6View::ncols(), ConstTensor6View::npages(), ConstTensor6View::nrows(), ConstTensor6View::nshelves(), and ConstTensor6View::nvitrines().
Referenced by surface_reflectivityFromGriddedField6().
resize() [1/2]
void GriddedField6::resize (const GriddedField6 & gf) inline
Make this GriddedField6 the same size as the given one.
Parameters
[in] gf Source gridded field.
Definition at line 552 of file gridded_fields.h.
References data, GriddedField::get_grid_size(), and Tensor6::resize().
resize() [2/2]
void GriddedField6::resize (Index v, Index s, Index b, Index p, Index r, Index c) inline
Resize the data tensor.
See also
Tensor6::resize
Definition at line 564 of file gridded_fields.h.
References data, and Tensor6::resize().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const GriddedField6 & gf) friend
Member Data Documentation
data
Tensor6 GriddedField6::data
Definition at line 571 of file gridded_fields.h.
Referenced by checksize(), checksize_strict(), resize(), and surface_reflectivityFromGriddedField6().
The documentation for this class was generated from the following file:
gridded_fields.h