ARTS: Tensor5View Class Reference
Tensor5View Class Reference
The Tensor5View class.
#include <matpackV.h>
Public Member Functions
ConstTensor5View operator() (const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
Const index operator for subrange.
ConstTensor4View operator() (const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
Const index operator returning an object of type ConstTensor4View.
ConstTensor4View operator() (const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
Const index operator returning an object of type ConstTensor4View.
ConstTensor4View operator() (const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor4View.
ConstTensor4View operator() (const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor4View.
ConstTensor4View operator() (Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor4View.
ConstTensor3View operator() (const Range &s, const Range &b, const Range &p, Index r, Index c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (const Range &s, const Range &b, Index p, const Range &r, Index c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (const Range &s, const Range &b, Index p, Index r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (const Range &s, Index b, const Range &p, Index r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (const Range &s, Index b, const Range &p, const Range &r, Index c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (const Range &s, Index b, Index p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (Index s, const Range &b, Index p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (Index s, const Range &b, const Range &p, Index r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (Index s, const Range &b, const Range &p, const Range &r, Index c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (Index s, Index b, const Range &p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstMatrixView operator() (const Range &s, const Range &b, Index p, Index r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (const Range &s, Index b, const Range &p, Index r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (const Range &s, Index b, Index p, const Range &r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (const Range &s, Index b, Index p, Index r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index s, const Range &b, Index p, Index r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index s, const Range &b, Index p, const Range &r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index s, const Range &b, const Range &p, Index r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index s, Index b, const Range &p, const Range &r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index s, Index b, const Range &p, Index r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index s, Index b, Index p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstVectorView operator() (const Range &s, Index b, Index p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index s, const Range &b, Index p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index s, Index b, const Range &p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index s, Index b, Index p, const Range &r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index s, Index b, Index p, Index r, const Range &c) const
Const index operator returning an object of type ConstVectorView.
Numeric operator() (Index s, Index b, Index p, Index r, Index c) const
Plain const index operator.
Numeric get (Index s, Index b, Index p, Index r, Index c) const
Get element implementation without assertions.
Tensor5View operator() (const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Index operator for subrange.
Tensor4View operator() (const Range &s, const Range &b, const Range &p, const Range &r, Index c)
Index operator returning an object of type Tensor4View.
Tensor4View operator() (const Range &s, const Range &b, const Range &p, Index r, const Range &c)
Index operator returning an object of type Tensor4View.
Tensor4View operator() (const Range &s, const Range &b, Index p, const Range &r, const Range &c)
Index operator returning an object of type Tensor4View.
Tensor4View operator() (const Range &s, Index b, const Range &p, const Range &r, const Range &c)
Index operator returning an object of type Tensor4View.
Tensor4View operator() (Index s, const Range &b, const Range &p, const Range &r, const Range &c)
Index operator returning an object of type Tensor4View.
Tensor3View operator() (const Range &s, const Range &b, const Range &p, Index r, Index c)
Index operator returning an object of type Tensor3View.
Tensor3View operator() (const Range &s, const Range &b, Index p, const Range &r, Index c)
Index operator returning an object of type Tensor3View.
Tensor3View operator() (const Range &s, const Range &b, Index p, Index r, const Range &c)
Index operator returning an object of type Tensor3View.
Tensor3View operator() (const Range &s, Index b, const Range &p, Index r, const Range &c)
Index operator returning an object of type Tensor3View.
Tensor3View operator() (const Range &s, Index b, const Range &p, const Range &r, Index c)
Index operator returning an object of type Tensor3View.
Tensor3View operator() (const Range &s, Index b, Index p, const Range &r, const Range &c)
Index operator returning an object of type Tensor3View.
Tensor3View operator() (Index s, const Range &b, Index p, const Range &r, const Range &c)
Index operator returning an object of type Tensor3View.
Tensor3View operator() (Index s, const Range &b, const Range &p, Index r, const Range &c)
Index operator returning an object of type Tensor3View.
Tensor3View operator() (Index s, const Range &b, const Range &p, const Range &r, Index c)
Index operator returning an object of type Tensor3View.
Tensor3View operator() (Index s, Index b, const Range &p, const Range &r, const Range &c)
Index operator returning an object of type Tensor3View.
MatrixView operator() (const Range &s, const Range &b, Index p, Index r, Index c)
Index operator returning an object of type MatrixView.
MatrixView operator() (const Range &s, Index b, const Range &p, Index r, Index c)
Index operator returning an object of type MatrixView.
MatrixView operator() (const Range &s, Index b, Index p, const Range &r, Index c)
Index operator returning an object of type MatrixView.
MatrixView operator() (const Range &s, Index b, Index p, Index r, const Range &c)
Index operator returning an object of type MatrixView.
MatrixView operator() (Index s, const Range &b, Index p, Index r, const Range &c)
Index operator returning an object of type MatrixView.
MatrixView operator() (Index s, const Range &b, Index p, const Range &r, Index c)
Index operator returning an object of type MatrixView.
MatrixView operator() (Index s, const Range &b, const Range &p, Index r, Index c)
Index operator returning an object of type MatrixView.
MatrixView operator() (Index s, Index b, const Range &p, const Range &r, Index c)
Index operator returning an object of type MatrixView.
MatrixView operator() (Index s, Index b, const Range &p, Index r, const Range &c)
Index operator returning an object of type MatrixView.
MatrixView operator() (Index s, Index b, Index p, const Range &r, const Range &c)
Index operator returning an object of type MatrixView.
VectorView operator() (const Range &s, Index b, Index p, Index r, Index c)
Index operator returning an object of type VectorView.
VectorView operator() (Index s, const Range &b, Index p, Index r, Index c)
Index operator returning an object of type VectorView.
VectorView operator() (Index s, Index b, const Range &p, Index r, Index c)
Index operator returning an object of type VectorView.
VectorView operator() (Index s, Index b, Index p, const Range &r, Index c)
Index operator returning an object of type VectorView.
VectorView operator() (Index s, Index b, Index p, Index r, const Range &c)
Const index operator returning an object of type ConstVectorView.
Numeric & operator() (Index s, Index b, Index p, Index r, Index c)
Plain const index operator.
Numeric & get (Index s, Index b, Index p, Index r, Index c)
Get element implementation without assertions.
const Numeric * get_c_array () const
Conversion to plain C-array.
Numeric * get_c_array ()
Conversion to plain C-array.
ConstIterator5D begin () const
Return const iterator to first shelf.
ConstIterator5D end () const
Return const iterator behind last shelf.
Iterator5D begin ()
Return iterator to first shelf.
Iterator5D end ()
Return iterator behind last shelf.
Tensor5View & operator= (const ConstTensor5View &v)
Assignment operator.
Tensor5View & operator= (const Tensor5View &v)
Assignment from Tensor5View to Tensor5View.
Tensor5View & operator= (const Tensor5 &v)
Assignment from a Tensor5.
Tensor5View & operator= (Numeric x)
Assigning a scalar to a Tensor5View will set all elements to this value.
Tensor5View & operator*= (Numeric x)
Multiplication by scalar.
Tensor5View & operator/= (Numeric x)
Division by scalar.
Tensor5View & operator+= (Numeric x)
Addition of scalar.
Tensor5View & operator-= (Numeric x)
Subtraction of scalar.
Tensor5View & operator*= (const ConstTensor5View &x)
Element-vise multiplication by another Tensor5.
Tensor5View & operator/= (const ConstTensor5View &x)
Element-vise division by another Tensor5.
Tensor5View & operator+= (const ConstTensor5View &x)
Element-vise addition of another Tensor5.
Tensor5View & operator-= (const ConstTensor5View &x)
Element-vise subtraction of another Tensor5.
virtual ~Tensor5View ()
Destructor.
Tensor5View (const Tensor4View &a)
Special constructor to make a Tensor5 view of a Tensor4.
Public Member Functions inherited from ConstTensor5View
Index nshelves () const
Returns the number of shelves.
Index nbooks () const
Returns the number of books.
Index npages () const
Returns the number of pages.
Index nrows () const
Returns the number of rows.
Index ncols () const
Returns the number of columns.
ConstTensor5View operator() (const Range &s, const Range &b, const Range &p, const Range &r, const Range &c) const
Const index operator for subrange.
ConstTensor4View operator() (const Range &s, const Range &b, const Range &p, const Range &r, Index c) const
Const index operator returning an object of type ConstTensor4View.
ConstTensor4View operator() (const Range &s, const Range &b, const Range &p, Index r, const Range &c) const
Const index operator returning an object of type ConstTensor4View.
ConstTensor4View operator() (const Range &s, const Range &b, Index p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor4View.
ConstTensor4View operator() (const Range &s, Index b, const Range &p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor4View.
ConstTensor4View operator() (Index s, const Range &b, const Range &p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor4View.
ConstTensor3View operator() (const Range &s, const Range &b, const Range &p, Index r, Index c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (const Range &s, const Range &b, Index p, const Range &r, Index c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (const Range &s, const Range &b, Index p, Index r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (const Range &s, Index b, const Range &p, Index r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (const Range &s, Index b, const Range &p, const Range &r, Index c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (const Range &s, Index b, Index p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (Index s, const Range &b, Index p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (Index s, const Range &b, const Range &p, Index r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (Index s, const Range &b, const Range &p, const Range &r, Index c) const
Const index operator returning an object of type ConstTensor3View.
ConstTensor3View operator() (Index s, Index b, const Range &p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstTensor3View.
ConstMatrixView operator() (const Range &s, const Range &b, Index p, Index r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (const Range &s, Index b, const Range &p, Index r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (const Range &s, Index b, Index p, const Range &r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (const Range &s, Index b, Index p, Index r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index s, const Range &b, Index p, Index r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index s, const Range &b, Index p, const Range &r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index s, const Range &b, const Range &p, Index r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index s, Index b, const Range &p, const Range &r, Index c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index s, Index b, const Range &p, Index r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstMatrixView operator() (Index s, Index b, Index p, const Range &r, const Range &c) const
Const index operator returning an object of type ConstMatrixView.
ConstVectorView operator() (const Range &s, Index b, Index p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index s, const Range &b, Index p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index s, Index b, const Range &p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index s, Index b, Index p, const Range &r, Index c) const
Const index operator returning an object of type ConstVectorView.
ConstVectorView operator() (Index s, Index b, Index p, Index r, const Range &c) const
Const index operator returning an object of type ConstVectorView.
Numeric operator() (Index s, Index b, Index p, Index r, Index c) const
Plain const index operator.
Numeric get (Index s, Index b, Index p, Index r, Index c) const
Get element implementation without assertions.
ConstIterator5D begin () const
Return const iterator to first shelf.
ConstIterator5D end () const
Return const iterator behind last shelf.
virtual ~ConstTensor5View ()
Destructor.
ConstTensor5View (const ConstTensor4View &a)
Special constructor to make a Tensor5 view of a Tensor4.
Protected Member Functions
Tensor5View ()
Default constructor.
Tensor5View (Numeric *data, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Explicit constructor.
Tensor5View (Numeric *data, const Range &ps, const Range &pb, const Range &pp, const Range &pr, const Range &pc, const Range &ns, const Range &nb, const Range &np, const Range &nr, const Range &nc)
Recursive constructor.
Protected Member Functions inherited from ConstTensor5View
ConstTensor5View ()
Default constructor.
ConstTensor5View (Numeric *data, const Range &s, const Range &b, const Range &p, const Range &r, const Range &c)
Explicit constructor.
ConstTensor5View (Numeric *data, const Range &ps, const Range &pb, const Range &pp, const Range &pr, const Range &pc, const Range &ns, const Range &nb, const Range &np, const Range &nr, const Range &nc)
Recursive constructor.
Friends
class Iterator6D
class Tensor6View
class Tensor7View
Additional Inherited Members
Protected Attributes inherited from ConstTensor5View
Range msr
The shelf range of mdata that is actually used.
Range mbr
The book range of mdata that is actually used.
Range mpr
The page range of mdata that is actually used.
Range mrr
The row range of mdata that is actually used.
Range mcr
The column range of mdata that is actually used.
Numeric * mdata
Pointer to the plain C array that holds the data.
Detailed Description
The Tensor5View class.
This contains the main implementation of a Tensor5. It defines the concepts of Tensor5View. Plus additionally the recursive subrange operator, which makes it possible to create a Tensor5View from a subrange of a Tensor5View.
The class Tensor5 is just a special case of a Tensor5View which also allocates storage.
Definition at line 276 of file matpackV.h.
Constructor & Destructor Documentation
~Tensor5View()
virtual Tensor5View::~Tensor5View () inline virtual
Destructor.
Definition at line 420 of file matpackV.h.
Tensor5View() [1/4]
Tensor5View::Tensor5View (const Tensor4View & a)
Special constructor to make a Tensor5 view of a Tensor4.
Definition at line 2213 of file matpackV.cc.
Tensor5View() [2/4]
Tensor5View::Tensor5View () protected
Default constructor.
This is necessary, so that we can have a default constructor for the derived class Tensor5.
Definition at line 2230 of file matpackV.cc.
Referenced by operator()().
Tensor5View() [3/4]
Tensor5View::Tensor5View (Numeric * data, const Range & sr, const Range & br, const Range & pr, const Range & rr, const Range & cr) protected
Explicit constructor.
This one is used by Tensor5 to initialize its own Tensor5View part. The row range rr must have a stride to account for the length of one row.
Definition at line 2239 of file matpackV.cc.
Tensor5View() [4/4]
Tensor5View::Tensor5View (Numeric * data, const Range & ps, const Range & pb, const Range & pp, const Range & pr, const Range & pc, const Range & ns, const Range & nb, const Range & np, const Range & nr, const Range & nc) protected
Recursive constructor.
This is used to construct SubMatrices from SubMatrices. That means that the new ranges have to be interpreted relative to the original ranges.
The new ranges may contain -1 for the extent which acts as a joker. However, the used Range constructor converts this to an explicit range, consistent with the original Range.
Parameters
*data The actual data.
ps Previous range.
pb Previous range.
pp Previous range.
pr Previous range.
pc Previous range.
ns New Range.
nb New Range.
np New Range.
nr New Range.
nc New Range.
Definition at line 2270 of file matpackV.cc.
Member Function Documentation
begin() [1/2]
Iterator5D Tensor5View::begin ()
Return iterator to first shelf.
Definition at line 2018 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
begin() [2/2]
ConstIterator5D Tensor5View::begin () const
Return const iterator to first shelf.
Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 2006 of file matpackV.cc.
References ConstTensor5View::begin().
Referenced by copy(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), Tensor5::operator=(), Tensor5::Tensor5(), and transform().
end() [1/2]
Iterator5D Tensor5View::end ()
Return iterator behind last shelf.
Definition at line 2026 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
end() [2/2]
ConstIterator5D Tensor5View::end () const
Return const iterator behind last shelf.
Definition at line 2012 of file matpackV.cc.
References ConstTensor5View::end().
Referenced by copy(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), Tensor5::operator=(), and Tensor5::Tensor5().
get() [1/2]
Numeric& Tensor5View::get (Index s, Index b, Index p, Index r, Index c) inline
Get element implementation without assertions.
Definition at line 381 of file matpackV.h.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
get() [2/2]
Numeric Tensor5View::get (Index s, Index b, Index p, Index r, Index c) const inline
Get element implementation without assertions.
Definition at line 322 of file matpackV.h.
References ConstTensor5View::get().
Referenced by interpweights(), and operator()().
get_c_array() [1/2]
Numeric * Tensor5View::get_c_array ()
Conversion to plain C-array.
This function returns a pointer to the raw data. It fails if the Tensor5View is not pointing to the beginning of a Tensor5 or the stride is not 1 because the caller expects to get a C array with continuous data.
Definition at line 760 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
get_c_array() [2/2]
const Numeric * Tensor5View::get_c_array () const
Conversion to plain C-array.
This function returns a pointer to the raw data. It fails if the Tensor5View is not pointing to the beginning of a Tensor5 or the stride is not 1 because the caller expects to get a C array with continuous data.
Definition at line 778 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
Referenced by nca_read_from_file(), nca_write_to_file(), and Reduce().
operator()() [1/64]
Tensor5View Tensor5View::operator() (const Range & s, const Range & b, const Range & p, const Range & r, const Range & c)
Index operator for subrange.
We have to also account for the case, that *this is already a subrange of a Tensor5. This allows correct recursive behavior.
Definition at line 1317 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, and Tensor5View().
operator()() [2/64]
ConstTensor5View Tensor5View::operator() (const Range & s, const Range & b, const Range & p, const Range & r, const Range & c) const
Const index operator for subrange.
We have to also account for the case, that *this is already a subrange of a Tensor5. This allows correct recursive behavior. Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 915 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [3/64]
Tensor4View Tensor5View::operator() (const Range & s, const Range & b, const Range & p, const Range & r, Index c)
Index operator returning an object of type Tensor4View.
(Reducing the dimension by one.)
Definition at line 1330 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [4/64]
ConstTensor4View Tensor5View::operator() (const Range & s, const Range & b, const Range & p, const Range & r, Index c) const
Const index operator returning an object of type ConstTensor4View.
(Reducing the dimension by one.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 928 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [5/64]
Tensor4View Tensor5View::operator() (const Range & s, const Range & b, const Range & p, Index r, const Range & c)
Index operator returning an object of type Tensor4View.
(Reducing the dimension by one.)
Definition at line 1348 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [6/64]
ConstTensor4View Tensor5View::operator() (const Range & s, const Range & b, const Range & p, Index r, const Range & c) const
Const index operator returning an object of type ConstTensor4View.
(Reducing the dimension by one.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 941 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [7/64]
Tensor3View Tensor5View::operator() (const Range & s, const Range & b, const Range & p, Index r, Index c)
Index operator returning an object of type Tensor3View.
(Reducing the dimension by two.)
Definition at line 1420 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [8/64]
ConstTensor3View Tensor5View::operator() (const Range & s, const Range & b, const Range & p, Index r, Index c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by two.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 993 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [9/64]
Tensor4View Tensor5View::operator() (const Range & s, const Range & b, Index p, const Range & r, const Range & c)
Index operator returning an object of type Tensor4View.
(Reducing the dimension by one.)
Definition at line 1366 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [10/64]
ConstTensor4View Tensor5View::operator() (const Range & s, const Range & b, Index p, const Range & r, const Range & c) const
Const index operator returning an object of type ConstTensor4View.
(Reducing the dimension by one.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 954 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [11/64]
Tensor3View Tensor5View::operator() (const Range & s, const Range & b, Index p, const Range & r, Index c)
Index operator returning an object of type Tensor3View.
(Reducing the dimension by two.)
Definition at line 1441 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [12/64]
ConstTensor3View Tensor5View::operator() (const Range & s, const Range & b, Index p, const Range & r, Index c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by two.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1006 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [13/64]
Tensor3View Tensor5View::operator() (const Range & s, const Range & b, Index p, Index r, const Range & c)
Index operator returning an object of type Tensor3View.
(Reducing the dimension by two.)
Definition at line 1462 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [14/64]
ConstTensor3View Tensor5View::operator() (const Range & s, const Range & b, Index p, Index r, const Range & c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by two.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1019 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [15/64]
MatrixView Tensor5View::operator() (const Range & s, const Range & b, Index p, Index r, Index c)
Index operator returning an object of type MatrixView.
(Reducing the dimension by three.)
Definition at line 1630 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [16/64]
ConstMatrixView Tensor5View::operator() (const Range & s, const Range & b, Index p, Index r, Index c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by three.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1123 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [17/64]
Tensor4View Tensor5View::operator() (const Range & s, Index b, const Range & p, const Range & r, const Range & c)
Index operator returning an object of type Tensor4View.
(Reducing the dimension by one.)
Definition at line 1384 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [18/64]
ConstTensor4View Tensor5View::operator() (const Range & s, Index b, const Range & p, const Range & r, const Range & c) const
Const index operator returning an object of type ConstTensor4View.
(Reducing the dimension by one.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 967 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [19/64]
Tensor3View Tensor5View::operator() (const Range & s, Index b, const Range & p, const Range & r, Index c)
Index operator returning an object of type Tensor3View.
(Reducing the dimension by two.)
Definition at line 1504 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [20/64]
ConstTensor3View Tensor5View::operator() (const Range & s, Index b, const Range & p, const Range & r, Index c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by two.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1045 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [21/64]
Tensor3View Tensor5View::operator() (const Range & s, Index b, const Range & p, Index r, const Range & c)
Index operator returning an object of type Tensor3View.
(Reducing the dimension by two.)
Definition at line 1483 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [22/64]
ConstTensor3View Tensor5View::operator() (const Range & s, Index b, const Range & p, Index r, const Range & c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by two.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1032 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [23/64]
MatrixView Tensor5View::operator() (const Range & s, Index b, const Range & p, Index r, Index c)
Index operator returning an object of type MatrixView.
(Reducing the dimension by three.)
Definition at line 1654 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [24/64]
ConstMatrixView Tensor5View::operator() (const Range & s, Index b, const Range & p, Index r, Index c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by three.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1136 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [25/64]
Tensor3View Tensor5View::operator() (const Range & s, Index b, Index p, const Range & r, const Range & c)
Index operator returning an object of type Tensor3View.
(Reducing the dimension by two.)
Definition at line 1525 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [26/64]
ConstTensor3View Tensor5View::operator() (const Range & s, Index b, Index p, const Range & r, const Range & c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by two.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1058 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [27/64]
MatrixView Tensor5View::operator() (const Range & s, Index b, Index p, const Range & r, Index c)
Index operator returning an object of type MatrixView.
(Reducing the dimension by three.)
Definition at line 1678 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [28/64]
ConstMatrixView Tensor5View::operator() (const Range & s, Index b, Index p, const Range & r, Index c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by three.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1149 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [29/64]
MatrixView Tensor5View::operator() (const Range & s, Index b, Index p, Index r, const Range & c)
Index operator returning an object of type MatrixView.
(Reducing the dimension by three.)
Definition at line 1702 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [30/64]
ConstMatrixView Tensor5View::operator() (const Range & s, Index b, Index p, Index r, const Range & c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by three.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1162 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [31/64]
VectorView Tensor5View::operator() (const Range & s, Index b, Index p, Index r, Index c)
Index operator returning an object of type VectorView.
(Reducing the dimension by four.)
Definition at line 1870 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [32/64]
ConstVectorView Tensor5View::operator() (const Range & s, Index b, Index p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
(Reducing the dimension by four.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1253 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [33/64]
Tensor4View Tensor5View::operator() (Index s, const Range & b, const Range & p, const Range & r, const Range & c)
Index operator returning an object of type Tensor4View.
(Reducing the dimension by one.)
Definition at line 1402 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [34/64]
ConstTensor4View Tensor5View::operator() (Index s, const Range & b, const Range & p, const Range & r, const Range & c) const
Const index operator returning an object of type ConstTensor4View.
(Reducing the dimension by one.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 980 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [35/64]
Tensor3View Tensor5View::operator() (Index s, const Range & b, const Range & p, const Range & r, Index c)
Index operator returning an object of type Tensor3View.
(Reducing the dimension by two.)
Definition at line 1588 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [36/64]
ConstTensor3View Tensor5View::operator() (Index s, const Range & b, const Range & p, const Range & r, Index c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by two.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1097 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [37/64]
Tensor3View Tensor5View::operator() (Index s, const Range & b, const Range & p, Index r, const Range & c)
Index operator returning an object of type Tensor3View.
(Reducing the dimension by two.)
Definition at line 1567 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [38/64]
ConstTensor3View Tensor5View::operator() (Index s, const Range & b, const Range & p, Index r, const Range & c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by two.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1084 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [39/64]
MatrixView Tensor5View::operator() (Index s, const Range & b, const Range & p, Index r, Index c)
Index operator returning an object of type MatrixView.
(Reducing the dimension by three.)
Definition at line 1774 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [40/64]
ConstMatrixView Tensor5View::operator() (Index s, const Range & b, const Range & p, Index r, Index c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by three.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1201 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [41/64]
Tensor3View Tensor5View::operator() (Index s, const Range & b, Index p, const Range & r, const Range & c)
Index operator returning an object of type Tensor3View.
(Reducing the dimension by two.)
Definition at line 1546 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [42/64]
ConstTensor3View Tensor5View::operator() (Index s, const Range & b, Index p, const Range & r, const Range & c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by two.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1071 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [43/64]
MatrixView Tensor5View::operator() (Index s, const Range & b, Index p, const Range & r, Index c)
Index operator returning an object of type MatrixView.
(Reducing the dimension by three.)
Definition at line 1750 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [44/64]
ConstMatrixView Tensor5View::operator() (Index s, const Range & b, Index p, const Range & r, Index c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by three.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1188 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [45/64]
MatrixView Tensor5View::operator() (Index s, const Range & b, Index p, Index r, const Range & c)
Index operator returning an object of type MatrixView.
(Reducing the dimension by three.)
Definition at line 1726 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [46/64]
ConstMatrixView Tensor5View::operator() (Index s, const Range & b, Index p, Index r, const Range & c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by three.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1175 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [47/64]
VectorView Tensor5View::operator() (Index s, const Range & b, Index p, Index r, Index c)
Index operator returning an object of type VectorView.
(Reducing the dimension by four.)
Definition at line 1897 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [48/64]
ConstVectorView Tensor5View::operator() (Index s, const Range & b, Index p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
(Reducing the dimension by four.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1266 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [49/64]
Tensor3View Tensor5View::operator() (Index s, Index b, const Range & p, const Range & r, const Range & c)
Index operator returning an object of type Tensor3View.
(Reducing the dimension by two.)
Definition at line 1609 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [50/64]
ConstTensor3View Tensor5View::operator() (Index s, Index b, const Range & p, const Range & r, const Range & c) const
Const index operator returning an object of type ConstTensor3View.
(Reducing the dimension by two.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1110 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [51/64]
MatrixView Tensor5View::operator() (Index s, Index b, const Range & p, const Range & r, Index c)
Index operator returning an object of type MatrixView.
(Reducing the dimension by three.)
Definition at line 1798 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [52/64]
ConstMatrixView Tensor5View::operator() (Index s, Index b, const Range & p, const Range & r, Index c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by three.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1214 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [53/64]
MatrixView Tensor5View::operator() (Index s, Index b, const Range & p, Index r, const Range & c)
Index operator returning an object of type MatrixView.
(Reducing the dimension by three.)
Definition at line 1822 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [54/64]
ConstMatrixView Tensor5View::operator() (Index s, Index b, const Range & p, Index r, const Range & c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by three.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1227 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [55/64]
VectorView Tensor5View::operator() (Index s, Index b, const Range & p, Index r, Index c)
Index operator returning an object of type VectorView.
(Reducing the dimension by four.)
Definition at line 1924 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [56/64]
ConstVectorView Tensor5View::operator() (Index s, Index b, const Range & p, Index r, Index c) const
Const index operator returning an object of type ConstVectorView.
(Reducing the dimension by four.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1279 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [57/64]
MatrixView Tensor5View::operator() (Index s, Index b, Index p, const Range & r, const Range & c)
Index operator returning an object of type MatrixView.
(Reducing the dimension by three.)
Definition at line 1846 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [58/64]
ConstMatrixView Tensor5View::operator() (Index s, Index b, Index p, const Range & r, const Range & c) const
Const index operator returning an object of type ConstMatrixView.
(Reducing the dimension by three.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1240 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [59/64]
VectorView Tensor5View::operator() (Index s, Index b, Index p, const Range & r, Index c)
Index operator returning an object of type VectorView.
(Reducing the dimension by four.)
Definition at line 1951 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [60/64]
ConstVectorView Tensor5View::operator() (Index s, Index b, Index p, const Range & r, Index c) const
Const index operator returning an object of type ConstVectorView.
(Reducing the dimension by four.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1292 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [61/64]
VectorView Tensor5View::operator() (Index s, Index b, Index p, Index r, const Range & c)
Const index operator returning an object of type ConstVectorView.
(Reducing the dimension by four.)
Definition at line 1978 of file matpackV.cc.
References ConstTensor5View::mbr, ConstTensor5View::mcr, ConstTensor5View::mdata, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, ConstTensor5View::msr, Range::mstart, and Range::mstride.
operator()() [62/64]
ConstVectorView Tensor5View::operator() (Index s, Index b, Index p, Index r, const Range & c) const
Const index operator returning an object of type ConstVectorView.
(Reducing the dimension by four.) Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 1305 of file matpackV.cc.
References ConstTensor5View::operator()().
operator()() [63/64]
Numeric& Tensor5View::operator() (Index s, Index b, Index p, Index r, Index c) inline
Plain const index operator.
Definition at line 364 of file matpackV.h.
References get(), ConstTensor5View::mbr, ConstTensor5View::mcr, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, and ConstTensor5View::msr.
operator()() [64/64]
Numeric Tensor5View::operator() (Index s, Index b, Index p, Index r, Index c) const inline
Plain const index operator.
Has to be redefined here, since it is hiden by the non-const operator of the derived class.
Definition at line 318 of file matpackV.h.
References ConstTensor5View::operator()().
operator*=() [1/2]
Tensor5View & Tensor5View::operator*= (const ConstTensor5View & x)
Element-vise multiplication by another Tensor5.
Definition at line 2141 of file matpackV.cc.
References ConstTensor5View::begin(), begin(), end(), ConstTensor5View::nbooks(), ConstTensor5View::ncols(), ConstTensor5View::npages(), ConstTensor5View::nrows(), and ConstTensor5View::nshelves().
operator*=() [2/2]
Tensor5View & Tensor5View::operator*= (Numeric x)
Multiplication by scalar.
Definition at line 2097 of file matpackV.cc.
References begin(), and end().
operator+=() [1/2]
Tensor5View & Tensor5View::operator+= (const ConstTensor5View & x)
Element-vise addition of another Tensor5.
Definition at line 2177 of file matpackV.cc.
References ConstTensor5View::begin(), begin(), end(), ConstTensor5View::nbooks(), ConstTensor5View::ncols(), ConstTensor5View::npages(), ConstTensor5View::nrows(), and ConstTensor5View::nshelves().
operator+=() [2/2]
Tensor5View & Tensor5View::operator+= (Numeric x)
Addition of scalar.
Definition at line 2119 of file matpackV.cc.
References begin(), and end().
operator-=() [1/2]
Tensor5View & Tensor5View::operator-= (const ConstTensor5View & x)
Element-vise subtraction of another Tensor5.
Definition at line 2195 of file matpackV.cc.
References ConstTensor5View::begin(), begin(), end(), ConstTensor5View::nbooks(), ConstTensor5View::ncols(), ConstTensor5View::npages(), ConstTensor5View::nrows(), and ConstTensor5View::nshelves().
operator-=() [2/2]
Tensor5View & Tensor5View::operator-= (Numeric x)
Subtraction of scalar.
Definition at line 2130 of file matpackV.cc.
References begin(), and end().
operator/=() [1/2]
Tensor5View & Tensor5View::operator/= (const ConstTensor5View & x)
Element-vise division by another Tensor5.
Definition at line 2159 of file matpackV.cc.
References ConstTensor5View::begin(), begin(), end(), ConstTensor5View::nbooks(), ConstTensor5View::ncols(), ConstTensor5View::npages(), ConstTensor5View::nrows(), and ConstTensor5View::nshelves().
operator/=() [2/2]
Tensor5View & Tensor5View::operator/= (Numeric x)
Division by scalar.
Definition at line 2108 of file matpackV.cc.
References begin(), and end().
operator=() [1/4]
Tensor5View & Tensor5View::operator= (const ConstTensor5View & m)
Assignment operator.
This copies the data from another Tensor5View to this Tensor5View. Dimensions must agree! Resizing would destroy the selection that we might have done in this Tensor5View by setting its range.
Definition at line 2038 of file matpackV.cc.
References ConstTensor5View::begin(), begin(), copy(), ConstTensor5View::end(), ConstTensor5View::mbr, ConstTensor5View::mcr, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, and ConstTensor5View::msr.
operator=() [2/4]
Tensor5View & Tensor5View::operator= (const Tensor5 & m)
Assignment from a Tensor5.
This must exist to overide the automatically generated assignment operators, which don't copy the contents!
Definition at line 2072 of file matpackV.cc.
References begin(), copy(), end(), ConstTensor5View::mbr, ConstTensor5View::mcr, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, and ConstTensor5View::msr.
operator=() [3/4]
Tensor5View & Tensor5View::operator= (const Tensor5View & m)
Assignment from Tensor5View to Tensor5View.
This is a tricky one. The problem is that since Tensor5View is derived from ConstTensor5View, a default = operator is generated by the compiler, which does not do what we want. So we need this one to override the default.
Definition at line 2056 of file matpackV.cc.
References begin(), copy(), end(), ConstTensor5View::mbr, ConstTensor5View::mcr, Range::mextent, ConstTensor5View::mpr, ConstTensor5View::mrr, and ConstTensor5View::msr.
operator=() [4/4]
Tensor5View & Tensor5View::operator= (Numeric x)
Assigning a scalar to a Tensor5View will set all elements to this value.
Definition at line 2087 of file matpackV.cc.
References begin(), copy(), and end().
Friends And Related Function Documentation
Iterator6D
friend class Iterator6D friend
Definition at line 426 of file matpackV.h.
Tensor6View
friend class Tensor6View friend
Definition at line 427 of file matpackV.h.
Tensor7View
friend class Tensor7View friend
Definition at line 428 of file matpackV.h.
The documentation for this class was generated from the following files:
matpackV.h
matpackV.cc