ARTS: MCAntenna Class Reference
MCAntenna Class Reference
An Antenna object used by MCGeneral.
#include <mc_antenna.h>
Public Member Functions
MCAntenna ()
void set_pencil_beam (void)
makes the antenna pattern a pencil beam
void set_gaussian (const Numeric &za_sigma, const Numeric &aa_sigma)
makes the antenna pattern a 2D gaussian specified by za and aa standard deviations
void set_gaussian_fwhm (const Numeric &za_fwhm, const Numeric &aa_fwhm)
makes the antenna pattern a 2D gaussian specified by za and aa FWHM
void set_lookup (ConstVectorView &za_grid, ConstVectorView &aa_grid, ConstMatrixView &G_lookup)
makes the antenna pattern use a 2D lookup table to define the antenna response
AntennaType get_type (void) const
returns the antenna type
void draw_los (VectorView &sampled_rte_los, Rng &rng, ConstVectorView bore_sight_los) const
draws a line of sight by sampling the antenna response function
Private Attributes
AntennaType atype
Numeric sigma_aa
Numeric sigma_za
Vector aa_grid
Vector za_grid
Matrix G_lookup
Detailed Description
An Antenna object used by MCGeneral.
This class provides the means of sampling various types of 2D antenna functions..
Definition at line 56 of file mc_antenna.h.
Constructor & Destructor Documentation
MCAntenna()
MCAntenna::MCAntenna () inline
Definition at line 63 of file mc_antenna.h.
Member Function Documentation
draw_los()
void MCAntenna::draw_los (VectorView & sampled_rte_los, Rng & rng, ConstVectorView bore_sight_los) const
draws a line of sight by sampling the antenna response function
Parameters
sampled_rte_los Output: The sampled line of sight
rng a random number generator
bore_sight_los the bore sight LOS
Author
Cory Davis
Date
2005-12-02
Definition at line 167 of file mc_antenna.cc.
References ANTENNA_TYPE_GAUSSIAN, ANTENNA_TYPE_PENCIL_BEAM, atype, ran_gaussian(), sigma_aa, and sigma_za.
Referenced by mc_IWP_cloud_opt_pathCalc(), MCGeneral(), and MCIPA().
get_type()
AntennaType MCAntenna::get_type (void) const
returns the antenna type
Author
Cory Davis
Date
2006-6-16
Definition at line 150 of file mc_antenna.cc.
References atype.
Referenced by mc_IWP_cloud_opt_pathCalc().
set_gaussian()
void MCAntenna::set_gaussian (const Numeric & za_sigma, const Numeric & aa_sigma)
makes the antenna pattern a 2D gaussian specified by za and aa standard deviations
Givees the MCAntenna object a 2D gaussian response function
Parameters
za_sigma The std. dev. parameter for zenith angle
aa_sigma The std. dev. parameter for azimuthal angle.
Author
Cory Davis
Date
2005-12-02
Definition at line 100 of file mc_antenna.cc.
References ANTENNA_TYPE_GAUSSIAN, atype, sigma_aa, and sigma_za.
Referenced by mc_antennaSetGaussian().
set_gaussian_fwhm()
void MCAntenna::set_gaussian_fwhm (const Numeric & za_fwhm, const Numeric & aa_fwhm)
makes the antenna pattern a 2D gaussian specified by za and aa FWHM
Givees the MCAntenna object a 2D gaussian response function
Parameters
za_fwhm The full width half maximum zenith angle
aa_fwhm The full width half maximum azimuthal angle.
Author
Cory Davis
Date
2005-12-02
Definition at line 116 of file mc_antenna.cc.
References ANTENNA_TYPE_GAUSSIAN, atype, sigma_aa, and sigma_za.
Referenced by mc_antennaSetGaussianByFWHM().
set_lookup()
void MCAntenna::set_lookup (ConstVectorView & za_grid_, ConstVectorView & aa_grid_, ConstMatrixView & G_lookup_)
makes the antenna pattern use a 2D lookup table to define the antenna response
The lookup antenna type is not yet implemented
Parameters
za_grid_ zenith angle grid for the antenna response lookup table
aa_grid_ azimuthal angle grid for the antenna response lookup table
G_lookup_ the lookup table data
Author
Cory Davis
Date
2005-12-02
Definition at line 134 of file mc_antenna.cc.
References aa_grid, ANTENNA_TYPE_LOOKUP, atype, G_lookup, and za_grid.
set_pencil_beam()
void MCAntenna::set_pencil_beam (void)
makes the antenna pattern a pencil beam
Definition at line 88 of file mc_antenna.cc.
References ANTENNA_TYPE_PENCIL_BEAM, and atype.
Referenced by iyMC(), and mc_antennaSetPencilBeam().
Member Data Documentation
aa_grid
Vector MCAntenna::aa_grid private
Definition at line 59 of file mc_antenna.h.
Referenced by set_lookup().
atype
AntennaType MCAntenna::atype private
Definition at line 57 of file mc_antenna.h.
Referenced by draw_los(), get_type(), set_gaussian(), set_gaussian_fwhm(), set_lookup(), and set_pencil_beam().
G_lookup
Matrix MCAntenna::G_lookup private
Definition at line 60 of file mc_antenna.h.
Referenced by set_lookup().
sigma_aa
Numeric MCAntenna::sigma_aa private
Definition at line 58 of file mc_antenna.h.
Referenced by draw_los(), set_gaussian(), and set_gaussian_fwhm().
sigma_za
Numeric MCAntenna::sigma_za private
Definition at line 58 of file mc_antenna.h.
Referenced by draw_los(), set_gaussian(), and set_gaussian_fwhm().
za_grid
Vector MCAntenna::za_grid private
Definition at line 59 of file mc_antenna.h.
Referenced by set_lookup().
The documentation for this class was generated from the following files:
mc_antenna.h
mc_antenna.cc