ARTS: MakeVector Class Reference
MakeVector Class Reference
#include <make_vector.h>
Public Member Functions
MakeVector ()
MakeVector (Numeric a0)
MakeVector (Numeric a0, Numeric a1)
MakeVector (Numeric a0, Numeric a1, Numeric a2)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19, Numeric a20)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19, Numeric a20, Numeric a21)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19, Numeric a20, Numeric a21, Numeric a22)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19, Numeric a20, Numeric a21, Numeric a22, Numeric a23)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19, Numeric a20, Numeric a21, Numeric a22, Numeric a23, Numeric a24)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19, Numeric a20, Numeric a21, Numeric a22, Numeric a23, Numeric a24, Numeric a25)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19, Numeric a20, Numeric a21, Numeric a22, Numeric a23, Numeric a24, Numeric a25, Numeric a26)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19, Numeric a20, Numeric a21, Numeric a22, Numeric a23, Numeric a24, Numeric a25, Numeric a26, Numeric a27)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19, Numeric a20, Numeric a21, Numeric a22, Numeric a23, Numeric a24, Numeric a25, Numeric a26, Numeric a27, Numeric a28)
MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19, Numeric a20, Numeric a21, Numeric a22, Numeric a23, Numeric a24, Numeric a25, Numeric a26, Numeric a27, Numeric a28, Numeric a29)
Public Member Functions inherited from Vector
Vector ()
Default constructor.
Vector (Index n)
Constructor setting size.
Vector (Index n, Numeric fill)
Constructor setting size and filling with constant value.
Vector (Numeric start, Index extent, Numeric stride)
Constructor filling with values.
Vector (const ConstVectorView &v)
Copy constructor from VectorView.
Vector (const Vector &v)
Copy constructor from Vector.
Vector (const std::vector< Numeric > &)
Converting constructor from std::vector<Numeric>.
Vector & operator= (Vector v)
Assignment from another Vector.
Vector & operator= (const Array< Numeric > &v)
Assignment operator from Array<Numeric>.
Vector & operator= (Numeric x)
Assignment operator from scalar.
void resize (Index n)
Resize function.
virtual ~Vector ()
Destructor for Vector.
Public Member Functions inherited from VectorView
VectorView (const Vector &)
Bail out immediately if somebody tries to create a VectorView from a const Vector.
VectorView (Vector &v)
Create VectorView from a Vector.
Numeric operator[] (Index n) const
Plain const index operator.
Numeric get (Index n) const
Get element implementation without assertions.
ConstVectorView operator[] (const Range &r) const
Const index operator for subrange.
Numeric & operator[] (Index n)
Plain Index operator.
Numeric & get (Index n)
Get element implementation without assertions.
VectorView operator[] (const Range &r)
Index operator for subrange.
ConstIterator1D begin () const
Return const iterator to first element.
ConstIterator1D end () const
Return const iterator behind last element.
Iterator1D begin ()
Return iterator to first element.
Iterator1D end ()
Return iterator behind last element.
VectorView & operator= (const ConstVectorView &v)
Assignment operator.
VectorView & operator= (const VectorView &v)
Assignment from VectorView to VectorView.
VectorView & operator= (const Vector &v)
Assignment from Vector.
VectorView & operator= (const Array< Numeric > &v)
Assignment operator from Array<Numeric>.
VectorView & operator= (Numeric x)
Assigning a scalar to a VectorView will set all elements to this value.
VectorView operator*= (Numeric x)
Multiplication by scalar.
VectorView operator/= (Numeric x)
Division by scalar.
VectorView operator+= (Numeric x)
Addition of scalar.
VectorView operator-= (Numeric x)
Subtraction of scalar.
VectorView operator*= (const ConstVectorView &x)
Element-vise multiplication by another vector.
VectorView operator/= (const ConstVectorView &x)
Element-vise division by another vector.
VectorView operator+= (const ConstVectorView &x)
Element-vise addition of another vector.
VectorView operator-= (const ConstVectorView &x)
Element-vise subtraction of another vector.
operator MatrixView ()
Conversion to 1 column matrix.
const Numeric * get_c_array () const
Conversion to plain C-array.
Numeric * get_c_array ()
Conversion to plain C-array.
virtual ~VectorView ()
Destructor.
VectorView (Numeric &a)
A special constructor, which allows to make a VectorView from a scalar.
Public Member Functions inherited from ConstVectorView
Index nelem () const
Returns the number of elements.
Numeric sum () const
The sum of all elements of a Vector.
Numeric operator[] (Index n) const
Plain const index operator.
Numeric get (Index n) const
Get element implementation without assertions.
ConstVectorView operator[] (const Range &r) const
Const index operator for subrange.
ConstIterator1D begin () const
Return const iterator to first element.
ConstIterator1D end () const
Return const iterator behind last element.
operator ConstMatrixView () const
Conversion to const 1 column matrix.
virtual ~ConstVectorView ()
Destructor.
ConstVectorView (const Numeric &a)
A special constructor, which allows to make a ConstVectorView from a scalar.
Additional Inherited Members
Public Types inherited from VectorView
typedef Iterator1D iterator
Public Types inherited from ConstVectorView
typedef ConstIterator1D const_iterator
Protected Member Functions inherited from VectorView
VectorView ()
Default constructor.
VectorView (Numeric *data, const Range &range)
Explicit constructor.
VectorView (Numeric *data, const Range &p, const Range &n)
Recursive constructor.
Protected Member Functions inherited from ConstVectorView
ConstVectorView ()
Default constructor.
ConstVectorView (Numeric *data, const Range &range)
Explicit constructor.
ConstVectorView (Numeric *data, const Range &p, const Range &n)
Recursive constructor.
Protected Attributes inherited from ConstVectorView
Range mrange
The range of mdata that is actually used.
Numeric * mdata
Pointer to the plain C array that holds the data.
Detailed Description
Definition at line 41 of file make_vector.h.
Constructor & Destructor Documentation
MakeVector() [1/31]
MakeVector::MakeVector ()
Definition at line 21 of file make_vector.cc.
MakeVector() [2/31]
MakeVector::MakeVector (Numeric a0)
Definition at line 26 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [3/31]
MakeVector::MakeVector (Numeric a0, Numeric a1)
Definition at line 33 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [4/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2)
Definition at line 42 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [5/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3)
Definition at line 53 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [6/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4)
Definition at line 66 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [7/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5)
Definition at line 81 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [8/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6)
Definition at line 98 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [9/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7)
Definition at line 117 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [10/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8)
Definition at line 138 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [11/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9)
Definition at line 161 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [12/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10)
Definition at line 186 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [13/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11)
Definition at line 213 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [14/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12)
Definition at line 242 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [15/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13)
Definition at line 273 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [16/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14)
Definition at line 306 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [17/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15)
Definition at line 341 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [18/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16)
Definition at line 378 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [19/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17)
Definition at line 417 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [20/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18)
Definition at line 458 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [21/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19)
Definition at line 501 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [22/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19, Numeric a20)
Definition at line 546 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [23/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19, Numeric a20, Numeric a21)
Definition at line 593 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [24/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19, Numeric a20, Numeric a21, Numeric a22)
Definition at line 642 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [25/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19, Numeric a20, Numeric a21, Numeric a22, Numeric a23)
Definition at line 693 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [26/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19, Numeric a20, Numeric a21, Numeric a22, Numeric a23, Numeric a24)
Definition at line 746 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [27/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19, Numeric a20, Numeric a21, Numeric a22, Numeric a23, Numeric a24, Numeric a25)
Definition at line 801 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [28/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19, Numeric a20, Numeric a21, Numeric a22, Numeric a23, Numeric a24, Numeric a25, Numeric a26)
Definition at line 858 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [29/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19, Numeric a20, Numeric a21, Numeric a22, Numeric a23, Numeric a24, Numeric a25, Numeric a26, Numeric a27)
Definition at line 917 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [30/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19, Numeric a20, Numeric a21, Numeric a22, Numeric a23, Numeric a24, Numeric a25, Numeric a26, Numeric a27, Numeric a28)
Definition at line 978 of file make_vector.cc.
References VectorView::operator[]().
MakeVector() [31/31]
MakeVector::MakeVector (Numeric a0, Numeric a1, Numeric a2, Numeric a3, Numeric a4, Numeric a5, Numeric a6, Numeric a7, Numeric a8, Numeric a9, Numeric a10, Numeric a11, Numeric a12, Numeric a13, Numeric a14, Numeric a15, Numeric a16, Numeric a17, Numeric a18, Numeric a19, Numeric a20, Numeric a21, Numeric a22, Numeric a23, Numeric a24, Numeric a25, Numeric a26, Numeric a27, Numeric a28, Numeric a29)
Definition at line 1041 of file make_vector.cc.
References VectorView::operator[]().
The documentation for this class was generated from the following files:
make_vector.h
make_vector.cc