ARTS: WorkspaceMemoryHandler Class Reference
WorkspaceMemoryHandler Class Reference
#include <auto_workspace.h>
Public Member Functions
WorkspaceMemoryHandler ()
Default constructor.
void * allocate (Index wsvg)
Getaway function to call the allocation function for the WSV group with the given Index.
void deallocate (Index wsvg, void *vp)
Getaway function to call the deallocation function for the WSV group with the given Index.
void * duplicate (Index wsvg, void *vp)
Getaway function to call the duplication function for the WSV group with the given Index.
Static Private Member Functions
static void * allocate_wsvg_Any ()
static void deallocate_wsvg_Any (void *vp)
static void * duplicate_wsvg_Any (void *vp)
static void * allocate_wsvg_Index ()
static void deallocate_wsvg_Index (void *vp)
static void * duplicate_wsvg_Index (void *vp)
static void * allocate_wsvg_Numeric ()
static void deallocate_wsvg_Numeric (void *vp)
static void * duplicate_wsvg_Numeric (void *vp)
static void * allocate_wsvg_String ()
static void deallocate_wsvg_String (void *vp)
static void * duplicate_wsvg_String (void *vp)
static void * allocate_wsvg_Vector ()
static void deallocate_wsvg_Vector (void *vp)
static void * duplicate_wsvg_Vector (void *vp)
static void * allocate_wsvg_Matrix ()
static void deallocate_wsvg_Matrix (void *vp)
static void * duplicate_wsvg_Matrix (void *vp)
static void * allocate_wsvg_Sparse ()
static void deallocate_wsvg_Sparse (void *vp)
static void * duplicate_wsvg_Sparse (void *vp)
static void * allocate_wsvg_Tensor3 ()
static void deallocate_wsvg_Tensor3 (void *vp)
static void * duplicate_wsvg_Tensor3 (void *vp)
static void * allocate_wsvg_Tensor4 ()
static void deallocate_wsvg_Tensor4 (void *vp)
static void * duplicate_wsvg_Tensor4 (void *vp)
static void * allocate_wsvg_Tensor5 ()
static void deallocate_wsvg_Tensor5 (void *vp)
static void * duplicate_wsvg_Tensor5 (void *vp)
static void * allocate_wsvg_Tensor6 ()
static void deallocate_wsvg_Tensor6 (void *vp)
static void * duplicate_wsvg_Tensor6 (void *vp)
static void * allocate_wsvg_Tensor7 ()
static void deallocate_wsvg_Tensor7 (void *vp)
static void * duplicate_wsvg_Tensor7 (void *vp)
static void * allocate_wsvg_Timer ()
static void deallocate_wsvg_Timer (void *vp)
static void * duplicate_wsvg_Timer (void *vp)
static void * allocate_wsvg_Verbosity ()
static void deallocate_wsvg_Verbosity (void *vp)
static void * duplicate_wsvg_Verbosity (void *vp)
static void * allocate_wsvg_ArrayOfIndex ()
static void deallocate_wsvg_ArrayOfIndex (void *vp)
static void * duplicate_wsvg_ArrayOfIndex (void *vp)
static void * allocate_wsvg_ArrayOfArrayOfIndex ()
static void deallocate_wsvg_ArrayOfArrayOfIndex (void *vp)
static void * duplicate_wsvg_ArrayOfArrayOfIndex (void *vp)
static void * allocate_wsvg_ArrayOfString ()
static void deallocate_wsvg_ArrayOfString (void *vp)
static void * duplicate_wsvg_ArrayOfString (void *vp)
static void * allocate_wsvg_ArrayOfVector ()
static void deallocate_wsvg_ArrayOfVector (void *vp)
static void * duplicate_wsvg_ArrayOfVector (void *vp)
static void * allocate_wsvg_ArrayOfArrayOfVector ()
static void deallocate_wsvg_ArrayOfArrayOfVector (void *vp)
static void * duplicate_wsvg_ArrayOfArrayOfVector (void *vp)
static void * allocate_wsvg_ArrayOfMatrix ()
static void deallocate_wsvg_ArrayOfMatrix (void *vp)
static void * duplicate_wsvg_ArrayOfMatrix (void *vp)
static void * allocate_wsvg_ArrayOfArrayOfMatrix ()
static void deallocate_wsvg_ArrayOfArrayOfMatrix (void *vp)
static void * duplicate_wsvg_ArrayOfArrayOfMatrix (void *vp)
static void * allocate_wsvg_ArrayOfSparse ()
static void deallocate_wsvg_ArrayOfSparse (void *vp)
static void * duplicate_wsvg_ArrayOfSparse (void *vp)
static void * allocate_wsvg_ArrayOfTensor3 ()
static void deallocate_wsvg_ArrayOfTensor3 (void *vp)
static void * duplicate_wsvg_ArrayOfTensor3 (void *vp)
static void * allocate_wsvg_ArrayOfArrayOfTensor3 ()
static void deallocate_wsvg_ArrayOfArrayOfTensor3 (void *vp)
static void * duplicate_wsvg_ArrayOfArrayOfTensor3 (void *vp)
static void * allocate_wsvg_ArrayOfTensor4 ()
static void deallocate_wsvg_ArrayOfTensor4 (void *vp)
static void * duplicate_wsvg_ArrayOfTensor4 (void *vp)
static void * allocate_wsvg_ArrayOfTensor6 ()
static void deallocate_wsvg_ArrayOfTensor6 (void *vp)
static void * duplicate_wsvg_ArrayOfTensor6 (void *vp)
static void * allocate_wsvg_ArrayOfTensor7 ()
static void deallocate_wsvg_ArrayOfTensor7 (void *vp)
static void * duplicate_wsvg_ArrayOfTensor7 (void *vp)
static void * allocate_wsvg_ArrayOfArrayOfTensor6 ()
static void deallocate_wsvg_ArrayOfArrayOfTensor6 (void *vp)
static void * duplicate_wsvg_ArrayOfArrayOfTensor6 (void *vp)
static void * allocate_wsvg_ArrayOfLineMixingRecord ()
static void deallocate_wsvg_ArrayOfLineMixingRecord (void *vp)
static void * duplicate_wsvg_ArrayOfLineMixingRecord (void *vp)
static void * allocate_wsvg_ArrayOfLineRecord ()
static void deallocate_wsvg_ArrayOfLineRecord (void *vp)
static void * duplicate_wsvg_ArrayOfLineRecord (void *vp)
static void * allocate_wsvg_ArrayOfArrayOfLineRecord ()
static void deallocate_wsvg_ArrayOfArrayOfLineRecord (void *vp)
static void * duplicate_wsvg_ArrayOfArrayOfLineRecord (void *vp)
static void * allocate_wsvg_ArrayOfLineshapeSpec ()
static void deallocate_wsvg_ArrayOfLineshapeSpec (void *vp)
static void * duplicate_wsvg_ArrayOfLineshapeSpec (void *vp)
static void * allocate_wsvg_ArrayOfArrayOfSpeciesTag ()
static void deallocate_wsvg_ArrayOfArrayOfSpeciesTag (void *vp)
static void * duplicate_wsvg_ArrayOfArrayOfSpeciesTag (void *vp)
static void * allocate_wsvg_Ppath ()
static void deallocate_wsvg_Ppath (void *vp)
static void * duplicate_wsvg_Ppath (void *vp)
static void * allocate_wsvg_Agenda ()
static void deallocate_wsvg_Agenda (void *vp)
static void * duplicate_wsvg_Agenda (void *vp)
static void * allocate_wsvg_GridPos ()
static void deallocate_wsvg_GridPos (void *vp)
static void * duplicate_wsvg_GridPos (void *vp)
static void * allocate_wsvg_GasAbsLookup ()
static void deallocate_wsvg_GasAbsLookup (void *vp)
static void * duplicate_wsvg_GasAbsLookup (void *vp)
static void * allocate_wsvg_SingleScatteringData ()
static void deallocate_wsvg_SingleScatteringData (void *vp)
static void * duplicate_wsvg_SingleScatteringData (void *vp)
static void * allocate_wsvg_ArrayOfSingleScatteringData ()
static void deallocate_wsvg_ArrayOfSingleScatteringData (void *vp)
static void * duplicate_wsvg_ArrayOfSingleScatteringData (void *vp)
static void * allocate_wsvg_ScatteringMetaData ()
static void deallocate_wsvg_ScatteringMetaData (void *vp)
static void * duplicate_wsvg_ScatteringMetaData (void *vp)
static void * allocate_wsvg_ArrayOfScatteringMetaData ()
static void deallocate_wsvg_ArrayOfScatteringMetaData (void *vp)
static void * duplicate_wsvg_ArrayOfScatteringMetaData (void *vp)
static void * allocate_wsvg_GriddedField1 ()
static void deallocate_wsvg_GriddedField1 (void *vp)
static void * duplicate_wsvg_GriddedField1 (void *vp)
static void * allocate_wsvg_GriddedField2 ()
static void deallocate_wsvg_GriddedField2 (void *vp)
static void * duplicate_wsvg_GriddedField2 (void *vp)
static void * allocate_wsvg_GriddedField3 ()
static void deallocate_wsvg_GriddedField3 (void *vp)
static void * duplicate_wsvg_GriddedField3 (void *vp)
static void * allocate_wsvg_GriddedField4 ()
static void deallocate_wsvg_GriddedField4 (void *vp)
static void * duplicate_wsvg_GriddedField4 (void *vp)
static void * allocate_wsvg_GriddedField5 ()
static void deallocate_wsvg_GriddedField5 (void *vp)
static void * duplicate_wsvg_GriddedField5 (void *vp)
static void * allocate_wsvg_GriddedField6 ()
static void deallocate_wsvg_GriddedField6 (void *vp)
static void * duplicate_wsvg_GriddedField6 (void *vp)
static void * allocate_wsvg_ArrayOfGriddedField1 ()
static void deallocate_wsvg_ArrayOfGriddedField1 (void *vp)
static void * duplicate_wsvg_ArrayOfGriddedField1 (void *vp)
static void * allocate_wsvg_ArrayOfGriddedField2 ()
static void deallocate_wsvg_ArrayOfGriddedField2 (void *vp)
static void * duplicate_wsvg_ArrayOfGriddedField2 (void *vp)
static void * allocate_wsvg_ArrayOfGriddedField3 ()
static void deallocate_wsvg_ArrayOfGriddedField3 (void *vp)
static void * duplicate_wsvg_ArrayOfGriddedField3 (void *vp)
static void * allocate_wsvg_ArrayOfGriddedField4 ()
static void deallocate_wsvg_ArrayOfGriddedField4 (void *vp)
static void * duplicate_wsvg_ArrayOfGriddedField4 (void *vp)
static void * allocate_wsvg_ArrayOfArrayOfGriddedField1 ()
static void deallocate_wsvg_ArrayOfArrayOfGriddedField1 (void *vp)
static void * duplicate_wsvg_ArrayOfArrayOfGriddedField1 (void *vp)
static void * allocate_wsvg_ArrayOfArrayOfGriddedField2 ()
static void deallocate_wsvg_ArrayOfArrayOfGriddedField2 (void *vp)
static void * duplicate_wsvg_ArrayOfArrayOfGriddedField2 (void *vp)
static void * allocate_wsvg_ArrayOfArrayOfGriddedField3 ()
static void deallocate_wsvg_ArrayOfArrayOfGriddedField3 (void *vp)
static void * duplicate_wsvg_ArrayOfArrayOfGriddedField3 (void *vp)
static void * allocate_wsvg_ArrayOfArrayOfLineMixingRecord ()
static void deallocate_wsvg_ArrayOfArrayOfLineMixingRecord (void *vp)
static void * duplicate_wsvg_ArrayOfArrayOfLineMixingRecord (void *vp)
static void * allocate_wsvg_ArrayOfRetrievalQuantity ()
static void deallocate_wsvg_ArrayOfRetrievalQuantity (void *vp)
static void * duplicate_wsvg_ArrayOfRetrievalQuantity (void *vp)
static void * allocate_wsvg_MCAntenna ()
static void deallocate_wsvg_MCAntenna (void *vp)
static void * duplicate_wsvg_MCAntenna (void *vp)
static void * allocate_wsvg_SpeciesAuxData ()
static void deallocate_wsvg_SpeciesAuxData (void *vp)
static void * duplicate_wsvg_SpeciesAuxData (void *vp)
static void * allocate_wsvg_ArrayOfCIARecord ()
static void deallocate_wsvg_ArrayOfCIARecord (void *vp)
static void * duplicate_wsvg_ArrayOfCIARecord (void *vp)
Private Attributes
void *(* allocfp [59])()
void(* deallocfp [59])(void *)
void *(* duplicatefp [59])(void *)
Detailed Description
Definition at line 31 of file auto_workspace.h.
Constructor & Destructor Documentation
WorkspaceMemoryHandler()
WorkspaceMemoryHandler::WorkspaceMemoryHandler () inline
Default constructor.
Initialize allocation and deallocation function pointer lists.
Definition at line 577 of file auto_workspace.h.
References allocate_wsvg_Agenda(), allocate_wsvg_Any(), allocate_wsvg_ArrayOfArrayOfGriddedField1(), allocate_wsvg_ArrayOfArrayOfGriddedField2(), allocate_wsvg_ArrayOfArrayOfGriddedField3(), allocate_wsvg_ArrayOfArrayOfIndex(), allocate_wsvg_ArrayOfArrayOfLineMixingRecord(), allocate_wsvg_ArrayOfArrayOfLineRecord(), allocate_wsvg_ArrayOfArrayOfMatrix(), allocate_wsvg_ArrayOfArrayOfSpeciesTag(), allocate_wsvg_ArrayOfArrayOfTensor3(), allocate_wsvg_ArrayOfArrayOfTensor6(), allocate_wsvg_ArrayOfArrayOfVector(), allocate_wsvg_ArrayOfCIARecord(), allocate_wsvg_ArrayOfGriddedField1(), allocate_wsvg_ArrayOfGriddedField2(), allocate_wsvg_ArrayOfGriddedField3(), allocate_wsvg_ArrayOfGriddedField4(), allocate_wsvg_ArrayOfIndex(), allocate_wsvg_ArrayOfLineMixingRecord(), allocate_wsvg_ArrayOfLineRecord(), allocate_wsvg_ArrayOfLineshapeSpec(), allocate_wsvg_ArrayOfMatrix(), allocate_wsvg_ArrayOfRetrievalQuantity(), allocate_wsvg_ArrayOfScatteringMetaData(), allocate_wsvg_ArrayOfSingleScatteringData(), allocate_wsvg_ArrayOfSparse(), allocate_wsvg_ArrayOfString(), allocate_wsvg_ArrayOfTensor3(), allocate_wsvg_ArrayOfTensor4(), allocate_wsvg_ArrayOfTensor6(), allocate_wsvg_ArrayOfTensor7(), allocate_wsvg_ArrayOfVector(), allocate_wsvg_GasAbsLookup(), allocate_wsvg_GriddedField1(), allocate_wsvg_GriddedField2(), allocate_wsvg_GriddedField3(), allocate_wsvg_GriddedField4(), allocate_wsvg_GriddedField5(), allocate_wsvg_GriddedField6(), allocate_wsvg_GridPos(), allocate_wsvg_Index(), allocate_wsvg_Matrix(), allocate_wsvg_MCAntenna(), allocate_wsvg_Numeric(), allocate_wsvg_Ppath(), allocate_wsvg_ScatteringMetaData(), allocate_wsvg_SingleScatteringData(), allocate_wsvg_Sparse(), allocate_wsvg_SpeciesAuxData(), allocate_wsvg_String(), allocate_wsvg_Tensor3(), allocate_wsvg_Tensor4(), allocate_wsvg_Tensor5(), allocate_wsvg_Tensor6(), allocate_wsvg_Tensor7(), allocate_wsvg_Timer(), allocate_wsvg_Vector(), allocate_wsvg_Verbosity(), allocfp, deallocate_wsvg_Agenda(), deallocate_wsvg_Any(), deallocate_wsvg_ArrayOfArrayOfGriddedField1(), deallocate_wsvg_ArrayOfArrayOfGriddedField2(), deallocate_wsvg_ArrayOfArrayOfGriddedField3(), deallocate_wsvg_ArrayOfArrayOfIndex(), deallocate_wsvg_ArrayOfArrayOfLineMixingRecord(), deallocate_wsvg_ArrayOfArrayOfLineRecord(), deallocate_wsvg_ArrayOfArrayOfMatrix(), deallocate_wsvg_ArrayOfArrayOfSpeciesTag(), deallocate_wsvg_ArrayOfArrayOfTensor3(), deallocate_wsvg_ArrayOfArrayOfTensor6(), deallocate_wsvg_ArrayOfArrayOfVector(), deallocate_wsvg_ArrayOfCIARecord(), deallocate_wsvg_ArrayOfGriddedField1(), deallocate_wsvg_ArrayOfGriddedField2(), deallocate_wsvg_ArrayOfGriddedField3(), deallocate_wsvg_ArrayOfGriddedField4(), deallocate_wsvg_ArrayOfIndex(), deallocate_wsvg_ArrayOfLineMixingRecord(), deallocate_wsvg_ArrayOfLineRecord(), deallocate_wsvg_ArrayOfLineshapeSpec(), deallocate_wsvg_ArrayOfMatrix(), deallocate_wsvg_ArrayOfRetrievalQuantity(), deallocate_wsvg_ArrayOfScatteringMetaData(), deallocate_wsvg_ArrayOfSingleScatteringData(), deallocate_wsvg_ArrayOfSparse(), deallocate_wsvg_ArrayOfString(), deallocate_wsvg_ArrayOfTensor3(), deallocate_wsvg_ArrayOfTensor4(), deallocate_wsvg_ArrayOfTensor6(), deallocate_wsvg_ArrayOfTensor7(), deallocate_wsvg_ArrayOfVector(), deallocate_wsvg_GasAbsLookup(), deallocate_wsvg_GriddedField1(), deallocate_wsvg_GriddedField2(), deallocate_wsvg_GriddedField3(), deallocate_wsvg_GriddedField4(), deallocate_wsvg_GriddedField5(), deallocate_wsvg_GriddedField6(), deallocate_wsvg_GridPos(), deallocate_wsvg_Index(), deallocate_wsvg_Matrix(), deallocate_wsvg_MCAntenna(), deallocate_wsvg_Numeric(), deallocate_wsvg_Ppath(), deallocate_wsvg_ScatteringMetaData(), deallocate_wsvg_SingleScatteringData(), deallocate_wsvg_Sparse(), deallocate_wsvg_SpeciesAuxData(), deallocate_wsvg_String(), deallocate_wsvg_Tensor3(), deallocate_wsvg_Tensor4(), deallocate_wsvg_Tensor5(), deallocate_wsvg_Tensor6(), deallocate_wsvg_Tensor7(), deallocate_wsvg_Timer(), deallocate_wsvg_Vector(), deallocate_wsvg_Verbosity(), deallocfp, duplicate_wsvg_Agenda(), duplicate_wsvg_Any(), duplicate_wsvg_ArrayOfArrayOfGriddedField1(), duplicate_wsvg_ArrayOfArrayOfGriddedField2(), duplicate_wsvg_ArrayOfArrayOfGriddedField3(), duplicate_wsvg_ArrayOfArrayOfIndex(), duplicate_wsvg_ArrayOfArrayOfLineMixingRecord(), duplicate_wsvg_ArrayOfArrayOfLineRecord(), duplicate_wsvg_ArrayOfArrayOfMatrix(), duplicate_wsvg_ArrayOfArrayOfSpeciesTag(), duplicate_wsvg_ArrayOfArrayOfTensor3(), duplicate_wsvg_ArrayOfArrayOfTensor6(), duplicate_wsvg_ArrayOfArrayOfVector(), duplicate_wsvg_ArrayOfCIARecord(), duplicate_wsvg_ArrayOfGriddedField1(), duplicate_wsvg_ArrayOfGriddedField2(), duplicate_wsvg_ArrayOfGriddedField3(), duplicate_wsvg_ArrayOfGriddedField4(), duplicate_wsvg_ArrayOfIndex(), duplicate_wsvg_ArrayOfLineMixingRecord(), duplicate_wsvg_ArrayOfLineRecord(), duplicate_wsvg_ArrayOfLineshapeSpec(), duplicate_wsvg_ArrayOfMatrix(), duplicate_wsvg_ArrayOfRetrievalQuantity(), duplicate_wsvg_ArrayOfScatteringMetaData(), duplicate_wsvg_ArrayOfSingleScatteringData(), duplicate_wsvg_ArrayOfSparse(), duplicate_wsvg_ArrayOfString(), duplicate_wsvg_ArrayOfTensor3(), duplicate_wsvg_ArrayOfTensor4(), duplicate_wsvg_ArrayOfTensor6(), duplicate_wsvg_ArrayOfTensor7(), duplicate_wsvg_ArrayOfVector(), duplicate_wsvg_GasAbsLookup(), duplicate_wsvg_GriddedField1(), duplicate_wsvg_GriddedField2(), duplicate_wsvg_GriddedField3(), duplicate_wsvg_GriddedField4(), duplicate_wsvg_GriddedField5(), duplicate_wsvg_GriddedField6(), duplicate_wsvg_GridPos(), duplicate_wsvg_Index(), duplicate_wsvg_Matrix(), duplicate_wsvg_MCAntenna(), duplicate_wsvg_Numeric(), duplicate_wsvg_Ppath(), duplicate_wsvg_ScatteringMetaData(), duplicate_wsvg_SingleScatteringData(), duplicate_wsvg_Sparse(), duplicate_wsvg_SpeciesAuxData(), duplicate_wsvg_String(), duplicate_wsvg_Tensor3(), duplicate_wsvg_Tensor4(), duplicate_wsvg_Tensor5(), duplicate_wsvg_Tensor6(), duplicate_wsvg_Tensor7(), duplicate_wsvg_Timer(), duplicate_wsvg_Vector(), duplicate_wsvg_Verbosity(), and duplicatefp.
Member Function Documentation
allocate()
void* WorkspaceMemoryHandler::allocate (Index wsvg) inline
Getaway function to call the allocation function for the WSV group with the given Index.
Definition at line 761 of file auto_workspace.h.
References allocfp.
Referenced by Workspace::operator[]().
allocate_wsvg_Agenda()
static void* WorkspaceMemoryHandler::allocate_wsvg_Agenda () inline static private
Definition at line 348 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Any()
static void* WorkspaceMemoryHandler::allocate_wsvg_Any () inline static private
Definition at line 42 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfArrayOfGriddedField1()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfArrayOfGriddedField1 () inline static private
Definition at line 501 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfArrayOfGriddedField2()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfArrayOfGriddedField2 () inline static private
Definition at line 510 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfArrayOfGriddedField3()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfArrayOfGriddedField3 () inline static private
Definition at line 519 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfArrayOfIndex()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfArrayOfIndex () inline static private
Definition at line 177 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfArrayOfLineMixingRecord()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfArrayOfLineMixingRecord () inline static private
Definition at line 528 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfArrayOfLineRecord()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfArrayOfLineRecord () inline static private
Definition at line 312 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfArrayOfMatrix()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfArrayOfMatrix () inline static private
Definition at line 222 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfArrayOfSpeciesTag()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfArrayOfSpeciesTag () inline static private
Definition at line 330 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfArrayOfTensor3()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfArrayOfTensor3 () inline static private
Definition at line 249 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfArrayOfTensor6()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfArrayOfTensor6 () inline static private
Definition at line 285 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfArrayOfVector()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfArrayOfVector () inline static private
Definition at line 204 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfCIARecord()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfCIARecord () inline static private
Definition at line 564 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfGriddedField1()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfGriddedField1 () inline static private
Definition at line 465 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfGriddedField2()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfGriddedField2 () inline static private
Definition at line 474 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfGriddedField3()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfGriddedField3 () inline static private
Definition at line 483 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfGriddedField4()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfGriddedField4 () inline static private
Definition at line 492 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfIndex()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfIndex () inline static private
Definition at line 168 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfLineMixingRecord()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfLineMixingRecord () inline static private
Definition at line 294 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfLineRecord()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfLineRecord () inline static private
Definition at line 303 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfLineshapeSpec()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfLineshapeSpec () inline static private
Definition at line 321 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfMatrix()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfMatrix () inline static private
Definition at line 213 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfRetrievalQuantity()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfRetrievalQuantity () inline static private
Definition at line 537 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfScatteringMetaData()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfScatteringMetaData () inline static private
Definition at line 402 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfSingleScatteringData()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfSingleScatteringData () inline static private
Definition at line 384 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfSparse()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfSparse () inline static private
Definition at line 231 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfString()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfString () inline static private
Definition at line 186 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfTensor3()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfTensor3 () inline static private
Definition at line 240 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfTensor4()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfTensor4 () inline static private
Definition at line 258 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfTensor6()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfTensor6 () inline static private
Definition at line 267 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfTensor7()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfTensor7 () inline static private
Definition at line 276 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfVector()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfVector () inline static private
Definition at line 195 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_GasAbsLookup()
static void* WorkspaceMemoryHandler::allocate_wsvg_GasAbsLookup () inline static private
Definition at line 366 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_GriddedField1()
static void* WorkspaceMemoryHandler::allocate_wsvg_GriddedField1 () inline static private
Definition at line 411 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_GriddedField2()
static void* WorkspaceMemoryHandler::allocate_wsvg_GriddedField2 () inline static private
Definition at line 420 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_GriddedField3()
static void* WorkspaceMemoryHandler::allocate_wsvg_GriddedField3 () inline static private
Definition at line 429 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_GriddedField4()
static void* WorkspaceMemoryHandler::allocate_wsvg_GriddedField4 () inline static private
Definition at line 438 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_GriddedField5()
static void* WorkspaceMemoryHandler::allocate_wsvg_GriddedField5 () inline static private
Definition at line 447 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_GriddedField6()
static void* WorkspaceMemoryHandler::allocate_wsvg_GriddedField6 () inline static private
Definition at line 456 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_GridPos()
static void* WorkspaceMemoryHandler::allocate_wsvg_GridPos () inline static private
Definition at line 357 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Index()
static void* WorkspaceMemoryHandler::allocate_wsvg_Index () inline static private
Definition at line 51 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Matrix()
static void* WorkspaceMemoryHandler::allocate_wsvg_Matrix () inline static private
Definition at line 87 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_MCAntenna()
static void* WorkspaceMemoryHandler::allocate_wsvg_MCAntenna () inline static private
Definition at line 546 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Numeric()
static void* WorkspaceMemoryHandler::allocate_wsvg_Numeric () inline static private
Definition at line 60 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Ppath()
static void* WorkspaceMemoryHandler::allocate_wsvg_Ppath () inline static private
Definition at line 339 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ScatteringMetaData()
static void* WorkspaceMemoryHandler::allocate_wsvg_ScatteringMetaData () inline static private
Definition at line 393 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_SingleScatteringData()
static void* WorkspaceMemoryHandler::allocate_wsvg_SingleScatteringData () inline static private
Definition at line 375 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Sparse()
static void* WorkspaceMemoryHandler::allocate_wsvg_Sparse () inline static private
Definition at line 96 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_SpeciesAuxData()
static void* WorkspaceMemoryHandler::allocate_wsvg_SpeciesAuxData () inline static private
Definition at line 555 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_String()
static void* WorkspaceMemoryHandler::allocate_wsvg_String () inline static private
Definition at line 69 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Tensor3()
static void* WorkspaceMemoryHandler::allocate_wsvg_Tensor3 () inline static private
Definition at line 105 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Tensor4()
static void* WorkspaceMemoryHandler::allocate_wsvg_Tensor4 () inline static private
Definition at line 114 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Tensor5()
static void* WorkspaceMemoryHandler::allocate_wsvg_Tensor5 () inline static private
Definition at line 123 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Tensor6()
static void* WorkspaceMemoryHandler::allocate_wsvg_Tensor6 () inline static private
Definition at line 132 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Tensor7()
static void* WorkspaceMemoryHandler::allocate_wsvg_Tensor7 () inline static private
Definition at line 141 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Timer()
static void* WorkspaceMemoryHandler::allocate_wsvg_Timer () inline static private
Definition at line 150 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Vector()
static void* WorkspaceMemoryHandler::allocate_wsvg_Vector () inline static private
Definition at line 78 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Verbosity()
static void* WorkspaceMemoryHandler::allocate_wsvg_Verbosity () inline static private
Definition at line 159 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate()
void WorkspaceMemoryHandler::deallocate (Index wsvg, void * vp) inline
Getaway function to call the deallocation function for the WSV group with the given Index.
Definition at line 769 of file auto_workspace.h.
References deallocfp.
Referenced by Workspace::del(), Workspace::pop_free(), and Workspace::~Workspace().
deallocate_wsvg_Agenda()
static void WorkspaceMemoryHandler::deallocate_wsvg_Agenda (void * vp) inline static private
Definition at line 351 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Any()
static void WorkspaceMemoryHandler::deallocate_wsvg_Any (void * vp) inline static private
Definition at line 45 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfArrayOfGriddedField1()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfArrayOfGriddedField1 (void * vp) inline static private
Definition at line 504 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfArrayOfGriddedField2()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfArrayOfGriddedField2 (void * vp) inline static private
Definition at line 513 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfArrayOfGriddedField3()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfArrayOfGriddedField3 (void * vp) inline static private
Definition at line 522 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfArrayOfIndex()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfArrayOfIndex (void * vp) inline static private
Definition at line 180 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfArrayOfLineMixingRecord()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfArrayOfLineMixingRecord (void * vp) inline static private
Definition at line 531 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfArrayOfLineRecord()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfArrayOfLineRecord (void * vp) inline static private
Definition at line 315 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfArrayOfMatrix()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfArrayOfMatrix (void * vp) inline static private
Definition at line 225 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfArrayOfSpeciesTag()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfArrayOfSpeciesTag (void * vp) inline static private
Definition at line 333 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfArrayOfTensor3()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfArrayOfTensor3 (void * vp) inline static private
Definition at line 252 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfArrayOfTensor6()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfArrayOfTensor6 (void * vp) inline static private
Definition at line 288 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfArrayOfVector()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfArrayOfVector (void * vp) inline static private
Definition at line 207 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfCIARecord()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfCIARecord (void * vp) inline static private
Definition at line 567 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfGriddedField1()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfGriddedField1 (void * vp) inline static private
Definition at line 468 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfGriddedField2()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfGriddedField2 (void * vp) inline static private
Definition at line 477 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfGriddedField3()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfGriddedField3 (void * vp) inline static private
Definition at line 486 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfGriddedField4()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfGriddedField4 (void * vp) inline static private
Definition at line 495 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfIndex()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfIndex (void * vp) inline static private
Definition at line 171 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfLineMixingRecord()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfLineMixingRecord (void * vp) inline static private
Definition at line 297 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfLineRecord()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfLineRecord (void * vp) inline static private
Definition at line 306 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfLineshapeSpec()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfLineshapeSpec (void * vp) inline static private
Definition at line 324 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfMatrix()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfMatrix (void * vp) inline static private
Definition at line 216 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfRetrievalQuantity()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfRetrievalQuantity (void * vp) inline static private
Definition at line 540 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfScatteringMetaData()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfScatteringMetaData (void * vp) inline static private
Definition at line 405 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfSingleScatteringData()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfSingleScatteringData (void * vp) inline static private
Definition at line 387 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfSparse()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfSparse (void * vp) inline static private
Definition at line 234 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfString()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfString (void * vp) inline static private
Definition at line 189 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfTensor3()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfTensor3 (void * vp) inline static private
Definition at line 243 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfTensor4()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfTensor4 (void * vp) inline static private
Definition at line 261 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfTensor6()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfTensor6 (void * vp) inline static private
Definition at line 270 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfTensor7()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfTensor7 (void * vp) inline static private
Definition at line 279 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfVector()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfVector (void * vp) inline static private
Definition at line 198 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_GasAbsLookup()
static void WorkspaceMemoryHandler::deallocate_wsvg_GasAbsLookup (void * vp) inline static private
Definition at line 369 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_GriddedField1()
static void WorkspaceMemoryHandler::deallocate_wsvg_GriddedField1 (void * vp) inline static private
Definition at line 414 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_GriddedField2()
static void WorkspaceMemoryHandler::deallocate_wsvg_GriddedField2 (void * vp) inline static private
Definition at line 423 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_GriddedField3()
static void WorkspaceMemoryHandler::deallocate_wsvg_GriddedField3 (void * vp) inline static private
Definition at line 432 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_GriddedField4()
static void WorkspaceMemoryHandler::deallocate_wsvg_GriddedField4 (void * vp) inline static private
Definition at line 441 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_GriddedField5()
static void WorkspaceMemoryHandler::deallocate_wsvg_GriddedField5 (void * vp) inline static private
Definition at line 450 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_GriddedField6()
static void WorkspaceMemoryHandler::deallocate_wsvg_GriddedField6 (void * vp) inline static private
Definition at line 459 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_GridPos()
static void WorkspaceMemoryHandler::deallocate_wsvg_GridPos (void * vp) inline static private
Definition at line 360 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Index()
static void WorkspaceMemoryHandler::deallocate_wsvg_Index (void * vp) inline static private
Definition at line 54 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Matrix()
static void WorkspaceMemoryHandler::deallocate_wsvg_Matrix (void * vp) inline static private
Definition at line 90 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_MCAntenna()
static void WorkspaceMemoryHandler::deallocate_wsvg_MCAntenna (void * vp) inline static private
Definition at line 549 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Numeric()
static void WorkspaceMemoryHandler::deallocate_wsvg_Numeric (void * vp) inline static private
Definition at line 63 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Ppath()
static void WorkspaceMemoryHandler::deallocate_wsvg_Ppath (void * vp) inline static private
Definition at line 342 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ScatteringMetaData()
static void WorkspaceMemoryHandler::deallocate_wsvg_ScatteringMetaData (void * vp) inline static private
Definition at line 396 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_SingleScatteringData()
static void WorkspaceMemoryHandler::deallocate_wsvg_SingleScatteringData (void * vp) inline static private
Definition at line 378 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Sparse()
static void WorkspaceMemoryHandler::deallocate_wsvg_Sparse (void * vp) inline static private
Definition at line 99 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_SpeciesAuxData()
static void WorkspaceMemoryHandler::deallocate_wsvg_SpeciesAuxData (void * vp) inline static private
Definition at line 558 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_String()
static void WorkspaceMemoryHandler::deallocate_wsvg_String (void * vp) inline static private
Definition at line 72 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Tensor3()
static void WorkspaceMemoryHandler::deallocate_wsvg_Tensor3 (void * vp) inline static private
Definition at line 108 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Tensor4()
static void WorkspaceMemoryHandler::deallocate_wsvg_Tensor4 (void * vp) inline static private
Definition at line 117 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Tensor5()
static void WorkspaceMemoryHandler::deallocate_wsvg_Tensor5 (void * vp) inline static private
Definition at line 126 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Tensor6()
static void WorkspaceMemoryHandler::deallocate_wsvg_Tensor6 (void * vp) inline static private
Definition at line 135 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Tensor7()
static void WorkspaceMemoryHandler::deallocate_wsvg_Tensor7 (void * vp) inline static private
Definition at line 144 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Timer()
static void WorkspaceMemoryHandler::deallocate_wsvg_Timer (void * vp) inline static private
Definition at line 153 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Vector()
static void WorkspaceMemoryHandler::deallocate_wsvg_Vector (void * vp) inline static private
Definition at line 81 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Verbosity()
static void WorkspaceMemoryHandler::deallocate_wsvg_Verbosity (void * vp) inline static private
Definition at line 162 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate()
void* WorkspaceMemoryHandler::duplicate (Index wsvg, void * vp) inline
Getaway function to call the duplication function for the WSV group with the given Index.
Definition at line 777 of file auto_workspace.h.
References duplicatefp.
Referenced by Workspace::duplicate().
duplicate_wsvg_Agenda()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Agenda (void * vp) inline static private
Definition at line 354 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Any()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Any (void * vp) inline static private
Definition at line 48 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfArrayOfGriddedField1()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfArrayOfGriddedField1 (void * vp) inline static private
Definition at line 507 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfArrayOfGriddedField2()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfArrayOfGriddedField2 (void * vp) inline static private
Definition at line 516 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfArrayOfGriddedField3()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfArrayOfGriddedField3 (void * vp) inline static private
Definition at line 525 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfArrayOfIndex()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfArrayOfIndex (void * vp) inline static private
Definition at line 183 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfArrayOfLineMixingRecord()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfArrayOfLineMixingRecord (void * vp) inline static private
Definition at line 534 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfArrayOfLineRecord()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfArrayOfLineRecord (void * vp) inline static private
Definition at line 318 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfArrayOfMatrix()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfArrayOfMatrix (void * vp) inline static private
Definition at line 228 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfArrayOfSpeciesTag()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfArrayOfSpeciesTag (void * vp) inline static private
Definition at line 336 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfArrayOfTensor3()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfArrayOfTensor3 (void * vp) inline static private
Definition at line 255 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfArrayOfTensor6()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfArrayOfTensor6 (void * vp) inline static private
Definition at line 291 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfArrayOfVector()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfArrayOfVector (void * vp) inline static private
Definition at line 210 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfCIARecord()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfCIARecord (void * vp) inline static private
Definition at line 570 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfGriddedField1()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfGriddedField1 (void * vp) inline static private
Definition at line 471 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfGriddedField2()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfGriddedField2 (void * vp) inline static private
Definition at line 480 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfGriddedField3()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfGriddedField3 (void * vp) inline static private
Definition at line 489 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfGriddedField4()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfGriddedField4 (void * vp) inline static private
Definition at line 498 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfIndex()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfIndex (void * vp) inline static private
Definition at line 174 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfLineMixingRecord()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfLineMixingRecord (void * vp) inline static private
Definition at line 300 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfLineRecord()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfLineRecord (void * vp) inline static private
Definition at line 309 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfLineshapeSpec()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfLineshapeSpec (void * vp) inline static private
Definition at line 327 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfMatrix()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfMatrix (void * vp) inline static private
Definition at line 219 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfRetrievalQuantity()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfRetrievalQuantity (void * vp) inline static private
Definition at line 543 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfScatteringMetaData()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfScatteringMetaData (void * vp) inline static private
Definition at line 408 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfSingleScatteringData()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfSingleScatteringData (void * vp) inline static private
Definition at line 390 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfSparse()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfSparse (void * vp) inline static private
Definition at line 237 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfString()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfString (void * vp) inline static private
Definition at line 192 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfTensor3()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfTensor3 (void * vp) inline static private
Definition at line 246 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfTensor4()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfTensor4 (void * vp) inline static private
Definition at line 264 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfTensor6()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfTensor6 (void * vp) inline static private
Definition at line 273 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfTensor7()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfTensor7 (void * vp) inline static private
Definition at line 282 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfVector()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfVector (void * vp) inline static private
Definition at line 201 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_GasAbsLookup()
static void* WorkspaceMemoryHandler::duplicate_wsvg_GasAbsLookup (void * vp) inline static private
Definition at line 372 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_GriddedField1()
static void* WorkspaceMemoryHandler::duplicate_wsvg_GriddedField1 (void * vp) inline static private
Definition at line 417 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_GriddedField2()
static void* WorkspaceMemoryHandler::duplicate_wsvg_GriddedField2 (void * vp) inline static private
Definition at line 426 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_GriddedField3()
static void* WorkspaceMemoryHandler::duplicate_wsvg_GriddedField3 (void * vp) inline static private
Definition at line 435 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_GriddedField4()
static void* WorkspaceMemoryHandler::duplicate_wsvg_GriddedField4 (void * vp) inline static private
Definition at line 444 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_GriddedField5()
static void* WorkspaceMemoryHandler::duplicate_wsvg_GriddedField5 (void * vp) inline static private
Definition at line 453 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_GriddedField6()
static void* WorkspaceMemoryHandler::duplicate_wsvg_GriddedField6 (void * vp) inline static private
Definition at line 462 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_GridPos()
static void* WorkspaceMemoryHandler::duplicate_wsvg_GridPos (void * vp) inline static private
Definition at line 363 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Index()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Index (void * vp) inline static private
Definition at line 57 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Matrix()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Matrix (void * vp) inline static private
Definition at line 93 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_MCAntenna()
static void* WorkspaceMemoryHandler::duplicate_wsvg_MCAntenna (void * vp) inline static private
Definition at line 552 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Numeric()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Numeric (void * vp) inline static private
Definition at line 66 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Ppath()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Ppath (void * vp) inline static private
Definition at line 345 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ScatteringMetaData()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ScatteringMetaData (void * vp) inline static private
Definition at line 399 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_SingleScatteringData()
static void* WorkspaceMemoryHandler::duplicate_wsvg_SingleScatteringData (void * vp) inline static private
Definition at line 381 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Sparse()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Sparse (void * vp) inline static private
Definition at line 102 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_SpeciesAuxData()
static void* WorkspaceMemoryHandler::duplicate_wsvg_SpeciesAuxData (void * vp) inline static private
Definition at line 561 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_String()
static void* WorkspaceMemoryHandler::duplicate_wsvg_String (void * vp) inline static private
Definition at line 75 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Tensor3()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Tensor3 (void * vp) inline static private
Definition at line 111 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Tensor4()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Tensor4 (void * vp) inline static private
Definition at line 120 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Tensor5()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Tensor5 (void * vp) inline static private
Definition at line 129 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Tensor6()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Tensor6 (void * vp) inline static private
Definition at line 138 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Tensor7()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Tensor7 (void * vp) inline static private
Definition at line 147 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Timer()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Timer (void * vp) inline static private
Definition at line 156 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Vector()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Vector (void * vp) inline static private
Definition at line 84 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Verbosity()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Verbosity (void * vp) inline static private
Definition at line 165 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
Member Data Documentation
allocfp
void*(* WorkspaceMemoryHandler::allocfp[59])() private
Definition at line 34 of file auto_workspace.h.
Referenced by allocate(), and WorkspaceMemoryHandler().
deallocfp
void(* WorkspaceMemoryHandler::deallocfp[59])(void *) private
Definition at line 36 of file auto_workspace.h.
Referenced by deallocate(), and WorkspaceMemoryHandler().
duplicatefp
void*(* WorkspaceMemoryHandler::duplicatefp[59])(void *) private
Definition at line 39 of file auto_workspace.h.
Referenced by duplicate(), and WorkspaceMemoryHandler().
The documentation for this class was generated from the following file:
auto_workspace.h