ARTS: disort.h File Reference
disort.h File Reference
Functions for disort interface.
#include "agenda_class.h"
#include "matpackIV.h"
#include "mystring.h"
#include "optproperties.h"
Functions
void dtauc_ssalbCalc (Workspace &ws, VectorView dtauc, VectorView ssalb, const Agenda &opt_prop_part_agenda, const Agenda &propmat_clearsky_agenda, const Agenda &spt_calc_agenda, ConstTensor4View pnd_field, ConstTensor3View t_field, ConstTensor3View z_field, ConstVectorView p_grid, ConstTensor4View vmr_field, ConstVectorView f_mono)
dtauc_ssalbCalc
void phase_functionCalc (MatrixView phase_function, const ArrayOfSingleScatteringData &scat_data_array_mono, ConstTensor4View pnd_field)
phase_functionCalc
void pmomCalc (MatrixView pmom, ConstMatrixView phase_function, ConstVectorView scat_angle_grid, const Index n_legendre, const Verbosity &verbosity)
pmomCalc
Numeric planck2 (const Numeric &f, const Numeric &t)
planck
Detailed Description
Functions for disort interface.
Author
Claudia Emde claud.nosp@m.ia.e.nosp@m.mde@d.nosp@m.lr.d.nosp@m.e
Date
Tue Feb 7 11:48:17 2006
Definition in file disort.h.
Function Documentation
dtauc_ssalbCalc()
void dtauc_ssalbCalc (Workspace & ws, VectorView dtauc, VectorView ssalb, const Agenda & opt_prop_part_agenda, const Agenda & propmat_clearsky_agenda, const Agenda & spt_calc_agenda, ConstTensor4View pnd_field, ConstTensor3View t_field, ConstTensor3View z_field, ConstVectorView p_grid, ConstTensor4View vmr_field, ConstVectorView f_mono)
dtauc_ssalbCalc
Calculates layer averaged cloud optical depth (dtauc) and single scattering albedo (ssalb). These variables are required as input for the DISORT subroutine
Parameters
ws Current workspace
dtauc optical depths for all layers
ssalb single scattering albedos for all layers
opt_prop_part_agenda use arts -d for docu
propmat_clearsky_agenda use arts -d
spt_calc_agenda use arts -d
pnd_field use arts -d
t_field use arts -d
z_field use arts -d
p_grid use arts -d
vmr_field use arts -d
f_index use arts -d
Author
Claudia Emde
Date
2006-02-10
Definition at line 68 of file disort.cc.
References abs, joker, ConstTensor4View::nbooks(), ConstVectorView::nelem(), ConstTensor4View::npages(), opt_prop_part_agendaExecute(), propmat_clearsky_agendaExecute(), and spt_calc_agendaExecute().
phase_functionCalc()
void phase_functionCalc (MatrixView phase_function, const ArrayOfSingleScatteringData & scat_data_array_mono, ConstTensor4View pnd_field)
phase_functionCalc
Calculates layer averaged normalized phase functions from the phase matrix in SingleScatteringData. The scattering angle grid is taken from the data. It is required that all particle types include the same scattering angle grid (FIXME: Include angle interpolation)
Parameters
phase_function normalized phase function
scat_data_array_mono use arts -d for docu
pnd_field use arts -d for docu
Author
Claudia Emde
Date
2006-02-10
Definition at line 189 of file disort.cc.
References ConstMatrixView::ncols(), Array< base >::nelem(), ConstTensor4View::npages(), and PI.
planck2()
Numeric planck2 (const Numeric & f, const Numeric & t)
planck
Calculates the Planck function for a single temperature.
Comment by CE: Copied here from physics_funcs.cc, because I cannot include physics.h in m_disort.cc. The problem is that the definition of complex is not compatible with f2c.h
Note that this expression gives the intensity for both polarisations.
Returns
blackbody radiation
Parameters
f frequency
t temperature
Author
Patrick Eriksson
Date
2000-04-08
Definition at line 364 of file disort.cc.
References BOLTZMAN_CONST, PLANCK_CONST, and SPEED_OF_LIGHT.
pmomCalc()
void pmomCalc (MatrixView pmom, ConstMatrixView phase_function, ConstVectorView scat_angle_grid, const Index n_legendre, const Verbosity & verbosity)
pmomCalc
Calculates Legendre polynomials of phase functions for each layer. The Legendre polynomial are required as input for DISORT.
Parameters
pmom Legendre polynomial of phase functions
phase_function Normalized phase function
scat_angle_grid Scattering angle grid corresponding to phase functions
n_legendre Number of Legendre polynomials to be calculated
Author
Claudia Emde
Date
2006-02-10
Definition at line 255 of file disort.cc.
References abs, CREATE_OUT1, gridpos(), interp(), interpweights(), joker, Array< base >::nelem(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and PI.