ARTS: Faddeeva.cc File Reference
Faddeeva.cc File Reference
#include "Faddeeva.h"
#include <float.h>
#include <math.h>
Macros
#define _GNU_SOURCE
#define FADDEEVA(name) Faddeeva_ ## name
#define FADDEEVA_RE(name) Faddeeva_ ## name ## _re
#define C(a, b) ((a) + I*(b))
#define Inf (1./0.)
#define NaN (0./0.)
#define USE_CONTINUED_FRACTION 1
Typedefs
typedef double complex cmplx
Functions
cmplx FADDEEVA() erfcx (cmplx z, double relerr)
double FADDEEVA_RE() erf (double x)
cmplx FADDEEVA() erf (cmplx z, double relerr)
cmplx FADDEEVA() erfi (cmplx z, double relerr)
double FADDEEVA_RE() erfi (double x)
double FADDEEVA_RE() erfc (double x)
cmplx FADDEEVA() erfc (cmplx z, double relerr)
double FADDEEVA_RE() Dawson (double x)
cmplx FADDEEVA() Dawson (cmplx z, double relerr)
cmplx FADDEEVA() w (cmplx z, double relerr)
double FADDEEVA_RE() erfcx (double x)
double FADDEEVA() w_im (double x)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 220 of file Faddeeva.cc.
C
#define C (a, b) ((a) + I*(b))
Definition at line 254 of file Faddeeva.cc.
FADDEEVA
#define FADDEEVA (name) Faddeeva_ ## name
Definition at line 227 of file Faddeeva.cc.
FADDEEVA_RE
#define FADDEEVA_RE (name) Faddeeva_ ## name ## _re
Definition at line 228 of file Faddeeva.cc.
Inf
#define Inf (1./0.)
Definition at line 255 of file Faddeeva.cc.
NaN
#define NaN (0./0.)
Definition at line 256 of file Faddeeva.cc.
USE_CONTINUED_FRACTION
#define USE_CONTINUED_FRACTION 1
Typedef Documentation
cmplx
typedef double complex cmplx
Definition at line 225 of file Faddeeva.cc.
Function Documentation
Dawson() [1/2]
cmplx FADDEEVA() Dawson (cmplx z, double relerr)
Definition at line 473 of file Faddeeva.cc.
References C, erfcx(), FADDEEVA, FADDEEVA_RE, NaN, w(), and w_im().
Dawson() [2/2]
double FADDEEVA_RE() Dawson (double x)
Definition at line 466 of file Faddeeva.cc.
References FADDEEVA, and w_im().
erf() [1/2]
cmplx FADDEEVA() erf (cmplx z, double relerr)
Definition at line 311 of file Faddeeva.cc.
References C, erf(), FADDEEVA, FADDEEVA_RE, Inf, NaN, w(), and w_im().
erf() [2/2]
double FADDEEVA_RE() erf (double x)
Definition at line 279 of file Faddeeva.cc.
References erfcx(), and FADDEEVA_RE.
Referenced by erf(), and erfi().
erfc() [1/2]
cmplx FADDEEVA() erfc (cmplx z, double relerr)
Definition at line 432 of file Faddeeva.cc.
References C, erfcx(), FADDEEVA, FADDEEVA_RE, Inf, w(), and w_im().
erfc() [2/2]
double FADDEEVA_RE() erfc (double x)
Definition at line 417 of file Faddeeva.cc.
References erfcx(), and FADDEEVA_RE.
erfcx() [1/2]
cmplx FADDEEVA() erfcx (cmplx z, double relerr)
Definition at line 273 of file Faddeeva.cc.
References C, FADDEEVA, and w().
Referenced by Dawson(), erf(), erfc(), and w().
erfcx() [2/2]
double FADDEEVA_RE() erfcx (double x)
Definition at line 1421 of file Faddeeva.cc.
erfi() [1/2]
cmplx FADDEEVA() erfi (cmplx z, double relerr)
Definition at line 403 of file Faddeeva.cc.
References C, erf(), and FADDEEVA.
erfi() [2/2]
double FADDEEVA_RE() erfi (double x)
Definition at line 410 of file Faddeeva.cc.
References FADDEEVA, Inf, and w_im().
w()
cmplx FADDEEVA() w (cmplx z, double relerr)
Definition at line 679 of file Faddeeva.cc.
References C, erfcx(), and FADDEEVA_RE.
Referenced by Dawson(), dotprod_with_los(), erf(), erfc(), erfcx(), GasAbsLookup::Extract(), faddeeva_algorithm_916(), find_all(), find_first(), gzstreambuf::flush_buffer(), from_dpath_to_dx(), interp(), interpweights(), jacobianCalcFreqShift(), jacobianCalcFreqStretch(), jacobianCalcPointingZaInterp(), jacobianCalcPointingZaRecalc(), jacobianCalcPolyfit(), main(), polint(), poly_root_solve(), ppath_end_2d(), ppathFromRtePos2(), CIARecord::ReadFromCIA(), rotationmat3D(), scale_pnd(), sensor_responseFillFgrid(), sensor_responsePolarisation(), spline_0_(), surfaceLambertianSimple(), vectorfield2los(), and yCloudRadar().
w_im()
double FADDEEVA() w_im (double x)
Definition at line 1863 of file Faddeeva.cc.
Referenced by Dawson(), erf(), erfc(), and erfi().