ARTS: geomag_calc.cc File Reference
geomag_calc.cc File Reference
Routine for calculating the geomagnetic field.
#include <iostream>
#include <cmath>
#include "arts.h"
#include "matpackI.h"
#include "xml_io.h"
#include "legendre.h"
Functions
void magfield_nk (Numeric &B_r, Numeric &B_th, Numeric &B_ph, const Numeric r, const Numeric theta, const Numeric phi, const Index Ny, const Verbosity &verbosity)
Variables
const Numeric PI
const Numeric DEG2RAD
const Numeric EARTH_RADIUS
Detailed Description
Routine for calculating the geomagnetic field.
Author
Nikolay Koulev nkoul.nosp@m.ev@u.nosp@m.ni-br.nosp@m.emen.nosp@m..de
Date
Mon Jul 28 11:38:22 2003
Definition in file geomag_calc.cc.
Function Documentation
magfield_nk()
void magfield_nk (Numeric & B_r, Numeric & B_th, Numeric & B_ph, const Numeric r, const Numeric theta, const Numeric phi, const Index Ny, const Verbosity & verbosity)
Definition at line 39 of file geomag_calc.cc.
References DEG2RAD, EARTH_RADIUS, g_legendre_poly_norm_schmidt(), g_legendre_poly_norm_schmidt_deriv3(), M, PI, and xml_read_from_file().
Variable Documentation
DEG2RAD
const Numeric DEG2RAD extern
Referenced by magfield_nk().
EARTH_RADIUS
const Numeric EARTH_RADIUS extern
Referenced by magfield_nk().
PI
const Numeric PI extern
Referenced by magfield_nk().