ARTS: linemixingrecord.cc File Reference
linemixingrecord.cc File Reference
LineMixingRecord implementation.
#include "linemixingrecord.h"
Functions
std::ostream & operator<< (std::ostream &os, const LineMixingRecord &lmr)
Detailed Description
LineMixingRecord implementation.
Author
Oliver Lemke
Definition in file linemixingrecord.cc.
Function Documentation
operator<<()
std::ostream& operator<< (std::ostream & os, const LineMixingRecord & lmr)
Definition at line 27 of file linemixingrecord.cc.
References LineMixingRecord::Data(), LineMixingRecord::Isotopologue(), LineMixingRecord::Quantum(), and LineMixingRecord::Species().