ARTS: linerecord.cc File Reference
linerecord.cc File Reference
LineRecord implementation.
#include <cfloat>
#include "linerecord.h"
#include "absorption.h"
#include "global_data.h"
Functions
ostream & operator<< (ostream &os, const LineRecord &lr)
Output operator for LineRecord.
bool find_matching_lines (ArrayOfIndex &matches, const ArrayOfLineRecord &abs_lines, const Index species, const Index isotopologue, const QuantumNumberRecord qr, const LineMatchingCriteria match_criteria)
Find lines matching the given criteria.
Detailed Description
LineRecord implementation.
Author
Stefan Buehler and Axel von Engeln
Definition in file linerecord.cc.
Function Documentation
find_matching_lines()
bool find_matching_lines (ArrayOfIndex & matches, const ArrayOfLineRecord & abs_lines, const Index species, const Index isotopologue, const QuantumNumberRecord qr, const LineMatchingCriteria match_criteria = LINE_MATCH_ALL)
Find lines matching the given criteria.
Parameters
[out] matches Matching indexes in abs_lines
[in] species Species index (-1 matches all)
[in] isotopologue Isotopologue index (-1 matches all)
[in] qr QuantumNumberRecord
[in] match_criteria One of LINE_MATCH_FIRST, LINE_MATCH_UNIQUE, LINE_MATCH_ALL
Returns
true if the match_criteria was satisfied
Definition at line 2631 of file linerecord.cc.
References LineRecord::Isotopologue(), LINE_MATCH_FIRST, LINE_MATCH_UNIQUE, QuantumNumberRecord::Lower(), Array< base >::nelem(), LineRecord::QuantumNumbers(), LineRecord::Species(), and QuantumNumberRecord::Upper().
Referenced by line_mixing_dataMatch(), and main().
operator<<()
ostream& operator<< (ostream & os, const LineRecord & lr)
Output operator for LineRecord.
The result should look like a catalogue line.
Author
Stefan Buehler
Definition at line 2512 of file linerecord.cc.
References LineRecord::A(), LineRecord::Agam(), LineRecord::Aux(), LineRecord::dAgam(), LineRecord::Delta_foreign(), LineRecord::dF(), LineRecord::dI0(), LineRecord::dNair(), LineRecord::dNself(), LineRecord::dPsf(), LineRecord::dSgam(), LineRecord::Elow(), LineRecord::F(), LineRecord::G_lower(), LineRecord::G_upper(), LineRecord::Gamma_foreign(), LineRecord::I0(), LineRecord::N_foreign(), LineRecord::Nair(), LineRecord::Name(), LineRecord::Naux(), my_basic_string< charT >::nelem(), LineRecord::Nself(), precision, LineRecord::Psf(), LineRecord::QuantumNumbersString(), LineRecord::Sgam(), LineRecord::Tgam(), LineRecord::Ti0(), and LineRecord::Version().