ARTS: linerecord.h File Reference
linerecord.h File Reference
LineRecord class for managing line catalog data.
#include <stdexcept>
#include <cmath>
#include "messages.h"
#include "mystring.h"
#include "array.h"
#include "matpackI.h"
#include "quantum.h"
Classes
class LineRecord
Spectral line catalog data.
Typedefs
typedef Array< LineRecord > ArrayOfLineRecord
Holds a list of spectral line data.
typedef Array< Array< LineRecord > > ArrayOfArrayOfLineRecord
Holds a lists of spectral line data for each tag group.
Enumerations
enum LineMatchingCriteria { LINE_MATCH_FIRST, LINE_MATCH_UNIQUE, LINE_MATCH_ALL }
Functions
ostream & operator<< (ostream &os, const LineRecord &lr)
Output operator for LineRecord.
bool find_matching_lines (ArrayOfIndex &matches, const ArrayOfLineRecord &abs_lines, const Index species, const Index isotopologue, const QuantumNumberRecord qr, const LineMatchingCriteria match_criteria=LINE_MATCH_ALL)
Find lines matching the given criteria.
Detailed Description
LineRecord class for managing line catalog data.
Author
Stefan Buehler, Axel von Engeln
Definition in file linerecord.h.
Typedef Documentation
ArrayOfArrayOfLineRecord
typedef Array< Array<LineRecord> > ArrayOfArrayOfLineRecord
Holds a lists of spectral line data for each tag group.
Dimensions: (tag_groups.nelem()) (number of lines for this tag)
Author
Stefan Buehler
Definition at line 1097 of file linerecord.h.
ArrayOfLineRecord
typedef Array<LineRecord> ArrayOfLineRecord
Holds a list of spectral line data.
Author
Stefan Buehler
Definition at line 1092 of file linerecord.h.
Enumeration Type Documentation
LineMatchingCriteria
enum LineMatchingCriteria
Enumerator
LINE_MATCH_FIRST
LINE_MATCH_UNIQUE
LINE_MATCH_ALL
Definition at line 1104 of file linerecord.h.
Function Documentation
find_matching_lines()
bool find_matching_lines (ArrayOfIndex & matches, const ArrayOfLineRecord & abs_lines, const Index species, const Index isotopologue, const QuantumNumberRecord qr, const LineMatchingCriteria match_criteria = LINE_MATCH_ALL)
Find lines matching the given criteria.
Parameters
[out] matches Matching indexes in abs_lines
[in] species Species index (-1 matches all)
[in] isotopologue Isotopologue index (-1 matches all)
[in] qr QuantumNumberRecord
[in] match_criteria One of LINE_MATCH_FIRST, LINE_MATCH_UNIQUE, LINE_MATCH_ALL
Returns
true if the match_criteria was satisfied
Definition at line 2631 of file linerecord.cc.
References LineRecord::Isotopologue(), LINE_MATCH_FIRST, LINE_MATCH_UNIQUE, QuantumNumberRecord::Lower(), Array< base >::nelem(), LineRecord::QuantumNumbers(), LineRecord::Species(), and QuantumNumberRecord::Upper().
Referenced by line_mixing_dataMatch(), and main().
operator<<()
ostream& operator<< (ostream & os, const LineRecord & lr)
Output operator for LineRecord.
The result should look like a catalogue line.
Author
Stefan Buehler
Definition at line 2512 of file linerecord.cc.
References LineRecord::A(), LineRecord::Agam(), LineRecord::Aux(), LineRecord::dAgam(), LineRecord::Delta_foreign(), LineRecord::dF(), LineRecord::dI0(), LineRecord::dNair(), LineRecord::dNself(), LineRecord::dPsf(), LineRecord::dSgam(), LineRecord::Elow(), LineRecord::F(), LineRecord::G_lower(), LineRecord::G_upper(), LineRecord::Gamma_foreign(), LineRecord::I0(), LineRecord::N_foreign(), LineRecord::Nair(), LineRecord::Name(), LineRecord::Naux(), my_basic_string< charT >::nelem(), LineRecord::Nself(), precision, LineRecord::Psf(), LineRecord::QuantumNumbersString(), LineRecord::Sgam(), LineRecord::Tgam(), LineRecord::Ti0(), and LineRecord::Version().