ARTS: linemixingrecord.h File Reference
linemixingrecord.h File Reference
LineMixingRecord class for storing line mixing data.
#include <iostream>
#include "matpackI.h"
#include "quantum.h"
#include "abs_species_tags.h"
Classes
class LineMixingRecord
Typedefs
typedef Array< LineMixingRecord > ArrayOfLineMixingRecord
typedef Array< ArrayOfLineMixingRecord > ArrayOfArrayOfLineMixingRecord
Functions
std::ostream & operator<< (std::ostream &os, const LineMixingRecord &lmr)
Detailed Description
LineMixingRecord class for storing line mixing data.
Author
Oliver Lemke
Definition in file linemixingrecord.h.
Typedef Documentation
ArrayOfArrayOfLineMixingRecord
typedef Array<ArrayOfLineMixingRecord> ArrayOfArrayOfLineMixingRecord
Definition at line 62 of file linemixingrecord.h.
ArrayOfLineMixingRecord
typedef Array<LineMixingRecord> ArrayOfLineMixingRecord
Definition at line 61 of file linemixingrecord.h.
Function Documentation
operator<<()
std::ostream& operator<< (std::ostream & os, const LineMixingRecord & lmr)
Definition at line 27 of file linemixingrecord.cc.
References LineMixingRecord::Data(), LineMixingRecord::Isotopologue(), LineMixingRecord::Quantum(), and LineMixingRecord::Species().