ARTS: m_append.h File Reference
m_append.h File Reference
Implementation of Append.
#include "array.h"
#include "exceptions.h"
#include "matpackI.h"
Functions
template<class T >
void Append (Array< T > &out, const Array< T > &in, const String &direction, const Verbosity &)
template<class T >
void Append (Array< T > &out, const T &in, const String &direction, const Verbosity &)
void Append (Vector &out, const Vector &in, const String &direction, const Verbosity &)
void Append (Matrix &out, const Matrix &in, const String &direction, const Verbosity &)
void Append (Matrix &out, const Vector &in, const String &direction, const Verbosity &)
void Append (Vector &out, const Numeric &in, const String &direction, const Verbosity &)
void Append (Tensor4 &out, const Tensor4 &in, const String &direction, const Verbosity &)
void Append (String &out, const String &in, const String &direction, const Verbosity &)
Detailed Description
Implementation of Append.
Author
Stefan Buehler sbueh.nosp@m.ler@.nosp@m.ltu.s.nosp@m.e
Date
Fri Jun 14 17:09:05 2002
This file contains the implementation of the supergeneric method Append.
Definition in file m_append.h.
Function Documentation
Append() [1/8]
template<class T > void Append (Array< T > & out, const Array< T > & in, const String & direction, const Verbosity &)
Definition at line 41 of file m_append.h.
References Array< base >::nelem().
Referenced by Append_sg_ArrayOfArrayOfGriddedField1ArrayOfArrayOfGriddedField1_g(), Append_sg_ArrayOfArrayOfGriddedField1ArrayOfGriddedField1_g(), Append_sg_ArrayOfArrayOfGriddedField2ArrayOfArrayOfGriddedField2_g(), Append_sg_ArrayOfArrayOfGriddedField2ArrayOfGriddedField2_g(), Append_sg_ArrayOfArrayOfGriddedField3ArrayOfArrayOfGriddedField3_g(), Append_sg_ArrayOfArrayOfGriddedField3ArrayOfGriddedField3_g(), Append_sg_ArrayOfArrayOfIndexArrayOfArrayOfIndex_g(), Append_sg_ArrayOfArrayOfIndexArrayOfIndex_g(), Append_sg_ArrayOfArrayOfLineMixingRecordArrayOfArrayOfLineMixingRecord_g(), Append_sg_ArrayOfArrayOfLineMixingRecordArrayOfLineMixingRecord_g(), Append_sg_ArrayOfArrayOfLineRecordArrayOfArrayOfLineRecord_g(), Append_sg_ArrayOfArrayOfLineRecordArrayOfLineRecord_g(), Append_sg_ArrayOfArrayOfMatrixArrayOfArrayOfMatrix_g(), Append_sg_ArrayOfArrayOfMatrixArrayOfMatrix_g(), Append_sg_ArrayOfArrayOfSpeciesTagArrayOfArrayOfSpeciesTag_g(), Append_sg_ArrayOfArrayOfTensor3ArrayOfArrayOfTensor3_g(), Append_sg_ArrayOfArrayOfTensor3ArrayOfTensor3_g(), Append_sg_ArrayOfArrayOfTensor6ArrayOfArrayOfTensor6_g(), Append_sg_ArrayOfArrayOfTensor6ArrayOfTensor6_g(), Append_sg_ArrayOfArrayOfVectorArrayOfArrayOfVector_g(), Append_sg_ArrayOfArrayOfVectorArrayOfVector_g(), Append_sg_ArrayOfCIARecordArrayOfCIARecord_g(), Append_sg_ArrayOfGriddedField1ArrayOfGriddedField1_g(), Append_sg_ArrayOfGriddedField1GriddedField1_g(), Append_sg_ArrayOfGriddedField2ArrayOfGriddedField2_g(), Append_sg_ArrayOfGriddedField2GriddedField2_g(), Append_sg_ArrayOfGriddedField3ArrayOfGriddedField3_g(), Append_sg_ArrayOfGriddedField3GriddedField3_g(), Append_sg_ArrayOfGriddedField4ArrayOfGriddedField4_g(), Append_sg_ArrayOfGriddedField4GriddedField4_g(), Append_sg_ArrayOfIndexArrayOfIndex_g(), Append_sg_ArrayOfIndexIndex_g(), Append_sg_ArrayOfLineMixingRecordArrayOfLineMixingRecord_g(), Append_sg_ArrayOfLineRecordArrayOfLineRecord_g(), Append_sg_ArrayOfLineshapeSpecArrayOfLineshapeSpec_g(), Append_sg_ArrayOfMatrixArrayOfMatrix_g(), Append_sg_ArrayOfMatrixMatrix_g(), Append_sg_ArrayOfRetrievalQuantityArrayOfRetrievalQuantity_g(), Append_sg_ArrayOfScatteringMetaDataArrayOfScatteringMetaData_g(), Append_sg_ArrayOfScatteringMetaDataScatteringMetaData_g(), Append_sg_ArrayOfSingleScatteringDataArrayOfSingleScatteringData_g(), Append_sg_ArrayOfSingleScatteringDataSingleScatteringData_g(), Append_sg_ArrayOfSparseArrayOfSparse_g(), Append_sg_ArrayOfSparseSparse_g(), Append_sg_ArrayOfStringArrayOfString_g(), Append_sg_ArrayOfStringString_g(), Append_sg_ArrayOfTensor3ArrayOfTensor3_g(), Append_sg_ArrayOfTensor3Tensor3_g(), Append_sg_ArrayOfTensor4ArrayOfTensor4_g(), Append_sg_ArrayOfTensor4Tensor4_g(), Append_sg_ArrayOfTensor6ArrayOfTensor6_g(), Append_sg_ArrayOfTensor6Tensor6_g(), Append_sg_ArrayOfTensor7ArrayOfTensor7_g(), Append_sg_ArrayOfTensor7Tensor7_g(), Append_sg_ArrayOfVectorArrayOfVector_g(), Append_sg_ArrayOfVectorVector_g(), Append_sg_MatrixMatrix_g(), Append_sg_MatrixVector_g(), Append_sg_StringString_g(), Append_sg_Tensor4Tensor4_g(), Append_sg_VectorNumeric_g(), and Append_sg_VectorVector_g().
Append() [2/8]
template<class T > void Append (Array< T > & out, const T & in, const String & direction, const Verbosity &)
Definition at line 71 of file m_append.h.
Append() [3/8]
void Append (Matrix & out, const Matrix & in, const String & direction, const Verbosity &)
Definition at line 121 of file m_append.h.
References ConstMatrixView::ncols(), ConstMatrixView::nrows(), and Matrix::resize().
Append() [4/8]
void Append (Matrix & out, const Vector & in, const String & direction, const Verbosity &)
Definition at line 172 of file m_append.h.
References ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Matrix::resize(), and transpose().
Append() [5/8]
void Append (String & out, const String & in, const String & direction, const Verbosity &)
Definition at line 276 of file m_append.h.
Append() [6/8]
void Append (Tensor4 & out, const Tensor4 & in, const String & direction, const Verbosity &)
Definition at line 233 of file m_append.h.
References ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), ConstTensor4View::nrows(), and Tensor4::resize().
Append() [7/8]
void Append (Vector & out, const Numeric & in, const String & direction, const Verbosity &)
Definition at line 210 of file m_append.h.
References ConstVectorView::nelem(), and Vector::resize().
Append() [8/8]
void Append (Vector & out, const Vector & in, const String & direction, const Verbosity &)
Definition at line 84 of file m_append.h.
References ConstVectorView::nelem(), and Vector::resize().