ARTS: m_conversion.h File Reference
m_conversion.h File Reference
Implementation of unit conversion functions.
Functions
void FrequencyFromWavelength (Numeric &frequency, const Numeric &wavelength, const Verbosity &)
WORKSPACE METHOD: FrequencyFromWavelength.
void FrequencyFromWavelength (Vector &frequency, const Vector &wavelength, const Verbosity &)
WORKSPACE METHOD: FrequencyFromWavelength.
Variables
const Numeric SPEED_OF_LIGHT
Detailed Description
Implementation of unit conversion functions.
Author
Claudia Emde claud.nosp@m.ia.e.nosp@m.mde@l.nosp@m.mu.d.nosp@m.e
Date
2010-07-21
Definition in file m_conversion.h.
Function Documentation
FrequencyFromWavelength() [1/2]
void FrequencyFromWavelength (Numeric & frequency, const Numeric & wavelength, const Verbosity & verbosity)
WORKSPACE METHOD: FrequencyFromWavelength.
Convert from wavelength [m] to frequency [Hz].
This is a generic method. It can take a single wavelength value or a wavelength vector as input.
Author
Claudia Emde
Parameters
[out] frequency Supergeneric output
[in] wavelength Generic Input
Definition at line 33 of file m_conversion.h.
References SPEED_OF_LIGHT.
Referenced by FrequencyFromWavelength_sg_NumericNumeric_g(), and FrequencyFromWavelength_sg_VectorVector_g().
FrequencyFromWavelength() [2/2]
void FrequencyFromWavelength (Vector & frequency, const Vector & wavelength, const Verbosity & verbosity)
WORKSPACE METHOD: FrequencyFromWavelength.
Convert from wavelength [m] to frequency [Hz].
This is a generic method. It can take a single wavelength value or a wavelength vector as input.
Author
Claudia Emde
Parameters
[out] frequency Supergeneric output
[in] wavelength Generic Input
Definition at line 47 of file m_conversion.h.
References ConstVectorView::nelem(), Vector::resize(), and SPEED_OF_LIGHT.
Variable Documentation
SPEED_OF_LIGHT
const Numeric SPEED_OF_LIGHT extern
Referenced by FrequencyFromWavelength().