ARTS: m_doit2.cc File Reference
m_doit2.cc File Reference
#include <stdexcept>
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "arts.h"
#include "array.h"
#include "auto_md.h"
#include "check_input.h"
#include "matpackVII.h"
#include "logic.h"
#include "ppath.h"
#include "agenda_class.h"
#include "physics_funcs.h"
#include "lin_alg.h"
#include "math_funcs.h"
#include "messages.h"
#include "xml_io.h"
#include "rte.h"
#include "special_interp.h"
#include "doit.h"
#include "m_general.h"
#include "wsv_aux.h"
#include "geodetic.h"
Functions
void CloudboxGetIncoming2 (Workspace &ws, Tensor7 &doit_i_field, const Agenda &iy_main_agenda, const Index &atmosphere_dim, const Vector &lat_grid, const Vector &lon_grid, const Tensor3 &z_field, const Tensor3 &t_field, const Tensor4 &vmr_field, const Matrix &z_surface, const Index &cloudbox_on, const ArrayOfIndex &cloudbox_limits, const Index &basics_checked, const Index &cloudbox_checked, const Index &sensor_checked, const Vector &f_grid, const Index &stokes_dim, const String &iy_unit, const Agenda &blackbody_radiation_agenda, const Vector &scat_za_grid, const Vector &scat_aa_grid, const Index &fill_interior, const Verbosity &)
void iyInterpCloudboxField2 (Matrix &iy, const Tensor7 &doit_i_field, const Vector &rte_pos, const Vector &rte_los, const Index &jacobian_do, const Index &cloudbox_on, const ArrayOfIndex &cloudbox_limits, const Index &basics_checked, const Index &cloudbox_checked, const Index &atmosphere_dim, const Vector &p_grid, const Vector &lat_grid, const Vector &lon_grid, const Tensor3 &z_field, const Index &stokes_dim, const Vector &scat_za_grid, const Vector &scat_aa_grid, const Vector &f_grid, const Index &za_order, const Verbosity &)
Function Documentation
CloudboxGetIncoming2()
void CloudboxGetIncoming2 (Workspace & ws, Tensor7 & doit_i_field, const Agenda & iy_main_agenda, const Index & atmosphere_dim, const Vector & lat_grid, const Vector & lon_grid, const Tensor3 & z_field, const Tensor3 & t_field, const Tensor4 & vmr_field, const Matrix & z_surface, const Index & cloudbox_on, const ArrayOfIndex & cloudbox_limits, const Index & basics_checked, const Index & cloudbox_checked, const Index & sensor_checked, const Vector & f_grid, const Index & stokes_dim, const String & iy_unit, const Agenda & blackbody_radiation_agenda, const Vector & scat_za_grid, const Vector & scat_aa_grid, const Index & fill_interior, const Verbosity &)
Definition at line 28 of file m_doit2.cc.
References chk_if_std_blackbody_agenda(), get_iy(), joker, max, ConstVectorView::nelem(), and Tensor7::resize().
iyInterpCloudboxField2()
void iyInterpCloudboxField2 (Matrix & iy, const Tensor7 & doit_i_field, const Vector & rte_pos, const Vector & rte_los, const Index & jacobian_do, const Index & cloudbox_on, const ArrayOfIndex & cloudbox_limits, const Index & basics_checked, const Index & cloudbox_checked, const Index & atmosphere_dim, const Vector & p_grid, const Vector & lat_grid, const Vector & lon_grid, const Tensor3 & z_field, const Index & stokes_dim, const Vector & scat_za_grid, const Vector & scat_aa_grid, const Vector & f_grid, const Index & za_order, const Verbosity &)
Definition at line 220 of file m_doit2.cc.
References chk_rte_los(), fractional_gp(), gridpos_poly(), gridpos_upperend_check(), GridPos::idx, interp(), interpweights(), joker, min, ConstTensor7View::nbooks(), ConstTensor7View::ncols(), ConstVectorView::nelem(), ConstTensor7View::nlibraries(), ConstTensor7View::npages(), ConstTensor7View::nrows(), ConstTensor7View::nshelves(), ConstTensor7View::nvitrines(), Tensor3::resize(), Matrix::resize(), and rte_pos2gridpos().