ARTS: make_auto_md_cc.cc File Reference
make_auto_md_cc.cc File Reference
#include "arts.h"
#include "array.h"
#include "file.h"
#include "methods.h"
#include "workspace_ng.h"
#include "agenda_record.h"
#include "global_data.h"
Macros
#define DUMMY_ELEMS 0
#define DUMMY_COLS DUMMY_ELEMS
#define DUMMY_ROWS DUMMY_ELEMS
#define DUMMY_PAGES DUMMY_ELEMS
#define DUMMY_BOOKS DUMMY_ELEMS
#define DUMMY_SHELVES DUMMY_ELEMS
#define DUMMY_VITRINES DUMMY_ELEMS
#define DUMMY_LIBRARIES DUMMY_ELEMS
Functions
void align (ofstream &ofs, bool &is_first_parameter, const String &indent)
int main ()
Macro Definition Documentation
DUMMY_BOOKS
#define DUMMY_BOOKS DUMMY_ELEMS
DUMMY_COLS
#define DUMMY_COLS DUMMY_ELEMS
DUMMY_ELEMS
#define DUMMY_ELEMS 0
DUMMY_LIBRARIES
#define DUMMY_LIBRARIES DUMMY_ELEMS
DUMMY_PAGES
#define DUMMY_PAGES DUMMY_ELEMS
DUMMY_ROWS
#define DUMMY_ROWS DUMMY_ELEMS
DUMMY_SHELVES
#define DUMMY_SHELVES DUMMY_ELEMS
DUMMY_VITRINES
#define DUMMY_VITRINES DUMMY_ELEMS
Function Documentation
align()
void align (ofstream & ofs, bool & is_first_parameter, const String & indent)
Definition at line 27 of file make_auto_md_cc.cc.
Referenced by main().
main()
int main (void)
Definition at line 40 of file make_auto_md_cc.cc.
References MdRecord::ActualGroups(), global_data::agenda_data, MdRecord::AgendaMethod(), align(), define_agenda_data(), define_md_data_raw(), Workspace::define_wsv_data(), define_wsv_group_names(), Workspace::define_wsv_map(), DUMMY_BOOKS, DUMMY_COLS, DUMMY_ELEMS, DUMMY_LIBRARIES, DUMMY_PAGES, DUMMY_ROWS, DUMMY_SHELVES, DUMMY_VITRINES, expand_md_data_raw_to_md_data(), get_wsv_group_id(), get_wsv_id(), MdRecord::GInType(), MdRecord::GOutType(), AgRecord::In(), MdRecord::In(), MdRecord::InOnly(), global_data::md_data, MdRecord::Name(), Array< base >::nelem(), my_basic_string< charT >::nelem(), open_output_file(), AgRecord::Out(), MdRecord::Out(), MdRecord::PassWorkspace(), MdRecord::PassWsvNames(), MdRecord::SetMethod(), MdRecord::Supergeneric(), write_agenda_wrapper_header(), Workspace::wsv_data, and global_data::wsv_group_names.