ARTS: math_funcs.cc File Reference
math_funcs.cc File Reference
#include <iostream>
#include <cmath>
#include <stdexcept>
#include "array.h"
#include "math_funcs.h"
#include "logic.h"
#include "mystring.h"
Functions
Numeric fac (const Index n)
fac
Index integer_div (const Index &x, const Index &y)
integer_div
Numeric LagrangeInterpol4 (ConstVectorView x, ConstVectorView y, const Numeric a)
Lagrange Interpolation (internal function).
Numeric last (ConstVectorView x)
last
Index last (const ArrayOfIndex &x)
last
void linspace (Vector &x, const Numeric start, const Numeric stop, const Numeric step)
linspace
void nlinspace (Vector &x, const Numeric start, const Numeric stop, const Index n)
nlinspace
void nlogspace (Vector &x, const Numeric start, const Numeric stop, const Index n)
nlogspace
Numeric AngIntegrate_trapezoid (ConstMatrixView Integrand, ConstVectorView za_grid, ConstVectorView aa_grid)
AngIntegrate_trapezoid.
Numeric AngIntegrate_trapezoid_opti (ConstMatrixView Integrand, ConstVectorView za_grid, ConstVectorView aa_grid, ConstVectorView grid_stepsize)
AngIntegrate_trapezoid_opti.
Numeric AngIntegrate_trapezoid (ConstVectorView Integrand, ConstVectorView za_grid)
AngIntegrate_trapezoid.
Numeric sign (const Numeric &x)
sign
Numeric gamma_func (Numeric xx)
Gamma Function.
Numeric lgamma_func (Numeric xx)
ln Gamma Function
void unitl (Vector &x)
lunit
Variables
const Numeric DEG2RAD
const Numeric PI
Detailed Description
Author
Patrick Eriksson Patri.nosp@m.ck.E.nosp@m.rikss.nosp@m.on@c.nosp@m.halme.nosp@m.rs.s.nosp@m.e
Date
2000-09-18
Contains basic mathematical functions.
Definition in file math_funcs.cc.
Function Documentation
AngIntegrate_trapezoid() [1/2]
Numeric AngIntegrate_trapezoid (ConstMatrixView Integrand, ConstVectorView za_grid, ConstVectorView aa_grid)
AngIntegrate_trapezoid.
Performs an integration of a matrix over all directions defined in angular grids using the trapezoidal integration method.
Parameters
Integrand The Matrix to be integrated
za_grid The zenith angle grid
aa_grid The azimuth angle grid
Returns
The resulting integral
Definition at line 327 of file math_funcs.cc.
References DEG2RAD, is_size(), and ConstVectorView::nelem().
Referenced by AngIntegrate_trapezoid_opti(), doit_scat_fieldNormalize(), and scat_data_arrayCheck().
AngIntegrate_trapezoid() [2/2]
Numeric AngIntegrate_trapezoid (ConstVectorView Integrand, ConstVectorView za_grid)
AngIntegrate_trapezoid.
Performs an integration of a matrix over all directions defined in angular grids using the trapezoidal integration method. The integrand is independant of the azimuth angle. The integration over the azimuth angle gives a 2*PI
Parameters
Integrand Input : The vector to be integrated
za_grid Input : The zenith angle grid
Author
Claas Teichmann
Date
2003-05-13
Returns
The resulting integral
Definition at line 438 of file math_funcs.cc.
References DEG2RAD, is_size(), ConstVectorView::nelem(), and PI.
AngIntegrate_trapezoid_opti()
Numeric AngIntegrate_trapezoid_opti (ConstMatrixView Integrand, ConstVectorView za_grid, ConstVectorView aa_grid, ConstVectorView grid_stepsize)
AngIntegrate_trapezoid_opti.
Performs an integration of a matrix over all directions defined in angular grids using the trapezoidal integration method.
In addition to the "old fashined" integration method, it checks whether the stepsize is constant. If it is, it uses a faster method, if not, it uses the old one.
Parameters
Integrand Input : The Matrix to be integrated
za_grid Input : The zenith angle grid
aa_grid Input : The azimuth angle grid
grid_stepsize Input : stepsize of the grid
Returns
The resulting integral
Author
Claas Teichmann claas.nosp@m.@sat.nosp@m..phys.nosp@m.ik.u.nosp@m.ni-br.nosp@m.emen.nosp@m..de
Date
2003/05/28
Definition at line 377 of file math_funcs.cc.
References AngIntegrate_trapezoid(), DEG2RAD, is_size(), ConstVectorView::nelem(), and temp.
Referenced by doit_scat_fieldCalc(), doit_scat_fieldCalcLimb(), and test_AngIntegrate_trapezoid_opti().
fac()
Numeric fac (const Index n)
fac
Calculates the factorial.
The function asserts that n must be >= 0
Returns
The factorial
Parameters
n Nominator
Author
Oliver Lemke
Date
2003-08-15
Definition at line 68 of file math_funcs.cc.
Referenced by addspec_(), faddeeva_algorithm_916(), g_legendre_poly_norm_schmidt(), g_legendre_poly_norm_schmidt_deriv(), g_legendre_poly_norm_schmidt_deriv1(), g_legendre_poly_norm_schmidt_deriv2(), g_legendre_poly_norm_schmidt_deriv3(), g_legendre_poly_norm_schmidt_deriv4(), hui_etal_1978_lineshape(), iyCloudRadar(), legendre_poly_norm_schmidt(), legendre_poly_norm_schmidt_deriv(), lineshape_CO2_lorentz(), lineshape_doppler(), lineshape_lorentz(), lineshape_norm_linear(), lineshape_norm_no_norm(), lineshape_norm_quadratic(), lineshape_norm_VVH(), lineshape_voigt_drayson(), lineshape_voigt_kuntz3(), lineshape_voigt_kuntz4(), lineshape_voigt_kuntz6(), MPM93_N2_continuum(), pnd_fieldGM58(), pnd_fieldMP48(), pnd_fieldSS70(), specular_losCalc(), and xsec_species().
gamma_func()
Numeric gamma_func (Numeric xx)
Gamma Function.
Returns gamma function of real argument 'x'. Returns error msg if argument is a negative integer or 0, or use lgamma function if argument exceeds 32.0.
Returns
gam Gamma function of x.
Parameters
xx Numeric
Author
Daniel Kreyling
Date
2010-12-13
Definition at line 497 of file math_funcs.cc.
References lgamma_func().
Referenced by IWCtopnd_MH97(), LWCtopnd(), and LWCtopnd2().
integer_div()
Index integer_div (const Index & x, const Index & y)
integer_div
Performs an integer division.
The function asserts that the reminder of the division x/y is 0.
Returns
The quotient
Parameters
x Nominator
y Denominator
Author
Patrick Eriksson
Date
2002-08-11
Definition at line 95 of file math_funcs.cc.
References is_multiple().
LagrangeInterpol4()
Numeric LagrangeInterpol4 (ConstVectorView x, ConstVectorView y, const Numeric a)
Lagrange Interpolation (internal function).
This function calculates the Lagrange interpolation of four interpolation points as described in Lagrange Interpolating Polynomial.
The input are the four x-axis values [x0,x1,x2,x3] and their associated y-axis values [y0,y1,y2,y3]. Furthermore the x-axis point "a" at which the interpolation should be calculated must be given as input. NOTE that the relation x2 =< x < x3 MUST hold!
Parameters
x x-vector with four elements [x0,x1,x2,x3]
y y-vector with four elements: yj = y(xj), j=0,1,2,3
a interpolation point on the x-axis with x1 =< a < x2
Returns
FIXME
Author
Thomas Kuhn
Date
2003-11-25
Definition at line 124 of file math_funcs.cc.
References ConstVectorView::nelem().
last() [1/2]
Index last (const ArrayOfIndex & x)
last
Returns the last value of an index array.
Returns
The last value of x.
Parameters
x An index array.
Author
Patrick Eriksson
Date
2000-06-27
Definition at line 201 of file math_funcs.cc.
References Array< base >::nelem().
last() [2/2]
Numeric last (ConstVectorView x)
last
Returns the last value of a vector.
Returns
The last value of x.
Parameters
x A vector.
Author
Patrick Eriksson
Date
2000-06-27
Definition at line 183 of file math_funcs.cc.
References ConstVectorView::nelem().
Referenced by antenna2d_simplified(), chk_scat_data(), find_effective_channel_boundaries(), iyFOS(), mixer_matrix(), pos2refell_r(), refr_index_airFreeElectrons(), sensor_responseAntenna(), sensor_responseBackend(), sensor_responseMixer(), sensor_summation_vector(), and ySimpleSpectrometer().
lgamma_func()
Numeric lgamma_func (Numeric xx)
ln Gamma Function
Returns ln of gamma function for real argument 'x'.
Returns
ln Gamma function of x.
Parameters
xx Numeric
Author
Daniel Kreyling
Date
2010-12-13
Definition at line 538 of file math_funcs.cc.
Referenced by gamma_func().
linspace()
void linspace (Vector & x, const Numeric start, const Numeric stop, const Numeric step)
linspace
Linearly spaced vector with specified spacing.
The first element of x is always start. The next value is start+step etc. Note that the last value can deviate from stop. The step can be both positive and negative. (in Matlab notation: start:step:stop)
Size of result is adjusted within this function!
Parameters
x Output: linearly spaced vector
start first value in x
stop last value of x <= stop
step distance between values in x
Author
Patrick Eriksson
Date
2000-06-27
Definition at line 228 of file math_funcs.cc.
References Vector::resize().
Referenced by VectorLinSpace(), VectorLogSpace(), and ySimpleSpectrometer().
nlinspace()
void nlinspace (Vector & x, const Numeric start, const Numeric stop, const Index n)
nlinspace
Linearly spaced vector with specified length.
Returns a vector equally and linearly spaced between start and stop of length n. (equals the Matlab function linspace)
The length must be > 1.
Parameters
x Output: linearly spaced vector
start first value in x
stop last value of x <= stop
n length of x
Author
Patrick Eriksson
Date
2000-06-27
Definition at line 261 of file math_funcs.cc.
References Vector::resize().
Referenced by AntennaConstantGaussian1D(), calc_ssp_fixed_test(), calc_ssp_random_test(), doit_scat_fieldCalcLimb(), DoitAngularGridsSet(), DoitScatteringDataPrepare(), f_gridFromSensorAMSU(), f_gridFromSensorHIRS(), gaussian_response_autogrid(), pha_mat_sptFromDataDOITOpt(), pha_mat_sptFromMonoData(), pnd_fieldZero(), sensor_responseFillFgrid(), and VectorNLinSpace().
nlogspace()
void nlogspace (Vector & x, const Numeric start, const Numeric stop, const Index n)
nlogspace
Logarithmically spaced vector with specified length.
Returns a vector logarithmically spaced vector between start and stop of length n (equals the Matlab function logspace)
The length must be > 1.
Parameters
x Output: logarithmically spaced vector
start first value in x
stop last value of x <= stop
n length of x
Author
Patrick Eriksson
Date
2000-06-27
Definition at line 294 of file math_funcs.cc.
References Vector::resize().
Referenced by VectorNLogSpace().
sign()
Numeric sign (const Numeric & x)
sign
Returns the sign of a numeric value.
The function returns 1 if the value is greater than zero, 0 if it equals zero and -1 if it is less than zero.
Returns
The sign of x (see above).
Parameters
x A Numeric.
Author
Patrick Eriksson
Date
2000-06-27
Definition at line 473 of file math_funcs.cc.
Referenced by binostream::float2ieee_double(), binostream::float2ieee_single(), geompath_from_r1_to_r2(), binistream::ieee_double2float(), binistream::ieee_single2float(), lat_crossing_3d(), poslos2cart(), r_crossing_2d(), raytrace_2d_linear_basic(), and specular_losCalc().
unitl()
void unitl (Vector & x)
lunit
Normalises a vector to have unit length.
The standard Euclidean norm is used (2-norm).
param x In/Out: A vector.
Author
Patrick Eriksson
Date
2012-02-12
Definition at line 578 of file math_funcs.cc.
References ConstVectorView::nelem().
Variable Documentation
DEG2RAD
const Numeric DEG2RAD extern
Referenced by AngIntegrate_trapezoid(), and AngIntegrate_trapezoid_opti().
PI
const Numeric PI extern
Referenced by AngIntegrate_trapezoid().