ARTS: matpackII.h File Reference
matpackII.h File Reference
Header file for sparse matrices.
#include "matpackI.h"
Classes
class Sparse
The Sparse class.
Functions
void abs (Sparse &A, const Sparse &B)
Absolute value of sparse matrix elements.
void mult (VectorView y, const Sparse &M, ConstVectorView x)
Sparse matrix - Vector multiplication.
void mult (MatrixView A, const Sparse &B, ConstMatrixView C)
SparseMatrix - Matrix multiplication.
void mult (Sparse &A, const Sparse &B, const Sparse &C)
Sparse - Sparse multiplication.
void add (Sparse &A, const Sparse &B, const Sparse &C)
Sparse - Sparse addition.
void sub (Sparse &A, const Sparse &B, const Sparse &C)
Sparse - Sparse subtraction.
void transpose (Sparse &A, const Sparse &B)
Transpose of sparse matrix.
Detailed Description
Header file for sparse matrices.
Author
Stefan Buehler sbueh.nosp@m.ler@.nosp@m.ltu.s.nosp@m.e
Date
Tue Jul 15 15:05:40 2003
Notes:
There are two different ways to index: S.rw(3,4) = 1; // Read and write cout << S.ro(3,4); // Read only
This distinction is necessary, because rw() creates elements if they don't already exist.
The normal index operator "()" correspondes to ro, so "S(3,4)" is the same as S.ro(3,4).
Definition in file matpackII.h.
Function Documentation
abs()
void abs (Sparse & A, const Sparse & B)
Absolute value of sparse matrix elements.
Computes the absolute values of the elements in sparse matrix B.
The output matrix A must have been initialized with the correct size.
Parameters
A Output: Absolute value matrix.
B Original matrix.
Author
Mattias Ekstrom
Date
2005-03-21
Definition at line 86 of file matpackII.cc.
References copy(), Sparse::mcolptr, Sparse::mdata, Sparse::mrowind, Sparse::ncols(), and Sparse::nrows().
add()
void add (Sparse & A, const Sparse & B, const Sparse & C)
Sparse - Sparse addition.
Calculates A = B+C, where result A is sparse, and B and C are also sparse.
Output comes first!
Dimensions of B, and C must match. A will be resized.
Parameters
A Output: Result matrix.
B First summand matrix.
C Second summand matrix.
Author
Oliver Lemke
Date
2009-09-03
Definition at line 90 of file matpackII.cc.
References C, Sparse::data(), Sparse::mcolptr, Sparse::mdata, Sparse::mrowind, Sparse::ncols(), Sparse::nrows(), and Sparse::rw().
Referenced by test49().
mult() [1/3]
void mult (MatrixView A, const Sparse & B, ConstMatrixView C)
SparseMatrix - Matrix multiplication.
Calculates the matrix product:
A = B*C, where B is sparse.
Output comes first!
Dimensions of A, B, and C must match. No memory reallocation takes place, only the data is copied.
Parameters
A Output: Result matrix (full).
B First matrix to multiply (sparse).
C Second matrix to multiply (full).
Author
Stefan Buehler sbueh.nosp@m.ler@.nosp@m.ltu.s.nosp@m.e
Date
Tue Jul 15 15:05:40 2003
Definition at line 88 of file matpackII.cc.
References C, Sparse::mcolptr, Sparse::mdata, Sparse::mrowind, ConstMatrixView::ncols(), Sparse::ncols(), ConstMatrixView::nrows(), and Sparse::nrows().
mult() [2/3]
void mult (Sparse & A, const Sparse & B, const Sparse & C)
Sparse - Sparse multiplication.
Calculates A = B*C, where result A is sparse, and B and C are also sparse.
Output comes first!
Dimensions of A, B, and C must match. No memory reallocation takes place, only the data is copied.
Parameters
A Output: Result matrix.
B First product matrix.
C Second product matrix.
Author
Mattias Ekstroem
Date
2003-08-06
Definition at line 89 of file matpackII.cc.
References C, Sparse::mcolptr, Sparse::mcr, Sparse::mdata, Sparse::mrowind, Sparse::ncols(), Sparse::nrows(), Sparse::rw(), and transpose().
mult() [3/3]
void mult (VectorView y, const Sparse & M, ConstVectorView x)
Sparse matrix - Vector multiplication.
This calculates the product
y = M*x, where M is sparse.
Output comes first!
Dimensions of y, M, and x must match. No memory reallocation takes place, only the data is copied.
Parameters
y Output: The multiplication result.
M Matrix for multiplication (sparse).
x Vector for multiplication.
Author
Stefan Buehler sbueh.nosp@m.ler@.nosp@m.ltu.s.nosp@m.e
Date
Tue Jul 15 15:05:40 2003
Definition at line 87 of file matpackII.cc.
References M, and ConstVectorView::nelem().
sub()
void sub (Sparse & A, const Sparse & B, const Sparse & C)
Sparse - Sparse subtraction.
Calculates A = B-C, where result A is sparse, and B and C are also sparse.
Output comes first!
Dimensions of B, and C must match. A will be resized.
Parameters
A Output: Result matrix.
B First subtrahend matrix.
C Second subtrahend matrix.
Author
Oliver Lemke
Date
2009-09-03
Definition at line 91 of file matpackII.cc.
References C, Sparse::ncols(), Sparse::nrows(), and Sparse::rw().
Referenced by sensor_responseBackendFrequencySwitching(), and test49().
transpose()
void transpose (Sparse & A, const Sparse & B)
Transpose of sparse matrix.
Computes the transpose of the sparse matrix B.
The output matrix A must have been initialized with the correct size.
Parameters
A Output: Transposed matrix.
B Original matrix.
Author
Mattias Ekstroem
Date
2003-08-05
Definition at line 92 of file matpackII.cc.
References Sparse::mcolptr, Sparse::mcr, Sparse::mdata, Sparse::mrowind, Sparse::ncols(), and Sparse::nrows().
Referenced by mult().