ARTS: partition_function_data.cc File Reference
partition_function_data.cc File Reference
Coefficients for 3rd order polynomial of partition function in temperature, plus safety check.
#include "arts.h"
#include "make_array.h"
#include "absorption.h"
Namespaces
global_data
Some #defines for better readability
#define Qcoeff MakeArray<Numeric>
void spec (Array< SpeciesRecord >::iterator &is, Array< IsotopologueRecord >::iterator &ii, String name)
Define partition function coefficients lookup data.
void iso (Array< IsotopologueRecord >::iterator &ii, String name, const ArrayOfNumeric &coeff, const Index &coefftype)
void define_partition_species_data ()
Detailed Description
Coefficients for 3rd order polynomial of partition function in temperature, plus safety check.
This file contains the definition of this function and a safety check of the input. You have to add the coefficients of new species here, along with the new entry into the species_data (file species_data.cc) record, if you want to extend the capability of ARTS. These entries have to be in the same order, which is assured by check_q_data.
This is the file from arts-1-0, back-ported to arts-1-1.
Author
Axel von Engeln, C. Verdes,
Date
2000-08-21
Definition in file partition_function_data.cc.
Macro Definition Documentation
Qcoeff
#define Qcoeff MakeArray<Numeric>
Definition at line 69 of file partition_function_data.cc.
Function Documentation
define_partition_species_data()
void define_partition_species_data ()
Definition at line 187 of file partition_function_data.cc.
References iso(), IsotopologueRecord::PF_FROMCOEFF, Qcoeff, spec(), and global_data::species_data.
Referenced by define_species_data().
iso()
void iso (Array< IsotopologueRecord >::iterator & ii, String name, const ArrayOfNumeric & coeff, const Index & coefftype)
Definition at line 937 of file partition_function_data.cc.
Referenced by abs_cia_dataReadFromCIA(), abs_cia_dataReadFromXML(), checkIsotopologueRatios(), define_partition_species_data(), LineRecord::ReadFromHitran2001Stream(), LineRecord::ReadFromHitran2004Stream(), and LineRecord::ReadFromMytran2Stream().
spec()
void spec (Array< SpeciesRecord >::iterator & is, Array< IsotopologueRecord >::iterator & ii, String name)
Define partition function coefficients lookup data.
General Remarks
Definition at line 925 of file partition_function_data.cc.
Referenced by define_partition_species_data(), find_first_species_tg(), and find_next_species_tg().