ARTS: physics_funcs.h File Reference
physics_funcs.h File Reference
#include "arts.h"
#include "matpackI.h"
#include "complex.h"
Functions
Numeric barometric_heightformula (const Numeric &p, const Numeric &dh)
Numeric dinvplanckdI (const Numeric &i, const Numeric &f)
dinvplanckdI
void fresnel (Complex &Rv, Complex &Rh, const Complex &n1, const Complex &n2, const Numeric &theta)
fresnel
Numeric invplanck (const Numeric &i, const Numeric &f)
invplanck
Numeric invrayjean (const Numeric &i, const Numeric &f)
invrayjean
Numeric number_density (const Numeric &p, const Numeric &t)
number_density
Numeric planck (const Numeric &f, const Numeric &t)
planck
Numeric rayjean (const Numeric &f, const Numeric &t)
rayjean
Complex refice_ (const Numeric &wavlen, const Numeric &temp)
Calculates complex refractive index of Ice 1H.
Detailed Description
Author
Patrick Eriksson Patri.nosp@m.ck.E.nosp@m.rikss.nosp@m.on@c.nosp@m.halme.nosp@m.rs.s.nosp@m.e
Date
2002-05-08
This file contains declerations of functions of physical character.
Definition in file physics_funcs.h.
Function Documentation
barometric_heightformula()
Numeric barometric_heightformula (const Numeric & p, const Numeric & dh)
barometric heightformula for isothermal earth atmosphere
Returns
p1 pressure in displacement level [Pa]
Parameters
p atmospheric pressure at starting level [Pa]
dh vertical displacement to starting pressure level [m]
Author
Daniel Kreyling
Date
2011-01-20
Definition at line 70 of file physics_funcs.cc.
References M.
Referenced by cloudboxSetAutomatically().
dinvplanckdI()
Numeric dinvplanckdI (const Numeric & i, const Numeric & f)
dinvplanckdI
Calculates the derivative of inverse-Planck with respect to intensity.
Returns
The derivative
Parameters
i radiance
f frequency
Author
Patrick Eriksson
Date
2010-10-26
Definition at line 110 of file physics_funcs.cc.
References BOLTZMAN_CONST, PLANCK_CONST, and SPEED_OF_LIGHT.
Referenced by apply_iy_unit2().
fresnel()
void fresnel (Complex & Rv, Complex & Rh, const Complex & n1, const Complex & n2, const Numeric & theta)
fresnel
Calculates complex AMPLITUDE reflection coeffcients for a specular reflection
The properties of the two involved media are given as the complex refractive index, n. A dielectric constant, eps, is converted as n = sqrt(eps). The power reflection coefficient, r, for one polarisation is r = abs(R)^2.
Parameters
Rv Out: Reflection coefficient for vertical polarisation
Rh Out: Reflection coefficient for vertical polarisation
n1 In: Refractive index of medium where radiation propagates
n2 In: Refractive index of reflecting medium
theta In: Propagation angle from normal of radiation to be reflected
Author
Patrick Eriksson
Date
2004-09-21
Definition at line 148 of file physics_funcs.cc.
References DEG2RAD.
Referenced by surfaceFlatRefractiveIndex().
invplanck()
Numeric invplanck (const Numeric & i, const Numeric & f)
invplanck
Converts a radiance to Planck brightness temperature.
Returns
Planck brightness temperature
Parameters
i radiance
f frequency
Author
Patrick Eriksson
Date
2002-08-11
Definition at line 180 of file physics_funcs.cc.
References BOLTZMAN_CONST, PLANCK_CONST, and SPEED_OF_LIGHT.
Referenced by apply_iy_unit().
invrayjean()
Numeric invrayjean (const Numeric & i, const Numeric & f)
invrayjean
Converts a radiance to Rayleigh-Jean brightness temperature.
Returns
RJ brightness temperature
Parameters
i radiance
f frequency
Author
Patrick Eriksson
Date
2000-09-28
Definition at line 214 of file physics_funcs.cc.
References BOLTZMAN_CONST, and SPEED_OF_LIGHT.
Referenced by apply_iy_unit(), apply_iy_unit2(), doit_conv_flagAbsBT(), doit_conv_flagLsq(), doit_i_fieldUpdateSeq1D(), MCGeneral(), and MCIPA().
number_density()
Numeric number_density (const Numeric & p, const Numeric & t)
number_density
Calculates the atmospheric number density.
Returns
number density
Parameters
p pressure
t temperature
Author
Patrick Eriksson
Date
2000-04-08
Definition at line 237 of file physics_funcs.cc.
References BOLTZMAN_CONST.
Referenced by abs_coefCalcFromXsec(), abs_xsec_per_speciesAddCIA(), calc_nd_field(), GasAbsLookup::Extract(), vmrunitscf(), and xsec_species_line_mixing_wrapper_with_zeeman().
planck()
Numeric planck (const Numeric & f, const Numeric & t)
planck
Calculates the Planck function for a single temperature.
Note that this expression gives the intensity for both polarisations.
Returns
blackbody radiation
Parameters
f frequency
t temperature
Author
Patrick Eriksson
Date
2000-04-08
Definition at line 261 of file physics_funcs.cc.
References BOLTZMAN_CONST, PLANCK_CONST, and SPEED_OF_LIGHT.
Referenced by blackbody_radiationPlanck(), cloud_ppath_update1D_planeparallel(), cloud_RT_no_background(), MatrixCBR(), MatrixPlanck(), MCGeneral(), and MCIPA().
rayjean()
Numeric rayjean (const Numeric & f, const Numeric & t)
rayjean
Converts a Rayleigh-Jean brightness temperature to radiance
Returns
radiance
Parameters
tb RJ brightness temperature
f frequency
Author
Patrick Eriksson
Date
2011-07-13
Definition at line 293 of file physics_funcs.cc.
References BOLTZMAN_CONST, and SPEED_OF_LIGHT.
refice_()
Complex refice_ (const Numeric & wavlen, const Numeric & temp)
Calculates complex refractive index of Ice 1H.
Valid range for wavelengths is between 45 nm and 8.6 m. For wavelengths above 167 microns, temperature dependence is included for temperatures between 213 and 272K. Mainly intended for applications in Earth ice clouds and snow, not other planets or interstellar space; the temperature dependence or crystalline form of ice may be incorrect for these latter applications.
Authors of Fortran function:
Stephen Warren, Univ. of Washington (1983)
Bo-Cai Gao, JCESS, Univ. of Maryland (1995)
Warren Wiscombe, NASA Goddard (1995)
References:
Warren, S., 1984: Optical Constants of Ice from the Ultraviolet to the Microwave, Appl. Opt. 23, 1206-1225
Kou, L., D. Labrie, and P. Chylek, 1994: Refractive indices of water and ice in the 0.65- to 2.5-micron spectral range, Appl. Opt. 32, 3531-3540
Perovich, D., and J. Govoni, 1991: Absorption Coefficients of Ice from 250 to 400 nm, Geophys. Res. Lett. 18, 1233-1235
Parameters
[in] wavlen Wavelength in microns
[in] temp Temperature in Kelvin
Returns
Refractive index as complex number