ARTS: sensor.cc File Reference
sensor.cc File Reference
Functions related to sensor modelling.
#include <cmath>
#include <list>
#include <stdexcept>
#include "arts.h"
#include "logic.h"
#include "make_vector.h"
#include "matpackI.h"
#include "matpackII.h"
#include "messages.h"
#include "sorting.h"
#include "sensor.h"
Functions
void antenna1d_matrix (Sparse &H, const Index &antenna_dim, ConstMatrixView antenna_los, const GriddedField4 &antenna_response, ConstVectorView za_grid, ConstVectorView f_grid, const Index n_pol, const Index do_norm)
antenna1d_matrix
void antenna2d_simplified (Sparse &H, const Index &antenna_dim, ConstMatrixView antenna_los, const GriddedField4 &antenna_response, ConstVectorView za_grid, ConstVectorView aa_grid, ConstVectorView f_grid, const Index n_pol, const Index do_norm)
antenna2d_simplified
void gaussian_response_autogrid (Vector &x, Vector &y, const Numeric &x0, const Numeric &fwhm, const Numeric &xwidth_si, const Numeric &dx_si)
gaussian_response_autogrid
void gaussian_response (Vector &y, const Vector &x, const Numeric &x0, const Numeric &fwhm)
gaussian_response
void mixer_matrix (Sparse &H, Vector &f_mixer, const Numeric &lo, const GriddedField1 &filter, ConstVectorView f_grid, const Index &n_pol, const Index &n_sp, const Index &do_norm)
mixer_matrix
void sensor_aux_vectors (Vector &sensor_response_f, ArrayOfIndex &sensor_response_pol, Vector &sensor_response_za, Vector &sensor_response_aa, ConstVectorView sensor_response_f_grid, const ArrayOfIndex &sensor_response_pol_grid, ConstVectorView sensor_response_za_grid, ConstVectorView sensor_response_aa_grid, const Index za_aa_independent)
sensor_aux_vectors
void sensor_integration_vector (VectorView h, ConstVectorView f, ConstVectorView x_f_in, ConstVectorView x_g_in)
sensor_integration_vector
void sensor_integration_vector2 (VectorView h, ConstVectorView f, ConstVectorView x_f, ConstVectorView x_g_in)
sensor_integration_vector
void sensor_summation_vector (VectorView h, ConstVectorView f, ConstVectorView x_f, ConstVectorView x_g, const Numeric x1, const Numeric x2)
sensor_summation_vector
void spectrometer_matrix (Sparse &H, ConstVectorView ch_f, const ArrayOfGriddedField1 &ch_response, ConstVectorView sensor_f, const Index &n_pol, const Index &n_sp, const Index &do_norm)
spectrometer_matrix
void stokes2pol (ArrayOfVector &s2p, const Numeric &nv)
stokes2pol
bool test_and_merge_two_channels (Vector &fmin, Vector &fmax, Index i, Index j)
Test if two instrument channels overlap, and if so, merge them.
void find_effective_channel_boundaries (Vector &fmin, Vector &fmax, const Vector &f_backend, const ArrayOfGriddedField1 &backend_channel_response, const Numeric &delta, const Verbosity &verbosity)
Calculate channel boundaries from instrument response functions.
Variables
const Numeric PI
const Numeric NAT_LOG_2
const Index GFIELD1_F_GRID
const Index GFIELD4_FIELD_NAMES
const Index GFIELD4_F_GRID
const Index GFIELD4_ZA_GRID
const Index GFIELD4_AA_GRID
Detailed Description
Functions related to sensor modelling.
Author
Mattias Ekström ekstr.nosp@m.om@r.nosp@m.ss.ch.nosp@m.alme.nosp@m.rs.se
Date
2003-02-27
Functions to model sensor behaviour and integration calculated as vector multiplication.
Definition in file sensor.cc.
Function Documentation
antenna1d_matrix()
void antenna1d_matrix (Sparse & H, const Index & antenna_dim, ConstMatrixView antenna_los, const GriddedField4 & antenna_response, ConstVectorView za_grid, ConstVectorView f_grid, const Index n_pol, const Index do_norm)
antenna1d_matrix
Core function for setting up the response matrix for 1D antenna cases.
Main task is to extract correct antenna pattern, including frequency interpolation. Actual weights are calculated in sensor_integration_vector.
Parameters
H The antenna transfer matrix
antenna_dim As the WSV with the same name
antenna_los As the WSV with the same name
antenna_response As the WSV with the same name
za_grid Zenith angle grid for pencil beam calculations
f_grid Frequency grid for monochromatic calculations
n_pol Number of polarisation states
do_norm Flag whether response should be normalised
Author
Mattias Ekström / Patrick Eriksson
Date
2003-05-27 / 2008-06-17
Definition at line 79 of file sensor.cc.
References GriddedField4::data, DEBUG_ONLY, GriddedField::get_numeric_grid(), GriddedField::get_string_grid(), GFIELD4_AA_GRID, GFIELD4_F_GRID, GFIELD4_FIELD_NAMES, GFIELD4_ZA_GRID, gridpos(), Sparse::insert_row(), interp(), interpweights(), joker, Sparse::ncols(), Array< base >::nelem(), ConstVectorView::nelem(), Sparse::resize(), sensor_integration_vector(), and ConstVectorView::sum().
Referenced by antenna2d_simplified(), and sensor_responseAntenna().
antenna2d_simplified()
void antenna2d_simplified (Sparse & H, const Index & antenna_dim, ConstMatrixView antenna_los, const GriddedField4 & antenna_response, ConstVectorView za_grid, ConstVectorView aa_grid, ConstVectorView f_grid, const Index n_pol, const Index do_norm)
antenna2d_simplified
A first function for setting up the response matrix for 2D antenna cases.
Following the ARTS definitions, a bi-linear variation (in za and aa dimensions) for both antenna pattern and pencil beam radiances should be assumed here. This function does not handle this. It performs instead a series of 1D antenna calculations and "sums up" the results. In this summation, both antenna pattern and radiances are assumed to constant in the azimuthal direction around each point in aa_grid (corresponding to mblock_aa_grid). That is, for azimuth, a step-wise function is used instead of a piecewise linear one.
Parameters
H The antenna transfer matrix
antenna_dim As the WSV with the same name
antenna_los As the WSV with the same name
antenna_response As the WSV with the same name
za_grid Zenith angle grid for pencil beam calculations
aa_grid Azimuth angle grid for pencil beam calculations
f_grid Frequency grid for monochromatic calculations
n_pol Number of polarisation states
do_norm Flag whether response should be normalised
Author
Patrick Eriksson
Date
2009-09-16
Definition at line 247 of file sensor.cc.
References antenna1d_matrix(), GriddedField4::data, GriddedField::get_numeric_grid(), GFIELD4_AA_GRID, gridpos(), Sparse::insert_row(), last(), ConstTensor4View::nbooks(), ConstVectorView::nelem(), ConstTensor4View::npages(), ConstTensor4View::nrows(), GriddedField4::resize(), Sparse::resize(), and GriddedField::set_grid().
Referenced by sensor_responseAntenna().
find_effective_channel_boundaries()
void find_effective_channel_boundaries (Vector & fmin, Vector & fmax, const Vector & f_backend, const ArrayOfGriddedField1 & backend_channel_response, const Numeric & delta, const Verbosity & verbosity)
Calculate channel boundaries from instrument response functions.
This function finds out the unique channel boundaries from f_backend and backend_channel_response. This is not a trivial task, since channels may overlap, or may be sorted in a strange way. The function tries to take care of all that. If channels overlap, they are combined to one continuous frequency region. therefore the number of elements in the output vectors fmin and fmax can be lower than the number of elements in f_backend and backend_channel_response.
The function also does consistency checking on the two input variables.
The output vectors fmin and fmax will be monotonically increasing.
Author
Stefan Buehler
Parameters
[out] fmin Vector of lower boundaries of instrument channels.
[out] fmax Vector of upper boundaries of instrument channels.
[in] f_backend Nominal backend frequencies.
[in] backend_channel_response Channel response, relative to nominal frequencies.
[in] delta Extra margin on both sides of each band. Has a default value of 0.
delta;
Definition at line 1325 of file sensor.cc.
References CREATE_OUT2, get_sorted_indexes(), is_increasing(), last(), Array< base >::nelem(), ConstVectorView::nelem(), Vector::resize(), and test_and_merge_two_channels().
Referenced by f_gridFromSensorAMSU(), f_gridFromSensorAMSUgeneric(), and f_gridFromSensorHIRS().
gaussian_response()
void gaussian_response (Vector & y, const Vector & x, const Numeric & x0, const Numeric & fwhm)
gaussian_response
Returns a 1D gaussian response
y is the gaussian function on grid x, with max at x0 and width following fwhm.
Parameters
y Calculated response.
x Grid.
x0 The x-position of response centre/max.
fwhm The full width at half-maximum of the response
Author
Patrick Eriksson
Date
2009-09-20
Definition at line 452 of file sensor.cc.
References NAT_LOG_2, ConstVectorView::nelem(), PI, and Vector::resize().
Referenced by antenna_responseVaryingGaussian(), and gaussian_response_autogrid().
gaussian_response_autogrid()
void gaussian_response_autogrid (Vector & x, Vector & y, const Numeric & x0, const Numeric & fwhm, const Numeric & xwidth_si, const Numeric & dx_si)
gaussian_response_autogrid
Returns a 1D gaussian response with a suitable grid
First a grid is generated. The grid is si*[-xwidth_si:dx:xwidth_si], where si is the "standard deviation" corresponding to the FWHM, and dx is biggest possible value < dx_si, to enusre an symmetric grid wth end points exactly at xwidth_si. That is, width and spacing of the grid is specified in terms of number of standard deviations. If xwidth_si is set to 2, the response will cover about 95% the complete response. For xwidth_si=3, about 99% is covered.
y is the gaussian function on grid x, with max at x0 and width following fwhm.
Parameters
x Grid generated.
y Calculated response.
x0 The x-position of response centre/max.
fwhm The full width at half-maximum of the response
xwidth_si The one-sided width of x. See above.
dx_si The grid step size of x. See above.
Author
Patrick Eriksson
Date
2009-09-20
Definition at line 412 of file sensor.cc.
References gaussian_response(), NAT_LOG_2, and nlinspace().
Referenced by antenna_responseGaussian(), antenna_responseVaryingGaussian(), and backend_channel_responseGaussian().
mixer_matrix()
void mixer_matrix (Sparse & H, Vector & f_mixer, const Numeric & lo, const GriddedField1 & filter, ConstVectorView f_grid, const Index & n_pol, const Index & n_sp, const Index & do_norm)
mixer_matrix
Sets up the sparse matrix that models the response from sideband filtering and the mixer.
The size of the transfer matrix is changed in the function as follows: nrows = f_mixer.nelem() ncols = f_grid.nelem()
The returned frequencies are given in IF, so both primary and mirror band is converted down.
Parameters
H The mixer/sideband filter transfer matrix
f_mixer The frequency grid of the mixer
lo The local oscillator frequency
filter The sideband filter data. See sideband_response for format and constraints.
f_grid The original frequency grid of the spectrum
n_pol The number of polarisations to consider
n_sp The number of spectra (viewing directions)
do_norm Flag whether rows should be normalised
Author
Mattias Ekström / Patrick Eriksson
Date
2003-05-27 / 2008-06-17
Definition at line 496 of file sensor.cc.
References GriddedField1::data, DEBUG_ONLY, GriddedField::get_numeric_grid(), GFIELD1_F_GRID, Sparse::insert_row(), last(), ConstVectorView::nelem(), Vector::resize(), Sparse::resize(), sensor_summation_vector(), and ConstVectorView::sum().
Referenced by sensor_responseMixer().
sensor_aux_vectors()
void sensor_aux_vectors (Vector & sensor_response_f, ArrayOfIndex & sensor_response_pol, Vector & sensor_response_za, Vector & sensor_response_aa, ConstVectorView sensor_response_f_grid, const ArrayOfIndex & sensor_response_pol_grid, ConstVectorView sensor_response_za_grid, ConstVectorView sensor_response_aa_grid, const Index za_aa_independent)
sensor_aux_vectors
Sets up the the auxiliary vectors for sensor_response.
The function assumes that all grids are common, and the aux vectors are just the grids repeated.
Parameters
sensor_response_f As the WSV with same name
sensor_response_pol As the WSV with same name
sensor_response_za As the WSV with same name
sensor_response_aa As the WSV with same name
sensor_response_f_grid As the WSV with same name
sensor_response_pol_grid As the WSV with same name
sensor_response_za_grid As the WSV with same name
sensor_response_aa_grid As the WSV with same name
za_aa_independent Flag to indicate that za and aa dimensions are "perpendicular".
This is only valid before the antenna response has been considered.
Author
Patrick Eriksson
Date
2008-06-09
Definition at line 627 of file sensor.cc.
References Array< base >::nelem(), ConstVectorView::nelem(), and Vector::resize().
Referenced by sensor_responseAntenna(), sensor_responseBackend(), sensor_responseBackendFrequencySwitching(), sensor_responseBeamSwitching(), sensor_responseFillFgrid(), sensor_responseFrequencySwitching(), sensor_responseGenericAMSU(), sensor_responseInit(), sensor_responseMixer(), sensor_responseMultiMixerBackend(), sensor_responsePolarisation(), and sensor_responseWMRF().
sensor_integration_vector()
void sensor_integration_vector (VectorView h, ConstVectorView f, ConstVectorView x_f_in, ConstVectorView x_g_in)
sensor_integration_vector
Calculates the (row) vector that multiplied with an unknown (column) vector approximates the integral of the product between the functions represented by the two vectors: h*g = integral(f(x)*g(x) dx)
Basic principle follows Eriksson et al., Efficient forward modelling by matrix representation of sensor responses, Int. J. Remote Sensing, 27, 1793-1808, 2006. However, while in Eriksson et al. the product between f*g is assumed to vary linearly between the grid point, the expressions applied here are more advanced and are completly exact as long as f and g are piece-wise linear functions. The product f*g is then a quadratic funtion between the grid points.
Parameters
h The multiplication (row) vector.
f The values of function f(x).
x_f_in The grid points of function f(x). Must be increasing.
x_g_in The grid points of function g(x). Can be increasing or decreasing. Must cover a wider range than x_f (in both ends).
Author
Mattias Ekström and Patrick Eriksson
Date
2003-02-13 / 2008-06-12
Definition at line 723 of file sensor.cc.
References b0, dx, is_decreasing(), is_increasing(), min, and ConstVectorView::nelem().
Referenced by antenna1d_matrix(), spectrometer_matrix(), and Test().
sensor_integration_vector2()
void sensor_integration_vector2 (VectorView h, ConstVectorView f, ConstVectorView x_f, ConstVectorView x_g_in)
sensor_integration_vector
Calculates the (row) vector that multiplied with an unknown (column) vector approximates the integral of the product between the functions represented by the two vectors.
E.g. h*g = integral(f(x)*g(x) dx)
See Eriksson et al., Efficient forward modelling by matrix representation of sensor responses, Int. J. Remote Sensing, 27, 1793-1808, 2006, for details.
Parameters
h The multiplication (row) vector.
f The values of function f(x).
x_f_in The grid points of function f(x). Must be increasing.
x_g_in The grid points of function g(x). Can be increasing or decreasing. Must cover a wider range than x_ft (in both ends).
Author
Mattias Ekström and Patrick Eriksson
Date
2003-02-13 / 2008-06-12
Definition at line 886 of file sensor.cc.
References dx, is_decreasing(), is_increasing(), and ConstVectorView::nelem().
Referenced by Test().
sensor_summation_vector()
void sensor_summation_vector (VectorView h, ConstVectorView f, ConstVectorView x_f, ConstVectorView x_g, const Numeric x1, const Numeric x2)
sensor_summation_vector
Calculates the (row) vector that multiplied with an unknown (column) vector approximates the sum of the product between the functions at two points.
E.g. h*g = f(x1)*g(x1) + f(x2)*g(x2)
The typical application is to set up the combined response matrix for mixer and sideband filter.
See Eriksson et al., Efficient forward modelling by matrix representation of sensor responses, Int. J. Remote Sensing, 27, 1793-1808, 2006, for details.
No normalisation of the response is made.
Parameters
h The summation (row) vector.
f Sideband response.
x_f The grid points of function f(x).
x_g The grid for spectral values (normally equal to f_grid)
x1 Point 1
x2 Point 2
Author
Mattias Ekström / Patrick Eriksson
Date
2003-05-26 / 2008-06-17
Definition at line 1030 of file sensor.cc.
References gridpos(), interp(), interpweights(), last(), and ConstVectorView::nelem().
Referenced by mixer_matrix().
spectrometer_matrix()
void spectrometer_matrix (Sparse & H, ConstVectorView ch_f, const ArrayOfGriddedField1 & ch_response, ConstVectorView sensor_f, const Index & n_pol, const Index & n_sp, const Index & do_norm)
spectrometer_matrix
Constructs the sparse matrix that multiplied with the spectral values gives the spectra from the spectrometer.
The input to the function corresponds mainly to WSVs. See f_backend and backend_channel_response for how the backend response is specified.
Parameters
H The response matrix.
ch_f Corresponds directly to WSV f_backend.
ch_response Corresponds directly to WSV backend_channel_response.
sensor_f Corresponds directly to WSV sensor_response_f_grid.
n_pol The number of polarisations.
n_sp The number of spectra (viewing directions).
do_norm Corresponds directly to WSV sensor_norm.
Author
Mattias Ekström and Patrick Eriksson
Date
2003-08-26 / 2008-06-10
Definition at line 1096 of file sensor.cc.
References GFIELD1_F_GRID, Sparse::insert_row(), Array< base >::nelem(), ConstVectorView::nelem(), Sparse::resize(), sensor_integration_vector(), and ConstVectorView::sum().
Referenced by sensor_responseBackend().
stokes2pol()
void stokes2pol (ArrayOfVector & s2p, const Numeric & nv)
stokes2pol
Sets up an array of vectors to convert the Stokes vector to different polarsiations.
The measured value is the sum of the element product of the conversion vector and the Stokes vector. Schematically:
y[iout] = sum(s2p[i].*iy(iin,joker)
The order of the vectors follow the coding described for sensor_pol, but zero-based indexing is used here. That is, the first vector (s2p[0]) corresponds to I.
Trailing zeros are not stored, to indicate the required value of stokes_dim*.
Vectors for I, Q, U and V are always normalised to have unit length (one value is 1, the remaining ones zero). The first element of remaining vectors is set to nv (and other values normalised accordingly), to allow that calibartion and other normalisation effects can be incorporated.
Parameters
s2p Array of conversion vectors.
nv Norm value for polarisations beside I, Q, U and V.
Author
Patrick Eriksson
Date
2011-11-01
Definition at line 1196 of file sensor.cc.
Referenced by iy_transmitterMultiplePol(), iy_transmitterSinglePol(), sensor_responsePolarisation(), and yCloudRadar().
test_and_merge_two_channels()
bool test_and_merge_two_channels (Vector & fmin, Vector & fmax, Index i, Index j)
Test if two instrument channels overlap, and if so, merge them.
The channels boundaries are specified in two separate vectors, fmin and fmax. These vectors are both input and output. If merging has happened, they will each be one element shorter.
The positions of the channels to compare is given by the input parameters i and j. It is assumed that the minimum frequency of i is lower than or equal to that of j.
Furthermore, it is assumed that i itself is lower than j.
The range of the first channel (i) will have been extended to accomodate the second channel (j). The second channel will have been removed.
The function also handles the updating of index j: If the two channels do not overlap, j is increased by one.
Function returns true if merging has happened.
Author
Stefan Buehler
Returns
True if channels were merged, otherwise false.
Return values
fmin Lower channel boundaries.
fmax Upper channel boundaries.
Parameters
i Index of first channel.
j Index of second channel.
Definition at line 1249 of file sensor.cc.
References ConstVectorView::nelem(), and Vector::resize().
Referenced by find_effective_channel_boundaries().
Variable Documentation
GFIELD1_F_GRID
const Index GFIELD1_F_GRID extern
Referenced by mixer_matrix(), and spectrometer_matrix().
GFIELD4_AA_GRID
const Index GFIELD4_AA_GRID extern
Referenced by antenna1d_matrix(), and antenna2d_simplified().
GFIELD4_F_GRID
const Index GFIELD4_F_GRID extern
Referenced by antenna1d_matrix().
GFIELD4_FIELD_NAMES
const Index GFIELD4_FIELD_NAMES extern
Referenced by antenna1d_matrix().
GFIELD4_ZA_GRID
const Index GFIELD4_ZA_GRID extern
Referenced by antenna1d_matrix().
NAT_LOG_2
const Numeric NAT_LOG_2 extern
Referenced by gaussian_response(), and gaussian_response_autogrid().
PI
const Numeric PI extern
Referenced by gaussian_response().