ARTS: surface.cc File Reference
surface.cc File Reference
#include <cmath>
#include "auto_md.h"
#include "check_input.h"
#include "complex.h"
#include "geodetic.h"
#include "matpackI.h"
#include "math_funcs.h"
#include "physics_funcs.h"
#include "workspace_ng.h"
#include "surface.h"
Functions
Numeric calc_incang (ConstVectorView rte_los, ConstVectorView specular_los)
calc_incang
void surface_specular_R_and_b (Workspace &ws, MatrixView surface_rmatrix, VectorView surface_emission, const Complex &Rv, const Complex &Rh, const Numeric &f, const Index &stokes_dim, const Numeric &surface_skin_t, const Agenda &blackbody_radiation_agenda)
surface_specular_R_and_b
Detailed Description
Author
Patrick Eriksson Patri.nosp@m.ck.E.nosp@m.rikss.nosp@m.on@c.nosp@m.halme.nosp@m.rs.s.nosp@m.e
Date
2012-02-06
This file contains internal functions associated with the surface.
Definition in file surface.cc.
Function Documentation
calc_incang()
Numeric calc_incang (ConstVectorView rte_los, ConstVectorView specular_los)
calc_incang
Calculates the incidence angle for a flat surface, based on rte_los and specular_los.
Parameters
incang Return: Incidence angle.
rte_los Input: As the WSV with the same name.
specular_los Input: As the WSV with the same name.
Author
Patrick Eriksson
Date
2012-11-15
Definition at line 72 of file surface.cc.
References abs.
Referenced by surfaceFlatRefractiveIndex().
surface_specular_R_and_b()
void surface_specular_R_and_b (Workspace & ws, MatrixView surface_rmatrix, VectorView surface_emission, const Complex & Rv, const Complex & Rh, const Numeric & f, const Index & stokes_dim, const Numeric & surface_skin_t, const Agenda & blackbody_radiation_agenda)
surface_specular_R_and_b
Sets up the surface reflection matrix and emission vector for the case of specular reflection.
The function handles only one frequency at the time.
See further the surface chapter in the user guide.
Parameters
surface_rmatrix Out: As the WSV with the same name, but slice for one direction and one frequency.
surface_emission Out: As the WSV with the same name, but slice for one direction and one frequency.
Rv In: Complex amplitude relection coefficient for vertical polarisation.
Rh In: Complex amplitude relection coefficient for horisontal polarisation.
f In: Frequency (a scalar).
stokes_dim In: As the WSV with the same name.
blackbody_radiation_agenda In: As the WSV with the same name.
surface_skin_t In: As the WSV with the same name.
Author
Patrick Eriksson
Date
2004-09-24
Definition at line 106 of file surface.cc.
References abs, blackbody_radiation_agendaExecute(), ConstMatrixView::ncols(), ConstVectorView::nelem(), and ConstMatrixView::nrows().
Referenced by surfaceFlatRefractiveIndex().