ARTS: test_sparse.cc File Reference
test_sparse.cc File Reference
Tests for sparse matrices.
#include <stdexcept>
#include <iostream>
#include "matpackII.h"
#include "xml_io.h"
Functions
void test3 ()
void test40 ()
void test41 ()
void test42 ()
void test43 ()
void test44 ()
void test45 ()
void test46 ()
void test47 ()
void test48 ()
void test49 ()
int main ()
Detailed Description
Tests for sparse matrices.
Author
Stefan Buehler sbueh.nosp@m.ler@.nosp@m.ltu.s.nosp@m.e
Date
Tue Jul 15 15:10:44 2003
Add more tests here as necessary...
Definition in file test_sparse.cc.
Function Documentation
main()
int main (void)
Definition at line 423 of file test_sparse.cc.
References test49().
test3()
void test3 ()
Definition at line 35 of file test_sparse.cc.
References M.
test40()
void test40 ()
Definition at line 179 of file test_sparse.cc.
References joker, mult(), and Sparse::rw().
test41()
void test41 ()
Definition at line 208 of file test_sparse.cc.
References Sparse::rw(), and transpose().
test42()
void test42 ()
Definition at line 239 of file test_sparse.cc.
References mult(), Sparse::rw(), and transpose().
test43()
void test43 ()
Definition at line 256 of file test_sparse.cc.
References Sparse::rw().
test44()
void test44 ()
Definition at line 283 of file test_sparse.cc.
References Sparse::insert_row(), Sparse::ncols(), Sparse::nrows(), and Sparse::rw().
test45()
void test45 ()
Definition at line 303 of file test_sparse.cc.
References C, FILE_TYPE_ASCII, mult(), Sparse::ncols(), Sparse::nrows(), xml_read_from_file(), and xml_write_to_file().
test46()
void test46 ()
Definition at line 337 of file test_sparse.cc.
References FILE_TYPE_ASCII, Sparse::ncols(), Sparse::nrows(), transpose(), xml_read_from_file(), and xml_write_to_file().
test47()
void test47 ()
Definition at line 367 of file test_sparse.cc.
References Sparse::make_I().
test48()
void test48 ()
Definition at line 378 of file test_sparse.cc.
References abs, and Sparse::rw().
test49()
void test49 ()
Definition at line 396 of file test_sparse.cc.
References add(), C, Sparse::rw(), and sub().
Referenced by main().