ARTS: test_linalg.cc File Reference
test_linalg.cc File Reference
Test for the linear algebra functions.
#include <iostream>
#include "lin_alg.h"
#include "make_vector.h"
#include "array.h"
Functions
void test_lusolve1D (void)
void test_lusolve4D (void)
void test_matrix_exp4D (void)
Test for the matrix exponential function (4D matrix)
void test_matrix_exp1D (void)
Test for the matrix exponential function (3D matrix)
void test_matrix_exp3D (void)
Test for the matrix exponential function (3D matrix)
int main (void)
Detailed Description
Test for the linear algebra functions.
Author
Claudia Emde claud.nosp@m.ia.e.nosp@m.mde@d.nosp@m.lr.d.nosp@m.e
Date
Thu May 2 14:37:57 2002
Definition in file test_linalg.cc.
Function Documentation
main()
int main (void)
Definition at line 354 of file test_linalg.cc.
References test_lusolve1D().
test_lusolve1D()
void test_lusolve1D (void)
The function tests the LU-decompusition method for solving a 1D linear equation system. It uses the functions 'ludcmp' and 'lubacksub'.
Definition at line 44 of file test_linalg.cc.
References lubacksub(), and ludcmp().
Referenced by main().
test_lusolve4D()
void test_lusolve4D (void)
The function tests the LU-decompusition method for solving a linear equation system. It uses the functions 'ludcmp' and 'lubacksub'.
Definition at line 104 of file test_linalg.cc.
References lubacksub(), ludcmp(), and mult().
test_matrix_exp1D()
void test_matrix_exp1D (void)
Test for the matrix exponential function (3D matrix)
Definition at line 301 of file test_linalg.cc.
References matrix_exp(), and q.
test_matrix_exp3D()
void test_matrix_exp3D (void)
Test for the matrix exponential function (3D matrix)
Definition at line 322 of file test_linalg.cc.
References matrix_exp(), and q.
test_matrix_exp4D()
void test_matrix_exp4D (void)
Test for the matrix exponential function (4D matrix)
Definition at line 258 of file test_linalg.cc.
References matrix_exp(), and q.